### ISSUE TITLE
ability to hear acts incredibly strange while ventcrawling

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#10005]
When ventcrawling, your hearing ability is really odd. You can't hear yourself, you can't hear your radio and you can't hear others, but apparently others can hear you just fine.

When you crawl into a tile where the pipe is underneath a glass window/tinted window, you suddenly become able to hear yourself, your radio and other people in the room.

**Comment by Miauw62** [comment]
lel fuck if i know
get_hear is fully recursive but to get everybody in view it first calls
view() with some extra arguments

**Comment by phil235** [comment]
It's most likely a visibility issue. You are inside a pipe whose invisibility is lower than your see_invisible. If you are inside a gas pipe that is visible (floor tile crowbared) you can hear yourself fine. And you hear yourself when below a window because there's no floor tile below it, only plating, so the pipe is visible.
