### ISSUE TITLE
Airlock Power wire-datum wires do not actually work as you might expect

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#10014]
Airlocks have two main power lines (aka test wire) and two secondary power lines.
However, only one of each of those wires worked when pulsed. This is why the term "test wire" is singular in game lingo: If you use a wirecutter to test the wires, you'll see that there are actually two main power wires, however, only one of them will actually work with a multitool (which is the most popular hacking choice).

https://github.com/d3athrow/vgstation13/pull/4992 for more on a fix

**Comment by optimumtact** [comment]
I honestly can't tell if this is a bug or a design decision

**Comment by 9600bauds** [comment]
wow shocking!!

**Comment by RemieRichards** [comment]
old title was confusing as fug.

**Comment by PKPenguin321** [comment]
Thought this was intended. You pulse the main line and the backup power line kicks in; you cut backup and then the door goes down for a while. You cut both, and the door stays off (or at least it should, IIRC).

**Comment by duncathan** [comment]
There's two of each.

**Comment by 9600bauds** [comment]
That exactly. Don some gloves and go wirecutter snipping at every wire, you'll find two that turn the main power off. However only one of both will work when pulsed.
When you look at the fix for this it's clearly just a small syntax error, the problem is that it's been broken for so long that people got used to it being broken.

**Comment by optimumtact** [comment]
This was fixed at some point
