### ISSUE TITLE
Turning someone into a changeling via admin magic makes them unable to speak.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10048]
More specifically, only their name is printed out, but no text comes out, not even "says" or "asks" or whatever.

http://i.imgur.com/unVhvnW.png

@Miauw62

**Comment by palpatine213** [comment]
It's the transform to initial appearence button that seems to cause it. Pressing it causes the bug whether you delight them or not.

**Comment by Boggart** [comment]
This is more than just not being able to speak, you can't interact with anything besides by bumping.
If you get lasered into crit, you just lay there, you can't get up or hear anything but you can see fine. When I was hit while in crit, instead of dying my underclothes vaporized. While in crit, my health indicator showed only yellow, not crit.

When hit with a weapon while not in crit, you become able to speak and act normally.

Probably related:
```
runtime error: Cannot read null.species
proc name: handle blood (/mob/living/carbon/human/handle_blood)
  source file: blood.dm,48
runtime error: Cannot read null.species
proc name: say quote (/mob/living/carbon/human/say_quote)
  source file: say.dm,4
runtime error: Cannot execute null.mutations get spans().
proc name: get spans (/mob/living/carbon/human/get_spans)
  source file: say.dm,33
Warning: further proc crash messages are being suppressed to prevent overload...
```

**Comment by Miauw62** [comment]
i suspect that the transform to initial appearance button is fucked.
