### ISSUE TITLE
Nearly everything passed through qdel() does not have a QDEL_HINT attached to it.

### ISSUE THREAD

**Issue by tigercat2000** [tgstation/-tg-station#10091]
Problem description: Almost every object that is passed through qdel falls into the 'else' category of this switch: https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/garbage.dm#L109-L123

This is due to most /Destroy() procs only containing a ..() at the end (ex: https://github.com/tgstation/-tg-station/blob/master/code/game/objects/objs.dm#L15) instead of a ". = ..()" or "return ..()"

What did you expect to happen: Every subtype of datum without a custom qdel hint to go into category 1, QDEL_HINT_QUEUE, as it is defined at the top in /datum/proc/Destroy()

What happened instead: Everything without a custom qdel hint skipped category 1 and ended up caught in the else.

Why is this bad/What are the consequences: There are no significant consequences on -tg-, as the garbage collector can handle datums and all subtypes. However, a potential issue is something being Queued that should definitely not be Queued. 

Steps to reproduce the problem: Add a "world << "gc switch skipped, [A], [A.type] went into else"" above [this line](https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/garbage.dm#L123). Observe everything without a custom qdel hint triggering the message.

Server: Local test server
Revision: 1f147b662e5ac0211fb7878926da6746b53456b5

**Comment by MrStonedOne** [comment]
Thats intended, because that didn't switch didn't exist until two months ago and I didn't want to change all 5000 Destroys.

Default behavior is to do QUEUE

**Comment by MrStonedOne** [comment]
You have to understand how qdel works, All things should be qdel'ed that are a child of datum. This includes mobs, atoms, objs, images, sounds, turfs, etc. 

Queued delete doesn't actually do what it sounds like it does. It is an ensured garbage collection system.

In byond, if the last var pointing to a thing no longer points to that thing, that thing is destroyed because its not being used anymore. This is called garbage collection.

what qdel does, is it will tell a thing to find and free up references to it, so that it can be naturally garbage collected by byond. 30 seconds later, it will check that this happened right, and that byond garbage collected the object, and if it didn't, it will manually del() it, causing byond to handle clearing the reference.

We do it this way because in byond, calling del() on an object takes a decent amount of time, but having byond figure out that the object isn't being used doesn't. However we don't want loose objects that are suppose to be deleted hanging around, so this gives us the best of both worlds.

**Comment by tigercat2000** [comment]
@MrStonedOne Ah, understood. I discovered that the Destroy() chain doesn't actually work as expected with making a hybrid system based on the qdel hints, for a GC that does not support anything but atom/movable. It was requested that I report that the Destroy() chain isn't intact, however due to the fact that the -tg- garbage collection system can handle anything that gets queued, it seems like a non-issue.
