### ISSUE TITLE
Wall flashers do not affect cyborgs

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#10111]
Revision: aa5541070c822346dc1ef02b858e15f3ebd48dd6 

ZE FLASHERS. ZEY DO NOTHING.
Borgs can move and act after being in the AoE of the mounted flashers just fine.
To be fair, for AI defenses they were shit to begin with. But at least they should be working shit.

I would write more if there was more to say.

**Comment by xxalpha** [comment]
You mean the portable flashers or the wall flashers? Or both?

**Comment by Actionb** [comment]
I was talking about the wall flashers. I am not so sure if it is the same with the portable ones.

**Comment by Thunder12345** [comment]
I think they do. I subverted the AI with an emagged borg earlier, it looked like it got stunned by the flasher, since it stopped trying to keep the power on for a bit after the flash.

**Comment by Actionb** [comment]
I am almost certain AoE flashes just dont work on borgs. Using a flash in hand against a cyborg didn't seem to stop him from accurately using his stunbaton and cuffing people.

**Comment by xxalpha** [comment]
Confirmed.

**Comment by phil235** [comment]
That change was actually intended in #8424. It affects both wall flashers and portable flashers. The underlying issue is that cyborg flashing is inconsistent. The flash from welding is stronger than the flash from flashers (sunglasses only protects against the latter), and since cyborg needs to be able to weld they require the higher protection, thus making them immune to flashers (but not flashbang and the flash item).

If we want to allow flashers to work on silicon, the best way would be to have welding flash use a separate proc.

**Comment by Actionb** [comment]
I've always considered the mounted flasher as the AI's last defense against a rogue cyborg. Obviously a solution must be found. Syndiborgs have it easy enough with the AI, considering that the only way to really stop them is to depower the chamber airlock. But by the time the motion sensors give alarm, they are pretty much already inserting their esword into your USB port.

**Comment by Dorsisdwarf** [comment]
This needs to be fixed, pretty urgently, too
