### ISSUE TITLE
CE getting objectives to steal blueprints and full plasma tank

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#10247]
I thought these were blacklisted. I've been seeing CEs get this recently.

**Comment by Marflowerose** [comment]
Also had CMO with hypospray as objective. Quite common for Engi/atmos/scientist to get steal plasma aswell. 
I don't see this as such a big problem since people generally consider objectives more as guidelines to bring excitement to crew. It's moderately rare that traitor just continues shift as normal after completing simple objectives since it leaves them time for more interesting ways of antagging. Greentexting causes joy for five minutes, plasma flood and loose singulo cause fun for 30 minutes, especially when lag makes 1 ingame minute last 2 minutes.

**Comment by palpatine213** [comment]
The issue Is, I'm definitely sure those objectives were blacklisted a while ago. Them showing up again, means something broke.

**Comment by palpatine213** [comment]
@Incoming5643 Do you think changing antag selection messed up the blacklist?

**Comment by Incoming5643** [comment]
it's possible, but I don't think objectives give out before job selection.

I'll look into it

**Comment by GunHog** [comment]
I also once got the 'steal an unused slime extract' objective as the RD.
