### ISSUE TITLE
html_interface: port to security camera computers?

### ISSUE THREAD

**Issue by nullquery** [tgstation/-tg-station#10321]
Speaking of computers that work with input(): the security camera computers have worked this way since day 1, and it's very annoying to switch camera's (even if you know the name you still have to scroll through the list because you can only seek to the first letter of the camera name).

An approach that uses the minimap, like how the crew monitoring computer now works, is feasible and I think would take ~2 hours of time to develop.

But I'm not sure what to make of it. I could turn it into a clone of the crew monitoring computer, except with cameras on the table and dots on the minimap representing those cameras.

Or I could go a different route, perhaps not showing a table at all but instead making the minimap bigger and only adding dots for the cameras (green dots would be active cameras, red dots would be inactive).

What do you think?

**Comment by duncathan** [comment]
I like the idea of the table. More convenient, I think.

**Comment by optimumtact** [comment]
It's strange to me that they don't just work like the AI eye does

**Comment by Iamgoofball** [comment]
@nullquery if I can click on an area and get an AI eye view of that area's camera cover with static over areas the cameras in that area can't see, i would love you forever

**Comment by Alek2ander** [comment]
If this is added AI should get a clickable minimap too.

**Comment by nullquery** [comment]
@Alek2ander This was already implemented with the crew monitoring computer changes. See https://github.com/tgstation/-tg-station/pull/10202#issuecomment-116333741

**Comment by nullquery** [comment]
What about reusing the crew monitoring computer and combining it with the security cameras computer? You'd have a single computer that allows you to get both cameras and people. By pressing a button on the computer you'd be able to switch back and forth between the two views.

Clicking the minimap as AI already moves you to that camera. The only change would be that it'd do the same for humans, but only if you're using a computer (handheld sensor does not support this).

**Comment by freerealestate** [comment]
Personally I'd prefer no table, as the current version doesn't scroll to the item you're currently highlighting on the minimap, which can make finding the item you're highlighting in the list difficult. That and the table means the minimap has to be quite small (though there's room for it to be slightly bigger), which makes the dots more finicky to click, especially when they're adjacent to one another (although this wouldn't often be the case with a security camera console). I don't think the table would be necessary though, as it would just say the name of the camera and its status, which you don't need if you can see its location and status on the minimap.

>It's strange to me that they don't just work like the AI eye does

I think it's due to lag.

**Comment by nullquery** [comment]
To-do: make the crew monitor scroll to the highlighted item in the table.

**Comment by freerealestate** [comment]
That'd be great. I didn't request it because I wasn't sure if it was
possible or not.

**Comment by nullquery** [comment]
Everything is possible, just in varying degrees of difficulty. Don't hold back asking anyway, if only to find out why it's difficult.

**Comment by Strathcona** [comment]
Honestly having it work like the AI eye does would be really nice. I'd much rather a camera console act primarily for viewing cameras on a network and have the crew console be something that works very different with all that minimap goodness. This removes any possible overlap between the two and lets both of them do their jobs effectively.

**Comment by RemieRichards** [comment]
Is everybody forgetting the advanced camera console that does indeed function like an AI eye?
it's the same as the Alien Abductor console except it's themed as sec computer, except nowhere uses them for balance.

**Comment by freerealestate** [comment]
I'd prefer the minimap. The lag on the AI eye on larger rounds, especially
with bad latency, makes it a pain to search the station with. I remember a
prominent coder saying a few years ago that the AI eye caused quite a bit
of lag, too. I'm not sure if that's true or not, but it's something to
consider.

**Comment by Strathcona** [comment]
Oh, huh. Never seen that console before.The minimap might be better than the AI eye esque console if it was removed for balance reasons. Why not just give Sec a crew monitor console instead of making a new one with similar or the same functionality? Sec are crew members and the information you want (vitals and location) are already available from there. 

Having the warden run to the tracking console upon a report of harm seems reasonable and also passively gives him more tools to ensure the cohesion of the Sec force. This often doesn't happen much as is because all you have is radio calls to go off of.

**Comment by Miauw62** [comment]
>making cameras even more OP

i'm ok with a searchable menu for cameras, but it really shouldnt go beyond that.

**Comment by nullquery** [comment]
IMO a big problem for SS13 is the lack of really good UI. It's a steep learning curve for new players and it makes the game look unattractive.

I think we should examine the underlying problem of what makes cameras so OP and not deliberately break or reduce the UI to fix this symptom.

So I guess my question now is: what makes cameras OP and what can we do about it that would generically fix it for both AI and human players?

**Comment by clusterfack** [comment]
We've had a nanoUI version of this for some time on /vg/ and frankly it's really a non-issue. The usability of the UI is a big bonus to the player experience while overall it's not significantly faster than the crappy version with a list of names (if you knew all the camera names-locations by heart).

**Comment by Dorsisdwarf** [comment]
Code Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
