### ISSUE TITLE
Something happened to make fireballs really weak

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10339]
They used to down someone with just two good hits.

Now, it takes about 4 direct hits to just barely crit them. Even after the 3rd one they can still get up perfectly fine

and I'm talking about the dumbfire fireball spell.

**Comment by Incoming5643** [comment]
it's because fireballs explode when they're within a tile of someone, including when they're a tile in front of someone, so unless a person happens to move into a tile a fireball is also moving into, there are no direct collisions. This lessens the damage considerably.

That said it stuns and sets you on fire, and the cooldown of the spell is long enough to where you can chain stun anyone, so I never thought it necessarily had to be fixed.

**Comment by xxalpha** [comment]
Why doesn't it explode on bump?

**Comment by phil235** [comment]
This is happening because of my change to projectile code. (#8687 , more specifically https://github.com/tgstation/-tg-station/pull/8687/files#diff-99ebcf7ba775c1dfd1e8fd98cdbebe11R6) I think a solution could be to modify the on_hit() proc of all projectiles causing an explosion to make the explosion happen on the target's location.

**Comment by tkdrg** [comment]
This isn't really an issue. Fireballs are still very much powerful and viable.
