### ISSUE TITLE
Space cleaner can make genetic powers invisble.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10355]
I was working on powers in genetics when a drone came in and sprayed me with some cleaner to clean my bloody lab coat.This made all the powers I currently had (hulk and cold resistance) invisible. Possible you could use the shower to same effect as well.

**Comment by Incoming5643** [comment]
Space cleaner so strong it'll wipe the genetic abnormalities right off your face.

**Comment by Actionb** [comment]
I lost the visuals for my powers in a round yesterday and was not sprayed with any space cleaner that I know of. I put on a biosuit helmet after repeatedly getting facehugged as a hulk - when I took it off a few moments later, hulk and TK were no longer visible but still active. Since it was kinda hectic, I have no idea if the change happened while getting face hugged or due to the helmet?

**Comment by phil235** [comment]
The real issue comes from the update_icons() proc (for both human and monkey), the deletes the genetics overlays.

**Comment by RemieRichards** [comment]
I TOLD razh not to have mutation icons outside of update_icons().
but nooooo...

**Comment by phil235** [comment]
There's a whole bunch of stuff making genetics powers invisible. See #11255 and  #10772
