### ISSUE TITLE
Floorbots will not repair hull breaches

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10362]
The seem to just ignore them. They will still repair damaged hull plating, and add floortiles to hull, but they will not patch up holes.
They do seem to engage traction magnets when they see a hullbreach however.

**Comment by GunHog** [comment]
Could they be...drifting? "Traction magnets" is just a fancy way of saying "anchored", this is to make them resist space wind. However, space drifting ignores the anchored flag, so the problem is more likely that the floorbot cannot physically stop on the space turf. If anyone know the correct way to prevent space drifting, let me know.

If you believe this issue is NOT related to drifting, please explain further, and ensure that the bot was not responding to PDA or AI overrides.

**Comment by palpatine213** [comment]
The bot was not responding to any AI or pda overrides. When it would see a breach, it would turn on magnets, and just sit there. If it had other things enabled, like replacing or repairing floor tiles, if would do those. The bot would not even make an attempt to approach the breach.
Turning the bot off then on does not seem to fix the issue.

**Comment by GunHog** [comment]
The problem seems to stem with AStar. I will need the help of @Aranclanos to resolve this issue. The changes to AStar "reachableAdjacentTurfs" does not account for things that can target or travel in space. *This includes changeling stings.*
