### ISSUE TITLE
Runtime error with proc IsAvailible (/datum/spellbook_entry/summon/events/IsAvailible)

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10424]
```
runtime error: Cannot read null.name
proc name: IsAvailible (/datum/spellbook_entry/summon/events/IsAvailible)
  source file: spellbook.dm,372
  usr: null
  src: Summon Events (/datum/spellbook_entry/summon/events)
  call stack:
Summon Events (/datum/spellbook_entry/summon/events): IsAvailible()
the spellbook of  (/obj/item/weapon/spellbook/oneuse/blind): New(the floor (39,131,5) (/turf/simulated/floor/wood))
the spellbook of  (/obj/item/weapon/spellbook/oneuse/blind): New(the floor (39,131,5) (/turf/simulated/floor/wood))
make mining asteroid secret()
/datum/controller/game_control... (/datum/controller/game_controller): setup(null)
: New()
```

Ran the code several times for reasons unrelated to this, and one time this popped up before roundstart. Game hadn't even started setting up yet. I hadn't touched the file at all.

**Comment by phil235** [comment]
The line in question is `ticker.mode.name != "ragin' mages" && !config.no_summon_events`. It runtimes specifically because the game hasn't started so ticker.mode isn't set. 

It happens because the mining asteroid secret room is spawning a spellbook and spellbook/New is wrongfully calling summon/events/isAvailible() when it should only call it for actual spellbooks and staves.
https://github.com/tgstation/-tg-station/blob/3c15ee47313e083f8cd5ac71c35b084326cb25f0/code/game/gamemodes/wizard/spellbook.dm#L408
I think `var/entry_types = typesof(/datum/spellbook_entry) - /datum/spellbook_entry - /datum/spellbook_entry/item - /datum/spellbook_entry/summon`
should be : `var/entry_types = typesof(/datum/spellbook_entry) - /datum/spellbook_entry - /datum/spellbook_entry/item - typesof(/datum/spellbook_entry/summon)`

**Comment by Incoming5643** [comment]
this is the cause of #10232
