### ISSUE TITLE
Unable to set Alien color in character preferences

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10438]
No matter what color I pick it always errors out back to me with this:
Invalid color. Your color is not bright enough

**Comment by Incoming5643** [comment]
the brighter colors are the ones closer to the center of the color selector, are you sure it's every color?

**Comment by Ikarrus** [comment]
I tried pure white and it gave me the same error

**Comment by Incoming5643** [comment]
the proc that checks for brightness, ReadHSV(hsv), hasn't been touched in years.

Something must be weird with the value being given to it

**Comment by Incoming5643** [comment]
Timetable suggests issue spawned from https://github.com/tgstation/-tg-station/commit/b8811f23e0b793b3154a348dbb31b56cfa6fd39d (the kitty cat one)

specifically

ReadHSV(temp_hsv)[3] < ReadHSV("#7F7F7F")[3]))

I am not sure this is a valid use of this proc...

**Comment by Incoming5643** [comment]
A Logic operator was reversed, it's >= elsewhere in the code. This check made literally every color invalid because it was checking that a color wasn't >=<.

At least that's my hunch, testing it now

**Comment by Incoming5643** [comment]
As a work around if you go to the advanced tab on color selection it will work fine.

The problem here seems to be that the hardcoded color selector returns a color as a format that isn't supported. (advanced which gives #RRGGBB").

None of these procs work right with any color that isn't formated in one of the following formats:
#RGB
#RGBA
#RRGGBB
#RRGGBBAA

Why this has suddenly become a problem now I have no idea, but someone needs to figure out what color format the color picker is spitting out.
