### ISSUE TITLE
Clothing Being Destroyed While Out Of Crit

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#10549]
A few days ago I was playing as a late joining admin spawned Wizard, the crew had access to weapons from another wizards summon guns spell.

I entered security and was immidently shot by a syndicate shotgun that had explosive rounds.  

[11:14:26]ATTACK: Happi Futur(kingofcarrotflowerspt1) shot Frank the Fabulous (as Sofo Oofs)(steelpoint) with The bullet (NEWHP: 4)

I survived the attack but my robes were destroyed, being defenceless and unable to do anything I was gunned down via laser fire around ten seconds later (according to the logs).

According to @Ikarrus you should only lose clothing from a explosive attack that would normally knock you into critical, but in this case I had four HP after the attack and was not in critical when I lost my clothing.

(On the record I'm against the whole concept, but a bug is a bug).

**Comment by Iamgoofball** [comment]
also just for balance's sake, wiz biz clothing shouldn't be able to get destroyed

**Comment by xxalpha** [comment]
Clothes destruction is just bad all around, in my opinion.

**Comment by Ikarrus** [comment]
armor = list(melee = 30, bullet = 20, laser = 20, energy = 20, bomb = 20, bio = 20, rad = 20)

So it turns out that wizard armor has bomb protection, which is probably what protected you from being crit.

You were caught in the heavy damage range of an explosion, which normally crits you, but you were lucky enough that your armor absorbed just enough damage to keep you barely alive, but the shredding still proceeds (albiet with a very low chance) as it's still ex_act(2)

So you were very lucky to have not died from the blast, but unlucky enough to lose your clothes, too. Both had a 1 in 5 chance of happening.
