### ISSUE TITLE
Reactionary Explosions are Lopsided

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10564]
Simply put, reactionary explosions don't exactly behave properly; they're quite lopsided and strongly favor blasts towards the north-east. 

![uhhh](http://i.imgur.com/gbEgQ00.png)

**Comment by Dorsisdwarf** [comment]
This should probbably be High Priority.

**Comment by phil235** [comment]
The issue comes from the fact that the proc starts to explode turfs before the explosion calculations for all turfs are done, which means the turf are processed from bottom to top and left to right, line by line. This in turn means that when handling the top half of the explosion the turf are exploded from the closest to epicenter to the furthest, so each new turf has its calculation done as if there were no walls (now destroyed) between it and the epicenter.
