### ISSUE TITLE
Decloner does not Declone

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#10625]
I checked the Projectiles out of boredom, and noticed that Energy/Declone projectile has no damage set, just damage type. So it defaults to 0 damage.
So it does no cloning damage. At all.
This should be an easy fix.

**Comment by GunHog** [comment]
It does radiation damage. I suspect it was simply nerfed at one point. It even has a design in the protolathe, but raised to nigh-impossible to reach levels. If it DID do clone damage, it would be a truly terrifying weapon, as there is but one way to cure clone damage.

**Comment by Fox-McCloud** [comment]
A longgggggg time ago...like clear back in 2011 it did 40 clone 70 radiation (!)....that was mport days.

EIther case it was nerfed some time in 2012 and has been pretty much the epitome of "shitgun" ever since.

throw 20 clone damage, in my opinion and lower R&D requirements so it's actually possible to create and see what happens., IMO.

**Comment by Lumipharon** [comment]
It can be made currently, by abusing the experimentor.
It's extremely tedious and pointless though.
