### ISSUE TITLE
Ya broke Toxins you idiots

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#10682]
Toxins gas valves are all fucking weird now, and they don't let gas travel through them. 

When you click them the sprite acts all goofy and I can't get them to work for the life of me.

**Comment by WJohn** [comment]
A major atmos pipe and machines rewrite was bound to have bugs. Should be getting all fixed and cleaned up over the next couple of days.

**Comment by duncathan** [comment]
A fix is being worked on. The sprite going wonky was me forgetting to finish something; the not working thing is something to do with the connector ports. Valves themselves work fine (besides the sprite thing)

**Comment by duncathan** [comment]
Alright, this issue is next on my list. Just so everyone knows, it's fixed by unwrenching then wrenching the valves back into place. Doing it to the connector might work too, who knows.

The underlying issue is that, for whatever reason, at roundstart, connector ports are not building their pipeline properly if their node is another device. Can't fathom why, but I'll try and puzzle out a fix.
