### ISSUE TITLE
Exofab causing lag (on metastation at least)

### ISSUE THREAD

**Issue by Nanotransistor** [tgstation/-tg-station#10759]
I tried messing with the exofab that is hidden in maint, and when i click to sync it gets stuck in updating, then when i close the window and try to click on the exofab again, it lags the entire server.

**Comment by Jalleo** [comment]
@metacide

**Comment by xxalpha** [comment]
It's laggy because it is listing the contents of the entire area the fabricator is in, and guess what, the maintenance it is in is big.

Then it doesn't work because there isn't an rdconsole nearby.

**Comment by Supermichael777** [comment]
Because the get area procs are hogs and this is a button that literally calls get area.  realistically this will be solved by mapping smaller sub areas in maintenance. most of the maintenance areas are already split by doors so their are already visible and semi logical divides to work from. with meta and other single maintainer maps the fix should go relatively easily but box might take a while.

**Comment by xxalpha** [comment]
If my fix is merged, that won't be necessary.
