### ISSUE TITLE
opaque windows are terrible.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#10769]
literaly why the feature. all they do as far as I can tell the let light through and provide a pathetically easy entry point.  most of them seem to serve the later purpose, separating two equally bright or dark areas. also you can't make them so it can't be built into cool projects. seem under implemented in the current setup.

**Comment by Supermichael777** [comment]
a feature and mapping request. want them to be build-able/replaced with normal windows. my main problem with them is that they make areas claustrophobic.

**Comment by Dorsisdwarf** [comment]
I think there's already an issue or ten about Tinted Windows being shite

**Comment by WJohn** [comment]
Tinted windows actually DO serve a minor purpose, in that they can be destroyed by fire and by smashing without any tools. This means fires can spread through to places while keeping some sort of privacy around. I'd kind of like to see these returned to R&D, frankly.

**Comment by Supermichael777** [comment]
^literally half of what I said. also who is ever not varying something strong enough to break glass?

**Comment by Cheridan** [comment]
I don't understand this issue. Are you requesting that more be added? There's been a push to remove these because yes, tinted windows are bad for many reasons. There shouldn't be any on boxstation left.

If you're referring to tinted windows on Metastation, forward that feedback to Metacide, not the issue tracker
