### ISSUE TITLE
stypic/silver powder's ingest toxin is based on the beaker size instead of the amount drank.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#10786]
So after driving me to depression, a CERTAIN scientist showed me that the ingestion damage caused by stypic/silver is based around the beaker size and not the amount taken.

This means a bluespace beaker full of stypic/silver can instantly put a person into deep critical with 1 whole sip from the beaker.

@Iamgoofball 
or
@kingofkosmos 

i dont know which since it involves goofchem and recently changed beakers

**Comment by Iamgoofball** [comment]
what the fuck

this most definitely is not me

**Comment by Shapsy** [comment]
It's not based on the beaker size, the issue is that the damage taken is based on the total amount of styptic or whatever that's in the beaker, rather than how much you drink, which can lead to a hilarious situation where sipping 5u of styptic from a bluespace beaker filled with 300u of styptic will instantly deal 150 tox damage (or 145 damage if you drink from a beaker with 290u and so on)

**Comment by MMMiracles** [comment]
i was close ENOUGH.

**Comment by Iamgoofball** [comment]
@Shapsy 

Sounds like the beaker sipping is feeding in the wrong volume number. Easy fix, probably.

**Comment by kingofkosmos** [comment]
My bad.

**Comment by phil235** [comment]
Technically it's not the feeding volume that is wrong it's the amount used by reaction(user, INGEST). I fixed some of those in IV drips and borghydro.
