### ISSUE TITLE
Lizard tail vanishes when facing up.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10805]
It seems to be specifically the tail, as the spines still show.
![](http://i.imgur.com/ulwfqRC.png)

This also happens when not wearing anything at all.

This is conveniently fixed when you wag your tail. Your tail re-appears if you stop wagging.

**Comment by Incoming5643** [comment]
Has anyone touched mob sprite layering recently?

**Comment by Incoming5643** [comment]
caused by https://github.com/tgstation/-tg-station/pull/10659/ (specifically https://github.com/phil235/-tg-station/blob/76feff5dfa04e8311db37d3f68ce0b24d3a3c29a/code/modules/mob/living/carbon/human/update_icons.dm) cutting out the first 8 sprite layers (?!) as well as the total number of layers (!?!?!)

I can fix this but is it really ok to have cut out all those layers?

@phil235

**Comment by phil235** [comment]
Apparently I didn't notice that BODY_FRONT_LAYER and other layer defines were defined twice in the code...

**Comment by Incoming5643** [comment]
It's REALLY stupid.

I'm working on seeing if I can just have everything in __DEFINE and keep this nonsense consistent going foward

**Comment by phil235** [comment]
sounds good to me

**Comment by Incoming5643** [comment]
So I can do that fairly painlessly

Except for some reason it breaks SMOOTH MOVEMENT of all things... where is that even handled in code?

**Comment by francinum** [comment]
Breaks catpeople too.

**Comment by francinum** [comment]
Doesn't break Smoothmovement, That's Dorsisdwarf fault.
