### ISSUE TITLE
Multiverse Sword: an "I ded pls nerf" story

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#10848]
Seriously, the multiverse sword is neat as an admin only item, but as an ordinary wizard item?
Lets look at what it does
1) super robust e-sword/katana levels of rape
2) spawns INFINITE new antags with their own swords of rape with an objective to murder everyone else
3) spawned plebs can spawn more plebs with swords of their own

You might as well just turn on highlander and enable respawn - it's functionally the same shit.

**Comment by Jalleo** [comment]
Add a chance for the sword to create a anti antag?

**Comment by GunHog** [comment]
Actually, this is currently the case! If you manage to steal the sword, you have a 70% to become a protector of the station, opposed to the original summoner:

    /obj/item/weapon/multisword/attack_self(mob/user)
	if(user.mind.special_role == "apprentice")
		user << "<span class='warning'>You know better than to touch your teacher's stuff.</span>"
		return
	if(cooldown < world.time)
		var/faction_check = 0
		for(var/F in faction)
			if(F in user.faction)
				faction_check = 1
				break
		if(faction_check == 0)
			faction = list("[user.real_name]")
			assigned = "[user.real_name]"
			user.faction = list("[user.real_name]")
			user << "You bind the sword to yourself. You can now use it to summon help."
			if(!usr.mind.special_role)
				if(prob(30))
					user << "<span class='warning'><B>With your new found power you could easily conquer the station!</B></span>"
					var/datum/objective/hijackclone/hijack_objective = new /datum/objective/hijackclone
					hijack_objective.owner = usr.mind
					usr.mind.objectives += hijack_objective
					hijack_objective.explanation_text = "Ensure only [usr.real_name] and their copies are on the shuttle!"
					usr << "<B>Objective #[1]</B>: [hijack_objective.explanation_text]"
					ticker.mode.traitors += usr.mind
					usr.mind.special_role = "[usr.real_name] Prime"
					evil = TRUE
				else
					user << "<span class='warning'><B>With your new found power you could easily defend the station!</B></span>"
					var/datum/objective/survive/new_objective = new /datum/objective/survive
					new_objective.owner = usr.mind
					new_objective.explanation_text = "Survive, and help defend the innocent from the mobs of multiverse clones."
					usr << "<B>Objective #[1]</B>: [new_objective.explanation_text]"
					usr.mind.objectives += new_objective
					ticker.mode.traitors += usr.mind
					usr.mind.special_role = "[usr.real_name] Prime"
					evil = FALSE

**Comment by Durkel** [comment]
Multiverse may easily be the most retarded item I've seen added yet. Spell book description should changed to "Causes a total clusterfuck." And that's putting it mildly.

**Comment by Cebasiz** [comment]
while technically you're a 'protector of the station' i think the net effect is to turn the entire thing into a fucking bloodbath; since the blade is a lethal weapon you can't really do anything but murder the fuck out of anyone who endangers the station, which then turns into a battle royale style bloodbath inevitably. 

the protectors of the station should probably be able to banish the blades and the summoned guys, and then once all of them are defeated the blade banishes all the protectors as well as itself down to all of the originals or something

that way the net effect is a decreasing bloodbath over time, rather than an inevitable escalation to factional bloodbath that nobody has any power to stop.

and hey, if the bad guys are robust they can still win when outnumbered.

**Comment by Aranclanos** [comment]
use the feedback forums for feedback
