### ISSUE TITLE
Nuke core deconstruction (and sprites) is horribly unintuitive and inconsistent.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10876]
Here's the actual construction steps:

1. Use a nuke screwdriver, visually identical but with a different description 

1.5. Use wirecutters to fumble around and get irradiated. (WHY???) This punishes you for using the sanest tool available, given that wirecutters can tidy wires while constructing mechs!
2. Use a CABLE COIL to TIDY the wires, done nowhere else in the game. (Consumes 15 cable pieces)
If you don't have enough, the cable coils only tell you you need more AFTER the wait period of trying to do it.
3. Use a PEN to draw CUTTING LINES(???)
4. Welder
5. Use a special nuke core container to steal the core, all while getting horribly irradiated.

The instructions sheet does NOT mention the whole clearing of cable coils, either. The description when you fumble around in it doesn't help, either.

That's 3 unusual tools, and the sprites for all this are absolute shit to boot. The nuke screwdriver (completely unecessary, put it on an access restriction) is visually identical, the nuke core container (why does it have an N on it???) and the nuke itself + its steps are all absolutely hideous.

0/10 objective see me after class.

**Comment by Xhuis** [comment]
>draw cutting lines
>use welder

10/10

**Comment by Aloraydrel** [comment]
Meme tier objective

**Comment by Cebasiz** [comment]
the other thing is that the vault is poorly defended at best, meaning you don't exactly have to be sneaky. the blast door protecting the vault is not different from another door and can be accessed with tools available everywhere in about five seconds, and by default the AI does not care about access, coupled with the fact that security rarely treads near arrivals means that nipping in to grab it is not exactly a feat.

it's a nice idea, but the vault isn't as difficult to enter as you'd expect, which means that it's not a hard objective, on top of the OP's issues.

**Comment by SconesC** [comment]
there's another vault objective and given how clunky this one is its kind of a "haha fuck you" objective

**Comment by Durkel** [comment]
I think this is the third issue report on this objective, It's a awful objective just remove the damn thing.

**Comment by NSSherlock** [comment]
Another issue is that the included instructions don't really emphasize (or even mention) the fact that you absolutely *need* rad protection to complete the process without dying. I managed to kill like half of the crew on Bagil the other night when I fell into crit while welding and died with the core exposed, which flooded the whole area around the vault with lethal levels of radiation (even through two layers of walls). People just walking by were dropping dead left and right with hardly any warning.

Reading the instructions, I expected the whole point of inserting the container into the hole rather than removing the core first was to *avoid* lethal exposure. The wiki mentions *possible* irradiation during the wire-cutting step, but the in-game instructions don't even allude to that.

I don't see an issue with the cutting lines, though. Makes sense since it's delicate equipment (and yes, you can do precision cuts with a welder). With the vault so easy to get into without being noticed, it makes some sense that the process of actually removing the core would be made complicated to compensate. If anything, it should be more complex or require harder-to-get tools. Or maybe just make it harder to breach the vault.

As for the screwdriver, it's not like we don't have other syndicate tools that are visually identical to ordinary tools. It does give a different description when examined.

It definitely needs work, but I like the idea.

**Comment by Robustin** [comment]
I vote to keep this horrific objective around long enough for me to expose the core and find a way to drag it around the station. 

Seriously who thought this was a good idea, it fails at every level. The damn objective comes with tools and instructions but doesn't include half the tools and the instructions neglect to mention super important life-or-death stuff.
