### ISSUE TITLE
I ded plz nerf: Multiverse Sword + Staff of Change Edition

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#10997]
Step 1: Get multiverse sword
Step 2: Get staff of change, magic skillsle, and 2 other "lel you cant kill me" spells
Step 3: Teleport to vacant office or some shit
Step 4: Summon a copy, staff of change that copy into an alien hunter, syndieborg, or slime
Step 5: Do this for a couple minutes
Step 6: Step out of vacant office with 3 syndieborgs and 2 alien hunters, continue pooping out additional hunters/borgs every 2 minutes. Laugh as your magic missile only stuns crew and not your stunproof murderarmy.

Simplest solution is to make SoC remove objectives so that the alien/slime/possibly syndieborg can just turn around and murder their master. Anyone who's seens this in action knows that its an auto-win unless someone manages to slip past the alien/syndieborg murdernet and suicide bomb the wizard before he can react. Iffier solution is giving % of clones a "kill your original" objective.

**Comment by Robustin** [comment]
I almost forgot Step 7: Remember that soulstone+artifice is still an artifact when shit like this and statue+animation exist.

**Comment by Jalleo** [comment]
@KorPhaeron @incoming5643 this is a edge from your two changes interacting with each other. @phil235 edgecase and fuck please.

**Comment by KorPhaeron** [comment]
Guess I gotta remove the memesword from wizard

**Comment by Robustin** [comment]
There are independent reasons for disliking memesword (As easy as it is to hate, at least you're never out of the round for long), but this particular issue can easily be solved by removing clone objectives once you become a non-human. This strategy will rapidly lose appeal when you SoC a clone into a hunter/syndieborg/borg/slime/etc. and then they turn around and dunk you.

**Comment by Lumipharon** [comment]
Just make multimeme sword admin only. It's so fucking broken.

**Comment by freerealestate** [comment]
People seemed to disregard the leftover objective after being transformed anyway. I saw people murdering multiverse clones on the shuttle (the objective didn't preclude them from doing that) and escaping on the shuttle themselves (despite the objective being to ensure that only multiverse clones arrive on the shuttle).

And there's no server obligation to complete your objectives. This one doesn't even show up on the end of round report, so once people realise that there'll be no incentive to complete it.

The wizard very easily could've been murdered by his creations that round. I think the only reason he wasn't is because it was such a new strategy that a lot of people didn't realise that they could or didn't have the balls to turn on him considering the size of his army. But once people realise the multiverse objective doesn't preclude them from killing the wizard, it'll become a much less viable strategy.

**Comment by Lumipharon** [comment]
it's not about being 'viable'.
Nothing in wizard has ever effected green text.

They have stock standard traitor objectives - a person with half a brain can get any objective done 60 seconds into the game.

Multicuck sword just turns the round into highlander with respawn on.
So what if the wiz dies? He'll just clone back in and keep murderboning.

**Comment by Robustin** [comment]
The round in question I believe every Wiz clone had "Defend Wizard and his clones and ensure they are the only ones on the shuttle" as objectives. There were plenty of bitter clones like me who would've loved to kill him but the wording was pretty clear that murdering the wizard was completely against our objective.

**Comment by KorPhaeron** [comment]
Syndiborg laws would erase/override traitor status though, wouldnt they?

**Comment by Jalleo** [comment]
Not sure datum antag would probably help solve this so much.

**Comment by Lumipharon** [comment]
if there are no syndicate operatives, the syndie borg effectively doesn't need to follow its laws.
It's traitor objectives will still be in effect though, so it should still be loyal to its maker.

Won't stop some chucklefucks from killing their maker though.

**Comment by Aranclanos** [comment]
as always, use the proper forums

**Comment by freerealestate** [comment]
>The round in question I believe every Wiz clone had "Defend Wizard and his
clones and ensure they are the only ones on the shuttle" as objectives

I'm 99% sure the objective only said "Ensure only clones of x escape
alive". Nothing about defending them.
