### ISSUE TITLE
C4 is inconsistent in it's ability to breach rwalls

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#11051]
Who knows why

**Comment by WJohn** [comment]
Might be related to #10564

**Comment by phil235** [comment]
Can't reproduce. Maybe you're talking about putting c4 on an APC (or other wall mounted stuff) and the rwall it is on isn't destroyed? That's because the APC is NOT on the wall but on the floor in front of it, it just appears to be on the wall via pixel offset shittery.

There is no bug with c4, it does its job properly. The issue is with wall mounted stuff with an offset.

**Comment by SconesC** [comment]
Hm, that might been what happened.

I saw it passingly and said "That's not right". It was on the Northern wall of telecomms, though, and I'm fairly sure that APC is on the inside. It was placed from maint.

**Comment by Dorsisdwarf** [comment]
This is not a bug. C4 only deletes the thing it's attatched to and the explosion has a dev range of 1/0, so it won't necessarily destroy things 1 tile away

**Comment by Dorsisdwarf** [comment]
closed for notabug. C4 only destroys the thing it's placed on 100% of the time.
