### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11273]
You can "duplicate" items visually (and actually functionally, in the case of armor?) by ctrl clicking them while you wear them, then clicking on the ground. This can then be done by multiple people and some fiddling to have multiple people wearing the same set of armor, and it will protect every single one of them equally (and also gives them the visual description, so there's no way to notice it).

It's not full duplication in that there's only one original armor, and it's fairly easy to "destroy" all the duplicates by doing some pickup/drop stuff. You also can't remove the duplicated items without picking up the original and dropping it.

Finally, it leads to some equipping issues where, until you drop it and your sprite refreshes, it tells you you can't equip that item even though you're note *technically* wearing it.

**Comment by Anonus** [comment]
THANKS, PULL CODE

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/blob/f124fe7a2585ecc2b53c3ca0f99c3d8ca8899351/code/modules/mob/mob.dm#L379

Pull code already checks for this.
It doesn't pull an object if that object isn't on the ground. Armor is put inside of you, so that last part of that if would trigger.

Control click calls this code. (unless something else is overriding control+click)

**Comment by WJohn** [comment]
This extends to not only armor, but guns, swords, entire backpacks, which leads to item teleportation.
