### ISSUE TITLE
Map merger doesn't work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11301]
What it says on the tin, it will say 6,000 something lines have been changed, and in commit it will say about 20,000 lines have been changed.

**Comment by optimumtact** [comment]
@RemieRichards 

It's probably PEBKAC

**Comment by RemieRichards** [comment]
@CorruptComputer said it worked, and he's the one who combined the tools.

**Comment by Jalleo** [comment]
Remie its the new dmm format

**Comment by CorruptComputer** [comment]
It's probably because it's the first conversion. Or it could be due to the map merge parser being shit. All I did was add a wrapper to it for the file selector. I never tested the diff of a remerged map. I assumed because it loaded It correctly that it was fine. Also @RemieRichards it could be due to the comment at the top of the file. I don't think that was ever expected to be there when it was originally written.

**Comment by WJohn** [comment]
This is how I did it on my end, if it's wrong:

1. Run prepare maps
2. Edit map
3. Save
4. Run map merger
5. Select 1 file for change, then select file 20 as that's box
6. 20,000 lines anyway ayyy

**Comment by RemieRichards** [comment]
@CorruptComputer if it's the comment, it's because the map merger is garbage, if byond can handle the comment, the map merger should really be able to too.

**Comment by CorruptComputer** [comment]
I didn't write map merger, nor do I plan on rewriting it. So if it is fucking up then I vote to just remove dmm2tgm before doing anything, unless you can write something that converts it back to the normal format and I can run that before map merge. Which would be a snowflakey bandaid fix, but it's the only thing I can think of.

**Comment by Firecage** [comment]
Well, might aswell post this here.

Tried to use the mapmerger yesterday, used it correctly. Most of the maps went through the mapmerger correctly, but when I tried to do it for the Box map, generic Z2, and Meta Z2...it gave errors when trying to mapmerge them and corrupted them.

**Comment by CorruptComputer** [comment]
Yeah after some testing it is because of map merges parser being shit and freaking out when everything isn't on the same line and because of that comment.

**Comment by WJohn** [comment]
Those are the maps I edited originally in #11130 
Did I do something wrong? I did the exact same process I listed above with that PR.

**Comment by CorruptComputer** [comment]
@WJohn It is map merges fault, I'll put up a PR to remove dmm2tgm until I can figure out something better.

**Comment by WJohn** [comment]
This is still broken.

**Comment by CorruptComputer** [comment]
It is working fine for me. Are your .backups in the tgm format? Because that is what causes this issue,

**Comment by CorruptComputer** [comment]
@WJohn I need to know if your backups are in the tgm format, because if so that is what causes the bug.

**Comment by WJohn** [comment]
How do I go about checking their format? Sorry, I'm terribly inexperienced with handling this stuff.

**Comment by CorruptComputer** [comment]
Does the file have newlines and tabs? You could also check of there is the header that says something along the lines of "// DO NOT REMOVE THIS IS TO PREVENT RECONVERSION". To fix just open the file in dream maker and save it without making any changes. This (if byond isn't dumb) put it back to normal dmm format with minimal line changes. But, your first commit doing this will have a lot of line changes because you are changing every line back to normal.

**Comment by CorruptComputer** [comment]
RIP

**Comment by duncathan** [comment]
I think this shouldn't have been closed; the commit that closed it was me pulling from upstream so if the original PR didn't fix it then I sure didn't

**Comment by CorruptComputer** [comment]
It's fine @duncathan the issue was user error.
