### ISSUE TITLE
Examining lizards shows their color as gray even if they're not gray

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#11333]
Title.

**Comment by duncathan** [comment]
Can you give a screenshot?

**Comment by WJohn** [comment]
This has been the case foreeeeeeeever. Happens with slime and plant people too.

**Comment by bgobandit** [comment]
all lizards are graytide, feature

**Comment by Core0verload** [comment]
BYOND Bug label.

**Comment by Incoming5643** [comment]
Anything that uses the color var to assign color does not appear colored in the little examine icon. This extends to hair on humans.

Additionally and really more critically, overlays don't appear on examine icons. This means you can always tell someone's race/gender no matter what they happen to be wearing, since the preview icon is always nude.

**Comment by RemieRichards** [comment]
We can probably fix this.
the base examine proc uses ```\icon[src]``` which is a byond built in (hence the failure being on byond's part here) but if we use one of those flatIcon helpers we have, we can create a ```/icon``` or ```/image``` and embed that in the text instead of ```src```

**Comment by Core0verload** [comment]
And cause a lag every time somebody examines.

**Comment by Incoming5643** [comment]
We could also just not show preview icons for mobs

**Comment by Dorsisdwarf** [comment]
We could also just not complain about special special lizards not being able to see the color of other lizards through hardsuits with their X-ray vision

**Comment by Dorsisdwarf** [comment]
Unresolved for unimportance
