### ISSUE TITLE
Horizontal HE pipes can't be installed on top of vertical regular pipes

### ISSUE THREAD

**Issue by Knigga** [tgstation/-tg-station#11398]
![bugreport](https://cloud.githubusercontent.com/assets/11097070/9483912/3ed1e69a-4b73-11e5-878c-e157d6491193.PNG)

If you lay a horizontal HE across a vertical pipe (top of picture), or vice versa, it states there is already a pipe at that location. However, the opposite (bottom of picture) can still be installed.

**Comment by duncathan** [comment]
@duncathan
Bizarre. I'll see what I did wrong.

**Comment by Actionb** [comment]
If it is of any help: same problem applies to scrubbers & vents.

**Comment by duncathan** [comment]
Can you be more specific; perhaps provide a picture?

**Comment by Actionb** [comment]
Top HE pipe cant be wrenched in, buttom one can.
![he](https://cloud.githubusercontent.com/assets/10028803/9534352/1f8df55c-4d18-11e5-8c78-d212e73e4668.JPG)
![he2](https://cloud.githubusercontent.com/assets/10028803/9534415/89e85672-4d18-11e5-91e5-cb99c5665e10.JPG)
Pretty much the same as in the OP. Though to my understanding scrubbers/vents never were full pipes since you could put bent pipes on the same tile.
