### ISSUE TITLE
Lizards lose sprite head-fluff with mask+helmet combo (temporarily)

### ISSUE THREAD

**Issue by cyfause** [tgstation/-tg-station#11691]
Gif describes the order in which this happens. Multiple different orders, however.
![fuck](https://cloud.githubusercontent.com/assets/13970003/9783594/65c9a880-5773-11e5-867f-8db14c88d8fd.gif)
I'm not entirely sure what might be happening code-wise, but it seems to only be with the mask that's doing it. Could be related to issue #10044 somehow, but I am doubtful.

**Comment by RemieRichards** [comment]
Most likely a missing update call, for species body parts.

**Comment by Incoming5643** [comment]
Masks and helmets check for a lot of the same flags, so I think the call is there but the code is just assuming some things it probably shouldn't

**Comment by Incoming5643** [comment]
Alright having looked into this there's a bit of a nasty mess when it comes to helmet updates. It's coded out completely different from any other slot and also is for some reason defined on the carbon level instead of at human. 

What's happening here is that at the time it was coded (which looks like it predates most other icon updates) it assumed spessmen would never have visible "ears" and thus didn't plan to update the sprite beyond the hair whenever a hat/helmet was put on taken off.
