### ISSUE TITLE
People turned into lizards without pre-existing preferences have no tails.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11697]
![](http://i.imgur.com/ZTh1R9u.png)

What it says on the tin. Their tail is labelled as "smooth".

**Comment by WJohn** [comment]
This may also come to happen if someone has their race changed by a green slime.

**Comment by Incoming5643** [comment]
This occurs to people who haven't even once looked (and/or saved) at their character preference window since the system was added. New accounts added after the system was added shouldn't be affected.

Affected players can just pull up to the preference screen and save without changing anything to fix the problem forever. Since there's only a finite number of these featureless lizard character saves it could also be intentionally kept as a bragging right. Though yeah they would have to be turned into a lizard in the middle of the round (not exactly common) to actually see that they were still featureless.

**Comment by WJohn** [comment]
Hm, then this is a player issue that's too minor to worry about.
