### ISSUE TITLE
Pun Pun now has a monkey number

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11736]
You hug Pun Pun (844) to make him feel better!

this relentless cloning of the pun pun must be fixed

**Comment by Incoming5643** [comment]
monkey numbers in general are pretty silly if you're not a ghost

**Comment by PKPenguin321** [comment]
"If you had to describe that monkey with a number from 1 to 1000, what would it be?"

**Comment by Aloraydrel** [comment]
Pun pun had a hard life in prison

**Comment by phil235** [comment]
Maybe Pun Pun's uniquename var got changed to 1 instead of 0 somehow?

**Comment by Nitrousoxide** [comment]
What if in stead of monkey numbers they got descriptions with enough variables so that the number of permutations is roughly 1000?  Stuff like, "Husky Brown Monkey" and "Haggard grey monkey".  It'll give the monkeys some character and still serve the purpose of making them unique for AI and ghost following purposes.

**Comment by feemjmeem** [comment]
@phil235 It looks like this is exactly what happened. I'm doin' a thing for it.
