### ISSUE TITLE
Becoming Traitorling despite preferences

### ISSUE THREAD

**Issue by ike709** [tgstation/-tg-station#12026]
Server revision compiled on: 2015-09-25
360f14689d085ed2aa2235c82ea47979f5e27c0c 

I just rolled Traitorling when I had every single special role disabled on Bagil. I don't... really know what other information I could provide...

**Comment by RemieRichards** [comment]
This happens when the gamemode is locked in to a specific mode (Due to all numbers for it, such as required enemies and what not, being correct) and the mode NEEDING to pick those antagonists.
While it will always pick people with prefs if they have them, it will pick from people who have the pref off if it can't find anyone, it happens all the time on basil because a lot of Basil don't even play antag.

**Comment by ike709** [comment]
It shouldn't force anyone to become antag if they have it disabled in their preferences. Most people have it disabled for a reason such as not playing SS13 in several months and totalling forgetting how everything works... Or never being changeling before.... Ever.... I'd rather it become Extended.
