### ISSUE TITLE
map issue: rd can walk into medbay through genetics and cmo can get into the superpower side of genetics.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#12040]
there not supposed to be able to do this technically.
could be fixed by requiring the middle door to have genetics, med-bay  and science accesses to open.

**Comment by PKPenguin321** [comment]
1. CMO needs access to the research area for patching genetic defects
2. are you certain RD can get into medical? iirc, he can't open the door from genetics research to genetics cloning.

**Comment by Supermichael777** [comment]
have done so before
and no cmo ever goes in there for any reason but to steal superpowers

**Comment by Lumipharon** [comment]
Unless RD gets it during low pop, RD cannot get into cloning.

**Comment by GunHog** [comment]
The CMO has always been able to get into the superpowers side.

**Comment by Marflowerose** [comment]
Not a bug. A head of department should and does have access to the places they're head of. CMO is head of medical therefore CMO has access to all medical facilities. 
If RD can get into Genetics, it's because Genetics is part of Research and Medical. It's a inconsistency but it's apparently an intended one. It's an inconsistency since Virology does exact same things: Medical and Research, but is not considered part of Research, despite being one of very few labs that do actual Plasma research.

**Comment by PKPenguin321** [comment]
add the "needs reproducing" tag for RD getting into meday (not just genetics research, but actual medbay)
it shouldn't be hard to test

**Comment by Shapsy** [comment]
It's fine for the CMO to have superpower access since the RD already watches over the entire science department and it's closer to medbay anyway (plus there are bottles of mutadone and mannitol over there which are useful for cloning), not to mention if a geneticist is being a shitler in medbay and the CMO wants to demote them, they shouldn't be able to just hide away in the science part of genetics 

If anything, it'd be nice if the RD had access to cloning, in order to do upgrades
