### ISSUE TITLE
THE RETURN OF THE ZOMBIE IAN: Dead corgis and meat spikes

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12115]
Putting a dead corgi on a meatspike results in the regular corgi sprite being on the spike, right side up, and you are able to attack it for a few hits before it bursts into hide and meat. 2SPOOKY.

@KorPhaeron

**Comment by Niknakflak** [comment]
GOD DAMNIT. WHY WOULD YOU REUSE THE NAME OF THE ISSUE I CAUSED

**Comment by KorPhaeron** [comment]
It takes the Xs of their eyes?

**Comment by KorPhaeron** [comment]
@tkdrg 

The corgi death sprite is just a corgi flipped 180 degrees with Xs on its eyes, and the meatspike flips it 180 when it dies (though it still has X eyes)

Short of a new dead corgi sprite this is unresolvable/not a bug/not something I'm going to fix (because it'd require an istype for corgis or something)

**Comment by tkdrg** [comment]
I don't even understand this report. I'll test it later I guess, not even sure if this is a bug or a feature request.

**Comment by bgobandit** [comment]
the point is, if you place a dead corgi on a meatspike the mob meatspike code kicks in, resulting in an alive-looking corgi sprite that you can attack and butcher

**Comment by phil235** [comment]
It doesn't really look alive when its eyes are x's. But yeah, it doesn't exactly look pretty.

**Comment by phil235** [comment]
@KorPhaeron

**Comment by optimumtact** [comment]
Duplicate of #15585 and that is more general than this one
