### ISSUE TITLE
In orion trail, the price for selling a crew member is higher than for buying a crew member, meaning you can chain buys and sells to get unlimited supplies

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#12368]
Buy crew member: 10/10
Sell crew member: 15/15

**Comment by Shapsy** [comment]
Slavery is good business

**Comment by Miauw62** [comment]
wasnt this fixed???

**Comment by CosmicScientist** [comment]
@Miauw62 #11722 "Fixes Infinite Resources in Orion Trail"
PR changed the sell price in this else if from 15 to 7:
https://github.com/Hamadryad-1/-tg-station/blob/f76e8e8af56b15ca4804e3752e81e761da0c9705/code/game/machinery/computer/arcade.dm#L640

This line wasn't changed in that PR:
https://github.com/Hamadryad-1/-tg-station/blob/f76e8e8af56b15ca4804e3752e81e761da0c9705/code/game/machinery/computer/arcade.dm#L903
eventdat += "<P ALIGN=Right><a href='byond://?src=\ref[src];sellcrew=1'>Sell crew for Fuel and Food (+15FU,+15FO)</a></P>"

Trying to find any 15 values led to that and that alone. I haven't tested it since #11722 but is it just *telling* you that it's worth 15 or is it actually *giving* you 15 for each crew member?

**Comment by astralenigma** [comment]
Well when I tested PR #12145 that was fixed, don't know if it's only there though.

**Comment by CosmicScientist** [comment]
@astralenigma the display line is correct in that one and I imagine it's only there since it's still going as a PR.

**Comment by MrStonedOne** [comment]
oh wait, it was.
