### ISSUE TITLE
Revenants randomly dying

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12386]
Honestly I'd be fine with the random dying if it gave you any kind of feedback as to why you died. As it is now, you're just left with your dick in the dirt as you die in front of the entire security team and get your ectoplasm spread around.

As an actual bug to give this substance, I couldn't EMP defibs for some reason, it just wasn't happening even as I was sitting on top of them.

**Comment by Steelpoint** [comment]
What happens is that you use your essence, or whatever it is called, to use your powers. Generally each power costs 10 to 15 essence but you only have 20 essence in total that recharges after you use your power.

The problem here is that if you use your power before you have enough essence, so using a 15 essence power when you only have 14 essence, then you die on the spot.

**Comment by Dorsisdwarf** [comment]
That's a shitty feature. Just make them unable to use any powers/move slowly/whatever while under 0 essence

**Comment by Anonus** [comment]
That is a bug, because it checks to make sure you have enough essence to cast the ability before you lose the essence.

**Comment by Steelpoint** [comment]
I'm pretty sure its a bug or just a lack of a feature/check/whatever to stop someone from killing themselves by accident.

It happened to me once before I realised why I was dying.

**Comment by Xhuis** [comment]
Please don't make assumptions about mechanics. You are incapable of using any abilities if you lack the essence to use them.

**Comment by Zilenan91** [comment]
Thing is, I've died before when I've had essence. I'm not stupid. Hell, I've seen revenants get upwards of 200 essence randomly dying after just floating around using nothing.

**Comment by Xhuis** [comment]
Revenants are very fragile or very powerful. @Zilenan91, your max health is the exact same as your essence, so you had 40 essence. The det revolver does 15 brute per shot (iirc) so that means you took 45 damage, which was enough to kill you anyway. Also, it is _only_ possible to die while revealed. I have a theory about why this random death thing is happening:

The revenant "dies" while hidden, but the death() doesn't call. This calls whenever the revenant is revealed, whereupon they instantly die. I have no idea how I can fix this.

**Comment by Anonus** [comment]
Your health is three times your essence, though, so that doesn't make any sense.
Also, becoming revealed doesn't call death() so that's not likely.

**Comment by Xhuis** [comment]
Since when is health 3 times your essence? Let me look at this...

**Comment by Zilenan91** [comment]
Det revolver also only does 10 brute, so it wasn't enough to kill me.

**Comment by Zilenan91** [comment]
Can someone add the bug tag? Even Xhuis says he doesn't understand why Revenants are dying.

**Comment by Anonus** [comment]
As far as I can tell, this appears to be fixed. I haven't seen any revenants die from non-attack causes in some time, at minimum.

**Comment by Zilenan91** [comment]
Yeah it's fixed.
