### ISSUE TITLE
Chem sprayer chems aren't actually applied to targets

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12382]
Spraying the chems doesn't actually seem to add them to the target's reageants. As such, all it seems to do is momentarily stun targets with no later ill effects.

**Comment by Iamgoofball** [comment]
@phil235 high priority

**Comment by Shadowlight213** [comment]
For comparison, I loaded a syringe with about 0.8 u of each chem in the bioterror chem sprayer mix and shot a full health human with it loaded into a syringe gun. Said human went to crit in about 15 seconds.

**Comment by Lumipharon** [comment]
spray does a touch reaction afaik, so while spraying someone with mutagen will still be able to (one off) mutate them horribly, something like zombie powder, that doesn't work off touch, will do nothing.

Or someone just changed it completely and it's fucked - I haven't used one for a while.

**Comment by phil235** [comment]
Here's what actually happens: You click a target X tiles away from you, the spray puff created calls reaction() on each turf and mob it crosses with a reaction volume of "the sprayer's tranfer amount setting" divided by X. Then in the reaction proc, since it's we're using a spray, it calculates how much of the mob's body is covered in more or less permeable clothes, finally for the reagents without a specific reaction_mob() proc the default action is to inject a fraction of the spray puff volume into the mob, depending on said permeability, unless the amount is too insignificant.

Example with the spray bottle set on 5u and filled with initropidril, aiming at a mob 3 tiles away with some clothes and a mask(permeability protection of 0.75). The mob is injected with 5*0.75/3=1.25u (which is barely above the current significance threshold of 1). If the mob had medical clothes, gloves and mask, he probably wouldn't have been injected with anything at all.

This is consistent and realistic. How can we expect 5units sprayed from 3 tiles away to have a big effect but splashing a 100u beaker not to do much?

Now let's see the problem with the chemsprayer: it has 5 different reagents, which means 1u of each in a 5u puff. No wonder nothing is injected into the mob. It also has a greater potential range which means more dilution when aiming far.

Now there's many things we can do to fix that:
- give the chem sprayer (and emagged medbiorg acid spray) a greater default transfer amount.
- Lower the significance threshold mentioned above to 0.1

**Comment by Lumipharon** [comment]
It was much better when these systems tranferred a fixed, full amount.
Arguably not realistic, until you remember that most of these poisons (or their rl equivalents) need barely any volume to kill a person - especially if it's in your blood stream.

Having higher transfer amount just means you run out really fast, which is shit for such a large investment.
