### ISSUE TITLE
Portable chem dispenser is broken

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#12444]
It has 'undefined units' of energy and no buttons to dispense chemicals.

**Comment by GunHog** [comment]
How closely are you standing to the machine? Was the machine powered? Were you stunned or otherwise incapacitated? Was there lag? What mob were you? Was the machine recently upgraded with T4 parts?

Please try to provide as many details as you can remember when making a bug report. Well explained reports that outline the situation helps us to get a fix to you faster. 

I recommend everyone posting issue reports adhere to this template: https://tgstation13.org/wiki/Reporting_Issues

**Comment by lollerderby** [comment]
Right next to it, it was powered, not incapacitated, no lag, was a normal human spawned on the thunderdome, machine was similarly spawned. I've heard other people had problems with it after constructing it, so I was checking it out.

**Comment by GunHog** [comment]
Try to provide additional reproduction steps. A quick check after building one and admin-spawning them showed no issues. Perhaps there is a NanoUI runtime somewhere?

**Comment by phil235** [comment]
Yep, Runtime it is:
runtime error: list index out of bounds
proc name: get ui data (/obj/machinery/chem_dispenser/get_ui_data)
  source file: Chemistry-Machinery.dm,104
  usr: Duke Of Science (/mob/living/carbon/human)
  src: the portable chem dispenser (/obj/machinery/chem_dispenser/constructable)
  usr.loc: the floor (184,121,1) (/turf/simulated/floor/plasteel)
  src.loc: the floor (183,121,1) (/turf/simulated/floor/plasteel)
  call stack:
the portable chem dispenser (/obj/machinery/chem_dispenser/constructable): get ui data(Duke Of Science (/mob/living/carbon/human))
NanoUI (/datum/subsystem/nano): push open or new ui(Duke Of Science (/mob/living/carbon/human), the portable chem dispenser (/obj/machinery/chem_dispenser/constructable), "main", null, "chem_dispenser.tmpl", "Chem Dispenser 5000", 490, 710, 0)
