### ISSUE TITLE
Syndicate c20r simple mobs drop nonspent ammo casings

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12507]
They should drop spent ammo casings because they just fired the bullet.

**Comment by Supermichael777** [comment]
whut

**Comment by Bawhoppen** [comment]
what is there to be confused about

**Comment by GunHog** [comment]
I believe what he is trying to say is that NPC Syndicate Agents (found on away missions or admin events) equipped with the c20r weapon drop ammo when they fire their weapons instead of used casings. One could simply pick up the unspent ammo and use it in their own weapon.

Please consider using the format here: https://tgstation13.org/wiki/Reporting_Issues
This will help you to provide provide higher quality bug reports.

**Comment by Bawhoppen** [comment]
Yes that is correct and what I meant. 

Also gunhog I post issue reports all the time, and maybe I didn't word this one well, but how would the form have made me word it any better?

**Comment by PKPenguin321** [comment]
it makes it very very clear what you're trying to say by restating it five thousand times
it's not necessary if you're half-decent at wording things, and i could understand this issue just fine so i think you're good
