### ISSUE TITLE
Xenobiologists can effectively change or ruin the gamemode.

### ISSUE THREAD

**Issue by dumpdavidson** [tgstation/-tg-station#12963]
Make 3-4 zombies, the gamemode is now zombies regardless of what it was before.
Make a ling, if the gamemode had lings in them they are now massively fucked over.
Make spiders and let them do their thing, the gamemode is now about spiders.

Suggested fix: Just get headslug/zombie/nursing spider out of the gold slime spawn code.

Xenobio has plenty of cool stuff left like golems and simple mobs slaved to them.

**Comment by Marflowerose** [comment]
Alternative title: Xenobiologists can effectively make the round more interesting.
Also, feedback forums.
There are many professions that can alter the round drastically: Virology, Genetics, RnD (BoH), Engineering (Goose is Loose/HALP NO POWER), Gun Cargonia, Toxins, Atmos, AI and probably something else. 
Xenobio produced people of course are a bit different but the issue is more validhunting and difficulty of seeing who is who. If there's 2 sapient slimes, one rogue and one helpful, both get lynched for the actions of the rogue one solely because the number identification is cumbersome.

**Comment by Dorsisdwarf** [comment]
Feedback forums.
