### ISSUE TITLE
Possible to Use Cloner to Get to Centcomm

### ISSUE THREAD

**Issue by Yolopanther12** [tgstation/-tg-station#12979]
If you build a cloner on the supply shuttle then upgrade it so you can autoprocess bodies, it's possible to get to Centcomm.

Just build the cloner on the shuttle, scan yourself with autoprocess on, send the shuttle away and kill yourself, then enjoy being at Centcomm.

Screenshots:
https://i.imgur.com/1jZDcy4.png
https://i.imgur.com/xiQmjKD.png
https://i.imgur.com/7iGMnjQ.png
https://i.imgur.com/zACw2iK.png
https://i.imgur.com/HLgFfWr.png (Gear change to open doors, but you could also hack them).

~~As an aside, I'm pretty sure this is fixable by just blacklisting */obj/machinery/clonepod* in */code/controllers/subsystem/shuttles/supply.dm* except I can't test it myself because every time I try to compile the code (for most anything I do actually), I just get a huge string of errors ( http://i.imgur.com/ypzH6iO.png ). If anyone could show me where I could go to help resolve this, I would **massively** appreciate it.~~

Adding the clonepod to the blacklist does work, suppose I'll put in a PR with the fix now.

**Comment by tkdrg** [comment]
The shuttle blacklist should be a lot larger really. I feel like I've seen this bug reported before else but I'm not sure and I can't find it right now. Anyway.

As for your compile errors, looks like buckled_mob is undefined somehow. Maybe double check if `code/game/objects/buckling.dm` is unticked for compilation, since that's where it is defined. And feel free to jump onto IRC if you need more help, there's usually helpful people around (including me sometimes). #coderbus @ irc.rizon.net

**Comment by Thunder12345** [comment]
Would it not be easier to just put some sort of barricade in place to block people from getting off the cargo shuttle even it they make it to CentComm?
