### ISSUE TITLE
Slime Processor: Doubled Output

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#13156]
At the start of the round, the slime processor in xenobio will produce 2 core for every slime put into it instead of just a singular 1, like its meant to.

**Comment by Bluespace** [comment]
It's supposed to output two due to relative slowness of xenobiology.

**Comment by Fox-McCloud** [comment]
Umm? How so? Slimes have 1 core and the processor isn't supposed to produce more than 1 core until it's upgraded.

It's also not that slow with the slime management console.

**Comment by bgobandit** [comment]
it's done this for ages

**Comment by LatD** [comment]
I've wondered this too and now that I've looked at the code and changelog, this is a bug. Goof added this in the big bluespace part update. In his changelog he says that part tier 3 should give 3 slime cores. So either this bug is kept to speed up xenobio or the bug is fixed.

Line 89 in processor.dm,
 for(var/i = 1, i <= C + processor.rating_amount, i++)
The <= is causing this bug. It should only be <

**Comment by Fox-McCloud** [comment]
It should be fixed, because you can set how many slime cores slimes start out with on the slimes, themselves; that would be the proper way of handling it.

**Comment by Iamgoofball** [comment]
i'll just call this a feature and roll with it

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

No, it shouldn't be done this way--a bug shouldn't be left in as a feature--especially one like this.

If the consensus is to increase the default amount of cores slimes have, then this: https://github.com/tgstation/-tg-station/blob/cdba29800d1016e628e52eb62026ed1978c105e0/code/modules/mob/living/simple_animal/slime/slime.dm#L43

should be changed, and not a bug left in place.

**Comment by LatD** [comment]
Since there is that proper variable for slime cores, I too agree that this bug should be fixed. This shouldn't be hidden in the processor file. I'd say this is also a consistency issue because currently the slimes are producing 2, 3, 4, 5 slime cores depending on part level. 
I can make a PR for this fix later if someone isn't doing it before me.
