### ISSUE TITLE
Runtime when calling mob/new_player/Login()

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#13162]
runtime error: Cannot modify null.active.
proc name: sync mind (/mob/proc/sync_mind)
  source file: mind.dm,1693
  usr: (src)
  src: Anthony Catleay (/mob/dead/observer)
  src.loc: the floor (41,145,1) (/turf/simulated/floor/plasteel/shuttle)
  call stack:
Anthony Catleay (/mob/dead/observer): sync mind()
Anthony Catleay (/mob/dead/observer): Login()
Anthony Catleay (/mob/dead/observer): Login()
MrMicrowave (/mob/new_player): Topic("src=\[mob_118];observe=1", /list (/list))
MrMicrowave (/client): Topic("src=\[mob_118];observe=1", /list (/list), MrMicrowave (/mob/new_player))

Caused by https://github.com/tgstation/-tg-station/pull/12869/files#diff-c3d8d983e2c6ebdd2156952858c6907bR2 @Menshin 
This calls mob/Login() which calls sync_mind() which then calls /mob/dead/observer/mind_initialize() which does nothing (and do not create a mind) then mind.active is called when mind is still null.

The runtime happens hundreds of times (each time someone logs in).

**Comment by Menshin** [comment]
I didn't caused this, whoever put _sync_mind()_ at the end of the _Login()_ proc did (merged from here https://github.com/tgstation/-tg-station/commit/8fce742d0a064d46203c3d2815b2ede311c65677).

The runtime would still be present even if i didn't tweaked the new_player _Login()_, since the culprit is choosing to observe at round start delete the new_player mind, yet _sync_mind()_ is still called on the newly created observer anyway.

Also, _sync_mind_ is still called for some /camera/mobs and  /livings _Logins()_ despite being called at root  level_ Login()_ now.

**Comment by bear1ake** [comment]
@phil235 can you close issue?
It fixed by @Menshin
