### ISSUE TITLE
Burning items render at a higher layer than the crit/damage overlay

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13204]
Want to see something in crit? Just set it on fire!

**Comment by PKPenguin321** [comment]
are you sure it's burning items, or items that were in a box which got destroyed by a burn
because there's this bug https://github.com/tgstation/-tg-station/issues/10511 where when items are dropped from a container by being destroyed they overlay over everything, and this is generally done by burning the container.

**Comment by Dorsisdwarf** [comment]
Someone set a load of paper on fire, then beat themselves to death with a toolbox, then get back to me, okay?

Bug testing can be fun.

**Comment by PKPenguin321** [comment]
Tested, paper was burning but was not seen through the crit overlay. I aghosted to confirm it was still burning. This is likely just #10511, but the items happened to be burning.

**Comment by phil235** [comment]
Yeah, can't reproduce this, unless I burn a box or backpack with stuff inside it.
