### ISSUE TITLE
 many of the windows on box are intermittently fucky

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13354]
Meaning you can't hit them/break them.

Same issue that happened to Wildwest

**Comment by KorPhaeron** [comment]
Okay I lied its only like half of them.

**Comment by MrStonedOne** [comment]
I need at least one example

I don't think dir = 5 causes that.

for wild west is was because the windows were border windows with the sprite of a full tile window, so they never updated with damage.... and they also had higher health.

**Comment by KorPhaeron** [comment]
The window on the left of medbay storage.

Also hop line windows.

**Comment by MrStonedOne** [comment]
Working fine for me...

They ARE reenforced windows, not normal windows, and take a bunch more hits before the first of the damage overlays trigger

**Comment by KorPhaeron** [comment]
You couldnt hit them at all, nevermind them taking damage. @oranges/@ausops/Dante/Invisty all experienced this off the top of my head.

**Comment by Firecage** [comment]
Last round I experienced it aswell with the R-windows at both R&D and Robotics aswell. Couldn't hit them.

**Comment by WJohn** [comment]
I'm seeing this on birdboat station, too.

**Comment by Firecage** [comment]
....Yes, yes it is. That is two maps so far, I wonder if any other maps are also affected.

**Comment by MrStonedOne** [comment]
it isn't dir 5

I can hit them just fine..

wild west's windows were not fixed by changing dir,

Please stop fucking spreading that around.

dir 5 means fucking nothing.

if you couldn't hit the window, it means byond thought you weren't in range of the window OR that you couldn't see the window...

I'm currently dealing with tracking down a bug with view() that is most likely byond side, this is most likely related.

So, @KorPhaeron seeing as how i've had to explain to multiple people (who heard it from you) that dir = 5 does not break windows, setting it to something else does not fix windows, how about you explain to me why the fuck you thought that was the case and why the fuck have you been spreading that around to other people.

**Comment by Strathcona** [comment]
I've seen this a few places on Disc as well.

**Comment by MrStonedOne** [comment]
Potentially related:

http://www.byond.com/forum/?post=1991401

**Comment by KorPhaeron** [comment]
@MrStoneOned

Because they shared that var in common with the wild west windows and seemed to have the same problem. Sorry.

**Comment by tkdrg** [comment]
dir = 5 just means it's a full tile window

**Comment by Anonus** [comment]
@SuperSayu You can't attack windows, probably due to one of your changes with the NODECONSTRUCT flag.

**Comment by SuperSayu** [comment]
oh

yeah okay I see what I did I apologize I will put a fix up
