### ISSUE TITLE
Items that fall off a burning victim cover the whole tile

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13436]
1. Take human
2. Set them on fire
3. Jumpsuit/back burns up
4. An epi pen is left sitting on their corpse
5. You can't click anything but the epipen, it covers the whole tile for some reason

@RemieRichards maybe? You did fire right

**Comment by Incoming5643** [comment]
It has something to do with UI objects and how they're set to cover the whole UI tile. There's at least one other issue that basically is this.

**Comment by RemieRichards** [comment]
@KorPhaeron ikky did item fires

**Comment by MrStonedOne** [comment]
@RemieRichards wouldn't it be better to make the screen objects for uis just relay the click to the item they are holding then keep messing with mouse occupancy

**Comment by KorPhaeron** [comment]
@Incoming5643 

Was pretty sure there was a similar issue but iirc it was light on details

**Comment by RemieRichards** [comment]
@MrStonedOne I wrote the logic for that out, and I'll explain why it was worse:
Byond produced some BIZARRE as fuck off-by-1 error that was so bizarre it was sometimes "off-by-0.5" attempting to correct this simply shifted the off by 1 to the OTHER side of the UI.
It was misrepresenting where the clicks took place, sometimes either 1 entire tile off to the side or half a tile off (the box UI is 1 drawing, not 7 or so boxes iirc, which is why you have to write click logic to convert coordinates, I wasn't going to rewrite the entire box drawing thing)

The logic I settled with, mouse opacity, was PERFECT, I set it when added to the box properly, and I removed it when removed from the box properly, as it's own closed off system it is literally perfect, but what started happening is things like burning items and explosions weren't removing things properly, so the blame lays squarely on THEIR shoulders.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Do you remember where your code for item removal is so I can try and make items burning off do it properly?

**Comment by RemieRichards** [comment]
@KorPhaeron that's the thing, it isn't my code to properly remove them, it's storage container procs that SHOULD have already been in use (and for normal usage like putting an item in by hand and removing it BY HAND, are perfect because of it)

**Comment by KorPhaeron** [comment]
@RemieRichards 

Would any problems come from making remove_from_storage an obj proc instead of a storage proc?

Because bombs need to handle both dumping out jumpsuit pockets as well as burning backpacks

**Comment by tkdrg** [comment]
there have been literally one million duplicates of this issue
i reported it 1 month ago and it was already a dupe
there's #11730
and there's also #11465
maybe somebody should just fix this

**Comment by RemieRichards** [comment]
@tkdrg Kor is literally doing that, but he closed his PR because he did it a stupid way.
he *SAID* he'd reopen it soon but that was an hour or so ago.

**Comment by KorPhaeron** [comment]
@RemieRichards 

I'm gonna do it when I'm a bit more clear headed painkillers and code (especially when mine is bad sober) dont mix
