### ISSUE TITLE
Assembly/item duping

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13527]
HELP: Shodansbreak/(JC Denton) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): I just duped an item, somehow. I was attachinga  remote signaller to a helmet I had in my bag, and it put it in my bag and dropped a copy ont he floor 

Reply PM from-Shodansbreak/(JC Denton): I had 2(?|F) helmets, 2 signallers, now I have 3 assemblies 

Reply PM from-Shodansbreak/(JC Denton): I attached it while it was in my bag, it attached, then made a second copy on the floor 

Reply PM from-Shodansbreak/(JC Denton): now when I attempt to weld the assemblies, it instantly welds them shut as well, all 3 of them seem bugged, or I'm just double clicking somehow

**Comment by MrStonedOne** [comment]
When ever somebody discusses "dupe" anything...

Please have them place both copy and original on the floor on different tiles.

We need to know if its an inventory display bug or an actual dupe, as most reported dupes are the formal.

**Comment by LatD** [comment]
I've had this bug too. It happens when you try to build a new securitron. If I remember correctly, just by combining the helmet and signaller, the item name became helmet/signaller/proxy sensor assembly. Proximity sensor would be the next step in making it but it didn't let me put the sensor in or to skip to the next phase, practically making it impossible to finish the securitron. When I disassembled the assembly, it got doubled. 

So if you want to try reproducing, just try building a securitron with the parts.

**Comment by tkdrg** [comment]
Just saw this in-game again. It really is a dupe, and a very clear one. You can easily make as many stun batons as you want. This needs a fix, and ASAP. The easiest way is probably just forcing people to tablecraft, though that does mean #12267 might get a bit annoying. We really should accept lists as keys in the tablecraft list.

**Comment by KorPhaeron** [comment]
>You can easily make as many stun batons as you want

Do they come with a battery?
