### ISSUE TITLE
Asteroid station disposal systems are broken

### ISSUE THREAD

**Issue by borntohonk** [tgstation/-tg-station#13578]
Medbay disposal by storage goes outside right where it starts, theatre disposals stops right outside in medbay.

Pretty much entire system on map is broken.

Solution: remove map from rotation.

**Comment by lordpidey** [comment]
Also: the stacking machine is just plain set up wrong in disposals.

**Comment by WJohn** [comment]
Both relatively easy fixes. You need only disposal yourself at the start, make a note of where missing pipes are when you pop out early, and fix repeatedly in the map maker.

As for stacking machines, well I guess that's trial and error because I have no idea how 1, 2, 4, 8 will translate correctly into the the machindir vars. More a trial and error thing you can do at the same time while cleaning the disposal system.
