### ISSUE TITLE
Upgraded freezers can be set to negative kelvin temperatures

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#13583]
This is bad because those should be unreachable

**Comment by duncathan** [comment]
I swear this was fixed a while ago

Negative temperature is bad kiddos

**Comment by Jordie0608** [comment]
The previous issue for reference #9991

**Comment by Zilenan91** [comment]
So this causes horrible horrible lag right

**Comment by PKPenguin321** [comment]
still just as hilarious as before

**Comment by Iamgoofball** [comment]
this has occured about 4 times now

and has been fixed 3 times before

what the FUCK do we keep doing to break it holy fuck

**Comment by Menshin** [comment]
> what the FUCK do we keep doing to break it holy fuck

This has probably been inadvertently reverted when merged into the```atmosrefactor2``` branch.

**Comment by LatD** [comment]
As a scientist who often upgrades the freezers in medbay, this has been possible since the summer. It was fixed for a while then but it's been possible since. On some stations I think this below 0K is the reason that causes medbay APC environment power consumption to get to insane numbers. I've used this below 0K thing weekly though, if not daily.

**Comment by duncathan** [comment]
Woops my bad
https://github.com/tgstation/-tg-station/commit/e63771c9f492ece94720962bff0070f2f642ab7a#diff-f311bb6b562bb332ae67898078c27d22L34
