### ISSUE TITLE
Reinforced floor breaks down into space when burned

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#13620]
This shouldn't happen, it should be burnproof

**Comment by MMMiracles** [comment]
For notice, the tempature inside the turbine before it burned was at 2.64154e+011k kelvin.

It usually caps around 6-7k kelvin before the fusion merge.

**Comment by as334** [comment]
Alright, so here's what info I've got. They've actually been broken for a while, but people rarely got up to the temperatures required for them to be in danger of melting so it went unreported. As it stands I guess fusion ignites easier than I thought inside plasma fires, so it can actually reach those higher temperatures needed to burn through. I suppose i'll make it so that it's harder for a fusion reaction to form in a fire. I'll probably make it so it requires a certain low level of impurities, that way it'll rarely ignite in an oxygen rich environment like a fire.

**Comment by WJohn** [comment]
Uh, I thought reinforced floors had a max heat capacity of 325,000K, while absolute max heat you could achieve was about 98,000K.

Did the max heat get increased?

**Comment by Knigga** [comment]
So I just tried a little plasmic fusion test in a previous round 
![image](https://cloud.githubusercontent.com/assets/11097070/11773126/400434ba-a1f3-11e5-9a84-679de5d21611.png)
The containment I had set up was so miniscule in comparison to what I probably should've used. The heat got to temperatures above 400000 K and not only melted atmos floors and walls, but broke out into the station with a heat strong enough to break windows from the vault to botany.

**Comment by duncathan** [comment]
KICKASS

@as334 yeah I'm thinking that impurity threshold might be prudent...
And maybe changing the scaling a bit

**Comment by Anonus** [comment]
This is excellent and I want a way to trigger this in normal plasmafires, if possibly not so easily.

**Comment by Supermichael777** [comment]
plasma once again horrifically dangerous. Now how to make ttv bombs go wacky with this?

**Comment by tkdrg** [comment]
Reinforced floor should never break down period, unless it is being wrenched
