### ISSUE TITLE
Deafness is stupid holy fuck

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13638]
enough said

**Comment by WJohn** [comment]
Don't clog up issue reports, please.

At least give some explanation or something.

**Comment by Bawhoppen** [comment]
Ask anyone, they would agree that its stupid, and is a real issue.
I know githubs for the code and all, but we should actually address this.

**Comment by duncathan** [comment]
@Bawhoppen stop making shitty reports. The only stupid thing here that is a real issue is your inability to make a proper issue report.

**Comment by Bawhoppen** [comment]
when was my last shitty report? besides that doesn't invalidate this

**Comment by duncathan** [comment]
Yes, it does invalidate this actually

**Comment by GamerGambit** [comment]
Notice that noone is saying you are wrong. The problem is that making an issue that just says "x is shit" and not providing any useful information is not an issue and is not going to get you anywhere.

Why is it shit? What could be done to make it better? Make your approach more formal and informative and people will take you seriously and they will be more than likely to accept your issue and point of view.

For the record I don't think there is anything wrong with blindness. It does what its supposed to do: it makes you blind. It sucks, yes, but so does getting spaced. It's part of the game.

**Comment by Bawhoppen** [comment]
I was referring to deafness, and ask any of the regulars anf they will agree with me. Its well known enough I don't need to explain it.
I understand issues are for bugs and other technical problems, not feedback, however, I wanted to bring this to attention, and maybe actually get something done about it.

**Comment by GamerGambit** [comment]
Whoops sorry. I'm still.pretty new to tg and SS13 in general but really your approach to this issue is quite poor.

If this is not the right place for this issue/ticket then perhaps make a thread on the forums about it and get some support and discussion going.

**Comment by duncathan** [comment]
>Its well known enough I don't need to explain it.

NO YOU'RE WRONG JESUS CHRIST
THIS IS A USELESS REPORT AND YOU'RE SHITTING UP MY NOTIFICATIONS WITH YOUR DUMBASSERY

go away

**Comment by duncathan** [comment]
I'm sorry for yelling but seriously stop
