### ISSUE TITLE
Tank not filling up with fusion exhaust

### ISSUE THREAD

**Issue by Knigga** [tgstation/-tg-station#13671]
Hooked up a fusion turbine, put some of the gas into a canister and tried to fill a tank with it, wouldn't work.
![image](https://cloud.githubusercontent.com/assets/11097070/11817006/fb49cedc-a320-11e5-8d31-7e28a1cc37b5.png)

**Comment by WJohn** [comment]
Friggin' fusion is so unbelievably broken holy shit.

**Comment by as334** [comment]
Wjohn this is the only active bug, and it's not technically fusion causing the bugs. Basically since there are certain points on the atmos scale that we never saw pre-fusion, a lot of bugs formed there. We're just revealing them, and then we can fix them/ Anyways i'll take a look.

**Comment by Cebasiz** [comment]
>25608800000

jesus fucking christ what is the pressure at the core of the sun in these units

NT canisters must be made out of fucking neutronium or some shit fuck

**Comment by duncathan** [comment]
Yeah there were only 2 issues with fusion itself, the rest was just atmos being pushed to its limit

**Comment by duncathan** [comment]
@Cebasiz the pressure at the center of the sun is about 1345 times that of this canister.

**Comment by Iamgoofball** [comment]
@duncathan we need to add crew objectives and give atmos "Store in an air canister the pressure of the sun"

**Comment by duncathan** [comment]
@iamgoofball this is why I keep you around

**Comment by as334** [comment]
Okay we found the issue here, basically atmos has a built in rounding factor(0.0001) in order to prevent tiny numbers causing issue with stuff, the issue is that the temperature here is so high that the actual number of moles that would be transfered is less than this factor. These sort of issues will likely come up later as well, so I believe we're going to be change the factor to around 0.0000001 barring any major issues.
