### ISSUE TITLE
Editing character appearance midround through the save file

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13862]
Certain things in a savefile are transferred to an existing character if changed during a round. Depending on the feature it might happen instantly, take an icon update, or require a cloning.

Much more obvious with mutant races, as the whole of the mutant bodyparts list is transferred back to the live character (aka lizards can change their color whenever they want).

**Comment by KorPhaeron** [comment]
Lizards are chameleons

**Comment by KorPhaeron** [comment]
@MrStonedOne

**Comment by Incoming5643** [comment]
The easy solution here is just to disallow editing of the active character slot during the round.

**Comment by GamerGambit** [comment]
Legit question: Why is it saved to the client anyway? The data shouldn't persist after each round so its easier to just keep it on the server. That way you don't have to worry about such tampering. Not to mention that players persist even if the close the game.

**Comment by MrStonedOne** [comment]
@GamerGambit 
Its not saved to the client.

This is saved to the server

We allow the player to edit it mid round.

It's only called a savefile because thats what byond calls files used for saving objects, but it's still server side.

@Incoming5643 NO
we need to make those things not use the char preference, they should be saved to mob or species or maybe a separate current character datum that is a copy of the old.

**Comment by Incoming5643** [comment]
That's why I said it was the easy solution, cause it's not the proper one :cop:
