### ISSUE TITLE
Odd issue with cryotubes and being able to talk

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#14137]
Reporting this for a player:

[REDACTED PRAYER]: Sorry, the cryo tubes were dinging and I was in water but could talk.

**Comment by LatD** [comment]
I've noticed someone talking and being awake there too. Seems like the cryo stops the sleep phase when they are fully healed even though the cryo is still on. So if they wait long enough they'll wake up and the cryo is still dinging. They just can't get out. Fix for this might be extending the sleep from full hp to the point when cryo is turned off.

**Comment by MrStonedOne** [comment]
They can get out, they hit resist.

**Comment by optimumtact** [comment]
What's wrong with them being able to talk?

**Comment by neersighted** [comment]
Yeah I don't see any bug here...

**Comment by LatD** [comment]
This might be intended but I can understand why people can see this being weird. The cryo tube is still on but the person inside can talk and be awake normally. 

I never understood why the manual mode was even added back there since it's toggleable even without upgrades. If this thing needs to be "fixed" I'd just remove the manual mode.

**Comment by neersighted** [comment]
Manual was added because people wanted to be able to use cryo as a trap like the old days/beaker somebody... I suppose I can just make it turn off when finished (and dinging).

**Comment by tkdrg** [comment]
neersighted fixed this
