### ISSUE TITLE
Hivebots don't die properly

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#14287]
They keep sparking and moving but without targeting anyone. Happens when you kill it normally with brute damage.

**Comment by Zilenan91** [comment]
Yeah I saw this a while ago, it kept seeming to hit itself over and over and over again even after someone sentienced it, causing it to spark and make attack animations constantly. I thought it was admin fuckery at the time because I kept asking why it was doing this and nobody was answering. That very same hivebot was also apparently invulnerable because people were emptying entire combat shotguns into it and it just wasn't dying.

**Comment by swankcookie** [comment]
The problem is, hostile.dm is made to apply to bots, and the spark code was just copypasted from cleanbot.dm.

**Comment by KorPhaeron** [comment]
runtime error: Cannot read /obj/effect/decal/cleanable/ro... (/obj/effect/decal/cleanable/robot_debris).len
proc name: death (/mob/living/simple_animal/death)
  source file: simple_animal.dm,400
  usr: Jada Singh (/mob/living/carbon/human)
  src: the hivebot (/mob/living/simple_animal/hostile/hivebot)
  usr.loc: the floor (112,143,1) (/turf/simulated/floor/plasteel)
  src.loc: the floor (112,142,1) (/turf/simulated/floor/plasteel)
  call stack:
the hivebot (/mob/living/simple_animal/hostile/hivebot): death(1)
the hivebot (/mob/living/simple_animal/hostile/hivebot): death(1)
the hivebot (/mob/living/simple_animal/hostile/hivebot): death(null)
the hivebot (/mob/living/simple_animal/hostile/hivebot): handle regular status updates()

**Comment by KorPhaeron** [comment]
@Jordie0608

**Comment by Bawhoppen** [comment]
tkdrg the reason that one didn't target anybody is because it was a blood gold slimed one
it did in fact target the slimes like intended, just didnt die

**Comment by tkdrg** [comment]
No I tested a normal one in the thunderdome. The reason it doesn't target anyone is because it's dead.it just didn't drop its remains and thus didn't disappear

**Comment by Bawhoppen** [comment]
ah
