### ISSUE TITLE
Neutral Artificers poop out cultist soulstones

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14407]
This is very important in continuing the mission in caves.dmm

**Comment by Buggy123** [comment]
I agree that they shouldn't poop out cultist soulstones, but how is it important to finishing caves.dmm?

It's absolutely possible to finish without making constructs, by the time you get to the shell you're halfway through that level anyway.

**Comment by KazeEspada** [comment]
No, as our oxygen tanks slowly peter out, as our healing supplies, run dry. The first guy drops and gets turned into the artificer, as we fight our way towards the gateway, the mime trips into lava, cant soulstone him as his life burns away. Then, of course, I drop as my tank goes dead.

**Comment by Zilenan91** [comment]
Miners and chaplains can use cultist soulstones afaik but yeah artificers should inherit the faction of those that shell them.

**Comment by Buggy123** [comment]
With a proper loadout and some caution Caves can be solo'd, so the soulstone isn't necessary. This should still be fixed, but it isn't necessary to complete the mission.

**Comment by KorPhaeron** [comment]
Maybe bring some supplies with you

**Comment by Buggy123** [comment]
There are more than a few ways to get more than enough/continous healing. Granted they are a little job-specific.

 Miner is a nice job for caves because you can get a hivelord implant for constant 1 health/tick healing, make stabilized cores which instantly heal all damage you've taken, and get a 80% melee resist hardsuit. Chemist can churn out brute patches like fucking candy, and loads of other healing chems; A robust chemist can passively heal faster than any other job, faster than even a changeling with fleshmend. Virologists can make healing viruses that heal 3-6 damage a tick for your entire life. Roboticists can make medibots. Scientists can also make medibots.  The list goes on...

But yeah this is still a issue that needs to be fixed, just not specifically for caves.dmm.
