### ISSUE TITLE
Traitor Virus Box item is empty

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/-tg-station#14510]
Current basil
1/7/2016

I tried spawning the 20tc Virus Box, but upon opening it you find that it is empty and is a complete waste of tc.

**Comment by swankcookie** [comment]
The Virus Kit?

**Comment by KorPhaeron** [comment]
It's for the best, trust me

**Comment by swankcookie** [comment]
lol

**Comment by Anonmare** [comment]
Can you at least keep it out of surplus crates til it's fixed? Smh tbh fam

**Comment by tkdrg** [comment]
Known bug, PR up for it being fixed already I believe

**Comment by TheWiznard** [comment]
if #14441 actually fixes this then go ahead and close this or whatever, from my limited understanding of clicking around, it [14441] (lol) appears to only rename the box to "syndie box"

**Comment by Jordie0608** [comment]
It does

**Comment by SouDescolado** [comment]
@TheWiznard although the issue is closed, let me tell you what is happening at the code on my PR.
Now, when you get the tuberculosis kit, the game gives you a /syndie_box/
The code to fill it, currently, is named /virus_box/. So when you buy it, the code does nothing, because you bought a Syndie_box, not a virus_box.

When the PR gets merged, it will fix it.
