### ISSUE TITLE
Speech bubbles appear shifted far to the right when you slip.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14664]
What it says on the tin. Talk + slip and your speech bubble gets shifted way to the right.

@ChangelingRain

**Comment by ChangelingRain** [comment]
Ah, damn. Probably the best way to fix this would be making speechbubbles not rotate with the mob, because it's otherwise not practical to fix without losing some of the design on at least one bubble type.

Unfortunately, I'm not sure how to make the bubbles not rotate but someone else probably knows.

**Comment by RemieRichards** [comment]
@ChangelingRain appearance_flags & IGNORE_ROTATION (I forget the real flag name) on the /image.
