### ISSUE TITLE
You can't attach the torso of a borg to the chassis

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#14804]
Even after you put wires and a battery into the torso part of the borg during construction, trying to attach it to the borg chassis just gives a message saying that "You need to attach wires to it first!"

![](http://puu.sh/mGnWb/1885d23988.png)

Seems pretty high priority since you can't build borgs anymore

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/b2629a56e2a7b59fb953caca6341b55b2b039e15/code/game/objects/items/robot/robot_parts.dm#L315 and https://github.com/tgstation/-tg-station/blob/b2629a56e2a7b59fb953caca6341b55b2b039e15/code/game/objects/items/robot/robot_parts.dm#L320 should `wired` instead of `wires`. 
@neersighted forgot to switch these two in #14761.
