### ISSUE TITLE
Efficiency Toxins is is intentionally designed to be unsecure and easy to hack

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#15123]
Toxins Storage is supposed to be a secure room, surrounded by rwalls, accessible only through Sci. 

On Efficiency it's got maint access. Fucking Maint access. It's right next to fucking Medbay, so it's a nobrainer to just hack the door, grab any fucking cannister, and just go into medbay and dump plasma. Cyro has maint access right near Toxins. Chem is just a welding tool away from getting flooded from Toxins

Or science. In WJ's words:
Admin PM from-WJohnston: I also designed R&D to not have all that many fire doors for the entire corridor, and also firedoors on the one spot that leads to space so the first stays in.

Toxins Storage is historically one of the least visited rooms in sci, bar like the Server room, so nobody ever knows until something is already burning. Having it unsecure as shit basically guarantees either someone will have to take measures every round  or fucking stand guard or move all the plasma or something (read: metagaming) to prevent it from being hacked 5 minutes in, or else anyone with maint access (read: assistants) can just dump all the from in Toxins Storage every single round because it's so fucking easy to get into.

I thought that maps were supposed to be designed with balance, not memes???

**Comment by xxalpha** [comment]
Forums
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=5740

**Comment by WJohn** [comment]
Why would you make an issue report on something I specifically stated was intentional, and then also avoid putting this in the feedback forum?

Also maps can absolutely have specific design goals or ideas put into them. The holodeck being extremely public was put there specifically so plasma fires and holocarp are actually dangerous. The centralized R&D/chemistry/robotics/mining thing is specifically to minimize travel times and is the whole gimmick of efficiency. Eff 1 and 2 had R&D behind medbay, because I wanted to mimic ye olde T medbay of box 2010. Eff 3 has the library that mimics that old design, too, because I loved the public D&D sessions.
