### ISSUE TITLE
Mech hit RNG

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#15128]
Mechs are kind of shit as an option for OPs in particular and the main reason for this is their inability to get around.

Fire doors completely stop them in their tracks, and it can literally take 40 hits per table or wall to break it when a fucking wispy hivelord can knock a table out in one hit. Mechs should at least be able to smash tables and windows in one hit and ideally walls too. I've spent multiple mech ops rounds stuck in one patch of hallway grinding at a table that just won't break because I'm unlucky and the odds are awful.

Please fix. Tables, windows and walls should really be smashable in one hit by the big mechs

**Comment by Lumipharon** [comment]
Or like, get your chucklefuck team mates to be useful and support you with welders, emags and crowbars.

**Comment by Stickymayhem** [comment]
A big stompy mech should be the thing that gets your team into place. Not the other way around

**Comment by Lumipharon** [comment]
That's the only thing that stops shit like a mauler (or even a kitted out durand) from being unreasonably strong.

Without an ion rifle it's rediculously hard to take down a mauler - it's only weakness is that its mobility can be severely limited (mainy due to AI's being the cockblocking shits they are) without other team members helping it, or the pilot having to get out and open shit.

Having to require LESS team work when you've already invested most of your tc's into one OP's fucktoy is pretty meh, really.

**Comment by CPTANT** [comment]
maulers are slow as fuck already, they should be something you run away from, not something that is blocked by a couple of tables.
