### ISSUE TITLE
Can't reload bulldog shotguns

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15214]
You can only load them back with whatever mag they come with, so if you waste all your ammo and try to load a different magazine on it, it simply won't work

**Comment by Shapsy** [comment]
Full desc: for some reason, you can load up the Bulldog shotgun with taser slug magazines, but trying to put in the magazines for slugs, buckshot, bioterror and dragons breath ammunition provides no feedback and doesn't do anything. I'd imagine it has something to do with the magazines themselves, since you can just empty out the taser magazine and load it with whatever else and it'll work fine

**Comment by tkdrg** [comment]
@MMMiracles

**Comment by MMMiracles** [comment]
I did a dumb and made it only accept the taser magazines as a valid magazine. 

Secret stealth nerfs. Will fix when home.
