### ISSUE TITLE
Swarmers being born into nullspace

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#15337]
I don't really have any details at this point but for some reason a bunch of swarmer bodies were being placed in nullspace, which then offered control to players who then ALSO became stuck in nullspace.

**Comment by lzimann** [comment]
I believe it's something wrong with you being able to click the shell(by the ghost hud) AFTER it was taken, so the shell get deleted and you spawn in nullspace.

**Comment by Incoming5643** [comment]
I had it happen multiple times by clicking the enter link in the chatbox.

**Comment by lzimann** [comment]
Something wrong [here](https://github.com/tgstation/-tg-station/blob/2a9444a891c3684042c5bf2e1b4f77898b10b88b/code/game/gamemodes/miniantags/bot_swarm/swarmer.dm#L22) I would assume

**Comment by WereChipmunk** [comment]
Hello! Just chiming in on what I noticed since I just had it in a round. It seems like of everyone that says "Yes" to become a swarmer, only 1 person gets it and the losers get sent to nullspace instead of being told the shell was taken. I tested by  waiting until I was sure a shell was taken and got sent to nullspace afterwards

**Comment by tkdrg** [comment]
possibly related to @MrStonedOne with his change to queues. does the queue to be queued return true for qdeleted()?
