### ISSUE TITLE
Deads can use HUD to unbuckle 

### ISSUE THREAD

**Issue by matillo** [tgstation/-tg-station#15862]
### What is the problem?
As a ghost in my dead body, the new HUD showing me on the stretcher cart lets me unbuckle myself when being dragged around.
### Why is it a problem, or what should have happened?
Should be checks if user is alive before letting the HUD disable that.
### How can the problem be reproduced?
I'm not sure which objects you can get out of, probably those without a struggle, but at very least the medical stretcher lets you drop off when buckled as a corpse.

**Comment by Shadowlight213** [comment]
Resist button works as well. My body was buckled into a chair and pressing resist unbuckle me.

**Comment by CosmicScientist** [comment]
I'm not sure where I read it from, it might have been a tip of the round but apparently you can also resist out of lockers when dead because you "lean with your dead weight" (I assume the unlocked kind). It might be something to consider making a decision on as well when also fixing this because it'll likely affect that too if it's still in.
