### ISSUE TITLE
Handcuff and timestop bug

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15978]
### What is the problem?

HELP: redacted (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Found a bug. If you're handcuffed and get dragged into a TImestop, then you and the person dragging you can never move again, and you can't resist out of the cuffs. 

### Why is it a problem, or what should have happened?

Obvious exploit potential.

### How can the problem be reproduced?

By following the above procedure.

Other useful info: Summon magic was occurring at the time

**Comment by ChangelingRain** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Sounds like the sort of edge case that I will look at in a year during the next freeze

**Comment by phil235** [comment]
I think something similar happened today, timestop occured with player at the center, players quickly tries to move away but is still caught in it, then the player can never move again even after the effect disappears. Calling update_canmove() fixed the issue.

**Comment by phil235** [comment]
Found the culprit:https://github.com/tgstation/-tg-station/blob/e3d5a240a9f4626689583a4cb16e2e536bd48552/code/modules/research/xenobiology/xenobiology.dm#L569
Manually setting stunned to a value instead of using the Stun procs (AdjustStunned(), Stun(), SetStunned() )

Also https://github.com/tgstation/-tg-station/blob/e3d5a240a9f4626689583a4cb16e2e536bd48552/code/modules/research/xenobiology/xenobiology.dm#L539  Should be Stun(10)
