### ISSUE TITLE
Alchohol Screen Shaking and trippiness applies for less then a tick and then wears off repeatedly.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16034]
Remember that bug where reagents that caused sleep and stun would cause the victim to be put to sleep every since tick and then wake back up again?

Yeah, alchohol does that with screen shaking and pan-galatic gargle blasters cause trippy to do it too.

Also, Alchohol based dizzyness isn't working either.

**Comment by phil235** [comment]
the trippy bug is due to a typo of mine: https://github.com/tgstation/-tg-station/blob/e43b3a891de6b4c62599b497b80634ed265205a9/code/modules/mob/living/living.dm#L1110

The dizziness effect work as intended afaik, it hasn't been changed in a long time.
Can't reproduce alcohol dizziness not working, it works fine with vodka.
