### ISSUE TITLE
Security starts with excess equipment

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#16054]
### What is the problem?
Security officers and the head of security start with excess equipment on their person including a stun baton, a flash and maybe a spare set of handcuffs. I haven't had the recent experience with the Warden to say they're affected or not.
### Why is it a problem, or what should have happened?
When you go to pick up a security belt from a security locker like a good little redshirt, you realise it's fully stocked thanks to #15709 moving the locker's contents into it and bringing light to the extra gear. So you now have inventory management to deal with.
### How can the problem be reproduced?
Join a round as any member of security besides the detective.

I'm going to state the obvious solutions and drawbacks:
- Remove the gear bloat from officers, this causes late joining officers to only come with a taser and may find themselves stuffed if the station is hostile, that might not be a bad thing but it would discourage joining late as an officer.
- Remove the gear bloat from the security belts, this causes new recruits (conversion round implant spam and job changing) or replacement of lost gear a problem as there isn't necessarily any available supply unless cargo can order to replace _every item_.
- Remove the gear bloat from the security belts and add additional gear to the sec vendor, I'm not sure if it has the right kit currently which might make the job easier if it does.

**Comment by CosmicScientist** [comment]
Oh and another option could be giving them security belts on joining but that gives them no set up time and would probably cause late joining balance issues too.

**Comment by Supermichael777** [comment]
Sec officers spawn with all the equipment _technically_ necessary to do their jobs/not die on the way to the arrivals locker. Their locker gear serves as spares and special use utility items (pepper spray is a non-harmful stun that isn't cancer to use due to needing pixel precision, zip-cuffs are a safer way to handle prisoners because you don't need to get the cuffs of the floor, The flashlight attaches to 2 of your must have bits of gear and REDUCES cancerous inventory clutter, flash-bang is a one-shot aoe stun with terms and conditions).  Yeah they have a lot of gear but they aren't nearly as overloaded as some others round-start.  Sec is one of the most carefully balanced segments of the game. Each piece of gear and its interactions have been bug-tested and balanced on the assumption that every officer gets it. (Hos has a bit to much but mostly its juggling it into the locker)

Frankly I don't see where your coming from. Your belt holds all the gear you need, with a spare cuffs and flash(or flash-bang for people who love not dyeing) in your pockets, flashlights on your hat and on your gun, and a baton in your pack as well as on your belt. any other spares go in the box and you have 17 weight of item space in your pack. If anything your a loot pinata more than an overburdened mule. 

All the gear you need spares of is in the armory or the sec vendor (only thing missing is pepper spray but pepper spray is only really useful on ungeared idiots and prisoners).

**Comment by CosmicScientist** [comment]
@Supermichael777 
Spawn with a stun baton, a taser, a pair of handcuffs and a flash:
![locker inventory](https://cloud.githubusercontent.com/assets/11809482/13724885/3570f7de-e88b-11e5-8ce0-967e002a7772.png)

Secbelt contains these three items already:
![start inventory](https://cloud.githubusercontent.com/assets/11809482/13724886/384add58-e88b-11e5-82bd-ba409473349a.png)

Hooray for dropping spare items so you have space for other things every round!

**Comment by CosmicScientist** [comment]
Returning the spares to the locker where they used to be might be good whilst leaving the flash bang and the pepper spray inside.

**Comment by KorPhaeron** [comment]
@Malkevin

**Comment by Malkevin** [comment]
Sorry but are you retarded?

It's the exact level of gear they've had for years, with the addition of an extra baton, which they've also had for a year.

Flashes burn out
Cuffs get lost
The baton is the only extra weapon, I don't know if disarms got buffed  but I see a hell of a lot more batons getting stolen lately so I would disagree with their removal - especially as taser stuns got gimped last year to the point where you NEED to hit the scumbag with a baton to have enough time to cuff them, so sec officers NEED to have a baton to replace the one that will inevitably get disarm stolen.

Sorry but this is a complete non issue and I feel dumber having read it.

**Comment by duncathan** [comment]
Feedback forum then
