### ISSUE TITLE
Shuttle walls that auto-smooth have black turfs at diagonal corners

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#16059]
If you use the diagonal version of the smooth shuttle walls, the underlay that's suppose to apply for the floor icon doesn't actually work and ends up with a corner piece sitting on a black tile.

**Comment by Supermichael777** [comment]
probably because the wall doesn't record the turf under it/doesn't use that information while the hard-coded corners did/were sprited to have the underlying turf

Probably has somthing to do with walls deleting the floor under them because otherwise air would pass through them(because atmos is simulated on turfs in tiles and having multiple active turfs on a tile would cause byond to have a seizure or something so turfs delete what their built on and just have a base turf var hard-coded. windows, laticis, catwalks, and grills are structures which dont do atmos and airlocks are a machine.)

**Comment by xxalpha** [comment]
Way ahead of you.
