### ISSUE TITLE
Uploading a template midround breaks lighting in that area

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16060]
I loaded a template (prisoner_crash.dmm) in lavaland (which is dark). No attempt to introduce lights (such as spawning light emitters, or using flashlights) could bring light to that area.

@RemieRichards I guess

**Comment by RemieRichards** [comment]
Probably something to do with the lightning system not noticing?
@AnturK may have undone/done something when he made the datums and all the preloading of templates.

**Comment by AnturK** [comment]
It was always like this due to map loader not using ChangeTurf in lieu of new, i didn't change it yet because ChangeTurf has the inbuilt assumption that it should equalize turf's air with neighbours immediately. Which is kinda annoying for templates loaded in airless areas. Probably needs a argument in ChangeTurf added and such.

**Comment by duncathan** [comment]
I'll handle this with my turf stuff

**Comment by octareenroon91** [comment]
Template loading still causes darkness.

**Comment by duncathan** [comment]
this was fixed
