### ISSUE TITLE
Foam dart duplication bug?

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16084]
HELP: Pecce/(Heimilich) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): alright, so... http://puu.sh/nEOqA/2ac724732f.png on the right side of the cleanbot(?|F) was an assistant in a janicart, I shot at him with foam force crossbow and the darts seemed to duplicate. the darts you can see on the reinforced table are the result of this awesome bug, but I'm just letting you guys know about this in case you guys wanna do something about it.

**Comment by phil235** [comment]
Yep, it duplicates the darts because it's actually creating a new dart and deleting the projectile when it hit something. The issue here is that the projectiles hits both the janicart and the mob at once (we already had an issue with it).

I also found another issue: if you fire the foam crossbow on a mob that's on your tile (or yourself by selecting your mouth) it won't drop any dart but your crossbow will have used one projectile.

**Comment by phil235** [comment]
I think the way to fix it would be to have bullet/reusable not create a new dart in its bullet_act but in its Destroy().
