### ISSUE TITLE
Using a package wrapper on an item via telekinesis warps the item to your hand

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16116]
1. Grab a package wrapper with telekinesis
2. Stand somewhere far away
3. Wrap an object with the telekinetically-grabbed package wrapper
4. Notice that the wrapped parcel appears in your other hand (or on the floor beneath you if your hands are full), passing through any walls or obstacles

**Comment by Supermichael777** [comment]
speceemahn magic knows no limits.
the put in hand for the package wasn't safety checked for this because you were never supposed to wrap anything out of reach. a simple if check on the put in hand part of its attack should do it(but i don't know the actual var for checking ajacency. range() could probably do it).
