### ISSUE TITLE
Borgs don't give death messages

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16195]
Default borg got lasered, no death message

**Comment by phil235** [comment]
For some silly reason, cyborg use emote("deathgasp") instead of a visible_message() in their death proc. Youcan't emote while unconscious, so no wonder no messageis shown.
https://github.com/tgstation/-tg-station/blob/2a9444a891c3684042c5bf2e1b4f77898b10b88b/code/modules/mob/living/silicon/robot/death.dm#L25
