### ISSUE TITLE
sleeping carp deflect should probably be boldtexted

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#16353]
Deflecting projectiles generates a boldtext warning to the user but only a small line of red text for others.
Should make it bold to make it more noticable in the heat of combat :^)
totally not idedplsnerf

**Comment by coiax** [comment]
Bold text warnings though are only for aggressive actions directed at you, the observer. Flagging sleeping carp deflections in the same way is not really a good precedent.

**Comment by Lumipharon** [comment]
Having no visual feedback for a person simply not being effected by ANY projectiles is far, far worse.

We had some lowpop murderboner kill 95% of the crew yesterday, and like 5 different people took turns trying to gun him down for extended periods of time, none of whom seemed to notice that he had projectile reflect.

Honestly there really needs to be actual visual feedback (sparks flying or whatever), since if you're right in a fight you tend to not stare at the chat window.

**Comment by coiax** [comment]
That's not a bad idea. Maybe some sort of... ninja gleam? With sound effect?

**Comment by Saegrimr** [comment]
Pay more attention, nerds.

**Comment by ChangelingRain** [comment]
Bold text is used for a lot of things, it's only the larger FONT that's used for things directed at you.
