### ISSUE TITLE
Pulsing syndicate bomb wires has no cooldown.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#16774]
I think we can all extrapolate why this is a problem

**Comment by coiax** [comment]
No?

**Comment by PKPenguin321** [comment]
>add time wire
>pulse 40 gorillion times
>bomb never ever explodes

**Comment by coiax** [comment]
You can pulse the time wire more than once? I think that's the problem right there.

**Comment by bgobandit** [comment]
Uh no that was not my concern, my concern was

>find bomb speed wire
>pulse 
>bypass the time limit

**Comment by drynwyn** [comment]
You can already do that by finding the Boom wire, though.

**Comment by Lumipharon** [comment]
Yeah. Findin the boom wire involves zero risk, and lets remotely detonate regardless of timer - spamming the timer down is literally pointless.

**Comment by bgobandit** [comment]
the risk of finding the boom wire is u ded

**Comment by PKPenguin321** [comment]
no, because you can pulse the wires before setting the bomb and nothing happens iirc

**Comment by Lumipharon** [comment]
>no, because you can pulse the wires before setting the bomb and nothing happens iirc

How do people still not know this?

**Comment by LatD** [comment]
So my PR isn't related to this then. But this doesn't seem to be a bug or an exploit. Only thing that can happen because of that no cooldown is that if you manage to spam the advance timer wire a lot it'll just go to 0 or negative and explode. 
The worse thing in no pulse cooldown was that the delay wire basically worked as a deactivation wire and this is getting fixed in my PR.
