### ISSUE TITLE
Random items lose their icon states when picked up

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#17242]
Guns are missing charges

HUDs, krava maga gloves are both invisible. They become visible again when dropped.

**Comment by Lumbermancer** [comment]
The sec hud sprite doesn't show at all in inventory. The UI buttons (resist throw) are missing.

**Comment by lzimann** [comment]
The sec belt updates its icon if you remove something from it.

**Comment by MrPerson** [comment]
Probably layer related, my fault

**Comment by phil235** [comment]
Caused by #17086

I think what's happening is that var/plane, unlike var/layer, is not automatically shared between an object and its overlays. This means the gun has plane = 20 and is then visible above the obj/screen/inventory/hand that has plane = 19 , but the gun's overlay still have the default plane = 0 or something, so they are shown behind the screen.

**Comment by phil235** [comment]
Fixed by #17256which reverted the plane var PR
