### ISSUE TITLE
Using a screwdriver on the Circuit Imprinter makes the Protolathe not wor

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#17538]
I can still access the Circuit Imprinter menu however despite it being open. Resyncing the devices doesn't let me use the protolathe unless I reset R&D after opening the panels on every device while the monitor is unscrewed.

EDIT: The same thing happens with the Analyzer. I can't use the Analyzer despite it being synced to the RD computer howerver. Unscrewing doesn't show either the Imprinter of Analyzer unsyncing

**Comment by GunHog** [comment]
Manually disconnect the machines before re-connecting them in the console.

**Comment by LatD** [comment]
I found the bug in the code. Is this urgent or should I just put it in my R&D PR?

**Comment by GunHog** [comment]
Not critical, simply do a manual disconnect at the R&D console before reconnecting them.

**Comment by LatD** [comment]
It's not that old bug, it's a new bug which always disconnects protolathe when either DA or circuit imprinter is opened with screwdriver. DA and imprinter cannot get disconnected with screwdriver.

**Comment by LatD** [comment]
Hm, I'm not sure how to fix this actually. @phil235 
This bug came with the attackby refactor thing. R&D machines got their unique attackby's removed and stored to rdmachines.dm. But the old ones used linked_console.linked_lathe = null for protolathe, linked_console.linked_imprinter = null for imprinter and linked_console.linked_destroy = null for DA. Now the proc does only the protolathe thing causing protolathe to get disconnected when any of the 3 machines is opened with a screwdriver. It needs part of its snowflakey thing back with ifs or something, you can probably do this better.

https://github.com/tgstation/-tg-station/blob/b146131a342d32a0bdac80d9130ae28ca3299c9d/code/modules/research/rdmachines.dm#L56
