### ISSUE TITLE
We could use a formal decision if those little emoticons under PRs mean anything or not

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#17696]
The logical conclusion of #16031

I've seen people asking others to :-1: pulls they otherwise wouldn't have touched will the expectation of making pulls look more controversial/hated than they actually are.

At the same time sometimes people will just :+1: / :-1: a pull instead of saying why something is a good/bad idea. This marginalizes them and gives more power to the people who are willing to write short novels about why they're right or someone else is wrong.

Whether any of this matters seems to depend on the maintainer and random chance. An abundance of downthumbers has been pointed to by some people as a valid reason not to merge something while at the same time other pulls have gotten merged despite looking from the emoticons like they were universally detested.

Can we just formally say that they either do matter or don't? Or better yet get github to give us someway to turn them off and remove the question entirely. 

I'm sick of getting memed on.

**Comment by PKPenguin321** [comment]
Thumbs are nice for feedback at a glance but are prone to peer pressure mentality ("this has 10 downvotes, better downvote preemptively"). Also they don't appear on mobile which I am on a lot and it makes me sad.

**Comment by phil235** [comment]
They're useful to judge the popularity of a PR and give your opinion on it. I'm not going to read a PR's 100 comments to see who likes it and who doesn't. I don't always want to comment on a PR, because I'm lazy or someone else already said what I wanted to say, so I just upvote/downvote the PR and upvote relevant comments. Not everyone has time to comment on every PR, emoticons make people give their opinion on PRs more easily. It makes judging a PR easier: two maintainers downvoting? probably some big flaw in the code. 15 downvotes? probably a shitty idea.

As a maintainer, the thumbs up/down emoticons are definitely helping.

I don't think  we need a formal decision on this, emoticons do have a specific meaning. We don't need a specific rule of "X downvotes = no merge". The emoticons are here to facilitate discussion. Having  two thumbs up from two maintainers doesn't not have the same weight as two thumbs up from some random players.

**Comment by KorPhaeron** [comment]
>Or better yet get github to give us someway to turn them off and remove the question entirely.

Man I wish

**Comment by Supermichael777** [comment]
FEEDBACK FOURM?

**Comment by ike709** [comment]
Usually someone else already says what I would say in response to a PR (in which case I :+1: / :-1: their post too), or I'm just too lazy to write something myself. Github is literally the first thing I check when I get on my computer when I get home. It's like to be able to provide an opinion at the click of a button when I'm too tired to go into detail about said opinion.

**Comment by PKPenguin321** [comment]
I also like using emotes to passive-aggressively disagree with people since if they respond with "WHY DID YOU DOWNTHUMB ME" they look petty :^)

**Comment by Iamgoofball** [comment]
I and many others just emotespam everythinng so emotes shouldn't matter tee bee aich

**Comment by Razharas** [comment]
They do not matter the slightest

**Comment by Aloraydrel** [comment]
1 upvote = 1 prayer

**Comment by PKPenguin321** [comment]
where's your god now

**Comment by Dorsisdwarf** [comment]
Resolved.

They don't do anything except provide a quick basis for the Popular and Controversial tags because I'm lazy
