### ISSUE TITLE
Deconstructing blue (hacked) APC's don't give extra time in AI malfunction mode

### ISSUE THREAD

**Issue by absalammi** [tgstation/-tg-station#2953]
Title is self explanatory.

**Comment by phil235** [comment]
I see two possibilities: 
- the APC in question was on the mining station, and those don't count for malf.
- the APC's main breaker was turned off before deconstructing it which would lead to the bug since the relevant code checks for `if(malfai && operating)`. The bug is due to the malf apc count not being changed when toggling the main breaker anymore (removed in #5004 for good reasons). Just removing the operating check isn't possible though (you'd be able to break the apc, repair it and break it again to lower the malf apc count).

**Comment by astralenigma** [comment]
Maybe change that check for a flag when the AI hacks it the flag turns on when the APC ceases to exist the flags turns off(although I don't think we need to change the flag in that situation if deconstruction resets all values).

**Comment by AlexanderUlanH** [comment]
Probably not an issue anymore since malf isn't a thing and blue APC's are just the AI sacrificing subtlety for points
