### ISSUE TITLE
Regular speech becomes invisible in some cases

### ISSUE THREAD

**Issue by Barhandar** [tgstation/-tg-station#4757]
Radios still work if you address them directly (.i, .r, .l), but otherwise? Doesn't get picked up.

10/10 bug please keep it (possibly as admin button) everyone turned so polite now they can only communicate in gestures or completely public talk!

**Comment by Jalleo** [comment]
Aranclanos> it was very simple
Aranclanos> I don't remember how to do it but it was somewhat easy-ish
Aranclanos> err
Aranclanos> when you talk, the game goes through the list of ghosts
Aranclanos> and it checks its preferences to see if they want to hear everything
Aranclanos> the say code runtimes there because the ghost doesn't have a client
Aranclanos> to get that clientless ghost in the player list you had to change your ckey with another mob
Aranclanos> but I don't remember how exactly
Aranclanos> hg might remember

**Comment by MrStonedOne** [comment]
This issue no longer exists.
