### ISSUE TITLE
Chem implant runtime

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#5781]
```
runtime error: type mismatch: cannot compare 30 to "action_button"
proc name: trans to (/datum/reagents/proc/trans_to)
source file: Chemistry-Holder.dm,102
usr: Ronny Steel (/mob/living/carbon/human)
src: /datum/reagents (/datum/reagents)
call stack:
/datum/reagents (/datum/reagents): trans to(Ronny Steel (/mob/living/carbon/human), "action_button", 1, 1)
the chem implant (/obj/item/weapon/implant/chem): activate("action_button")
the chem implant (/obj/item/weapon/implant/chem): ui action click()
Activate chem implant (/obj/screen/item_action): Click(null, "mapwindow.map", "icon-x=16;icon-y=12;left=1;scr...")
```

**Comment by Profakos** [comment]
I have run into this one while updating another codebase. The activate proc of the chem implant has only one argument, which is both used by the prisoner console (using numbers) and the action button (which passess the entire action button). What I did was that if the var/cause's value was an action button, transferred every reagent, otherwise converted it to a number, and used that as the injected amount.
This also revealed another runtime that the implant did not null the reference to the implanted mob, so the used up implants still showed up in the prisoner console while it was in qdel limbo.

**Comment by Core0verload** [comment]
Fixed years ago.
@phil235
