### ISSUE TITLE
Unbreakable infinite space loop

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6338]
Getting into a mass driver, such as the one on the white ship, setting it to 16 and shooting yourself out of it can leave you in an infinite loop that thrown items won't break you out of. I haven't tested whether you can break out of these loops at slower speeds.

**Comment by leibniztg** [comment]
Yeah I experienced this, in space I just kept looping, never hitting anything forever.

**Comment by Jalleo** [comment]
Its known but it is apparently unsolveable as it is.

**Comment by Incoming5643** [comment]
Only way to fix this is to introduce translation of movement vectors on crossing maps since the maps can't all be oriented the same way. Some other challenges:

*Mobs that can move through space would have to have held key presses translated to match the new directions after a transition until the key press ended

*Space itself would have to be shown rotating to match the new orientation so people wouldn't be confused when they hit a N-S to S-N boundary and could never escape because they'd keep trying to go "up" and transitioning back and forth between the boundaries.

I'm sure it's possible, but it's not easy and it leads to a situation that's harder for players to understand. I think the fact that some things can accelerate you to the point where it's impossible to slow down by any means is more the problem.
