### ISSUE TITLE
Extra space between AI name and speak verb

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6482]
I only noticed this when not speaking on the radio.

**Comment by phil235** [comment]
It only happens when you are the AI and listening to local talk (not radio), which includes your own speech as AI and the speech of people near your core. I think the bug comes from the interactive chat names (clicking on the name to track the person), it shows as "Namehere (Jobnamehere)". When not on the radio the parenthesis part is removed but the space between the two is kept, thus the two spaces in non radio talk for AIs.

**Comment by Miauw62** [comment]
phil is right
