### ISSUE TITLE
AIs able to see alien larva hiding underneath tables and such

### ISSUE THREAD

**Issue by TZK13** [tgstation/-tg-station#6739]
I've seen so many alien larva get absolutely shit on because of the AI's ability to just check through the list of mobs on their cameras to find them, this should really be changed so that if a larva is hiding underneath something like a table that largely covers it then it shouldn't be detected on cameras.

**Comment by WJohn** [comment]
This is definitely a problem, and it's a shame the AI can so easily track aliens regardless of their status (hiding for larvas, stalking for hunters). Yes, aliens can slash cameras once they've actually grown but the problem is that an AI that checks the list (almost all of them) can easily alert the crew of your presence, and it screws over all your chances of having a surprise base set-up when people are actively looking for you and the shuttle is immediately called.

**Comment by TheVekter** [comment]
This fucked me over a few minutes ago. Any chance of this getting fixed?

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
