### ISSUE TITLE
Uranium walls OP

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6841]
![](http://i.imgur.com/gLQozsD.png)

They have been for a while now.

**Comment by WJohn** [comment]
Especially awful when there are just piles and piles of uranium doors in the way and they all activate eachother's "TIME TO KILL YOU NOW" function when any of them open or close.

**Comment by Steelpoint** [comment]
What stands out to me is that the CE is dead, the CE's Hardsuit offers 90 rad protection.

**Comment by WJohn** [comment]
These things are ridiculously powerful.

**Comment by Anonus** [comment]
Anything short of a radsuit isn't enough to keep you alive near multiple uranium walls without additional chems.

**Comment by optimumtact** [comment]
At this stage I haven't seen any abuse of this tactic so I think it's fine to leave as is.

Unfortunately this incident is likely to touch off a lot of copycats.

The whole uranium walls triggering each other thing should probably be capped at some limit though, since right now it's exponential in nature

**Comment by Miauw62** [comment]
I don't mind it being exponential, it's just too exponential right now.
Op 7-jan.-2015 04:47 schreef "Orange Borg" <notifications@github.com>:
