### ISSUE TITLE
Poly acid can melt most clothing with a single unit from a dropper.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#6857]
This is kind of ridiculously powerful.

OOC: DarkNightSin: with 1 bit, and melted the lions share of my crap
OOC: DarkNightSin: as a fully decked out miner
OOC: DarkNightSin: left me with my jumpsuit and headset basically, not even my pda

@RemieRichards

**Comment by stapler2025** [comment]
how is this not a bug?

**Comment by dannno** [comment]
acid is meant to melt shit, just not this much shit

**Comment by paprka** [comment]
Don't report shit that you get from other people in OOC without testing it first and trying to replicate it.

Have them report it if you can't do so.

If I reported every bug I heard from someone in OOC we'd have twice the issues.

**Comment by Jalleo** [comment]
@stapler2025 we have a not a bug tag for when some specific things are technically not due to how the code is but how it is balanced across everything. Aka this is actually a balance issue of making sure things work properly and evenly. It might sound like a bug but its technically a balance issue of how the code was implemented.

**Comment by RemieRichards** [comment]
it's not easy to change this, the majority of clothing items have no armour values which acid_act() reads as the clothing being weak enough to turn it to goop.

it's intentional, I was aware of 0 armour items when I made this. The majority of clothing items that have no armour values are also cosmetic only so it's not a major loss. (I was a victim of this myself, a pacid grenade outside my office as HoP left me naked and I had to get my spare suit.)

**Comment by Jalleo** [comment]
Could it be changed so all clothes have generic acid'd state if they have no armor value as to make it so it lasts twice but still leaves some sort of visual cue that you should go and replace that since it will probable break apart in about 5 minuites anyhow?

Also lets just never hope we get a station covered in pacid or everyone will be going mad for clothing.

**Comment by WJohn** [comment]
I completely understand a poly acid smoke grenade, of course that should obliterate your clothing. This, however, was 1 single unit from a dropper.

**Comment by paprka** [comment]
Why don't droppers apply to the body part you're aiming at instead of the entire body

Spray bottle acid would be so much better if this was the case too

**Comment by Jalleo** [comment]
Its how the acid works it needs a sanity check.
