### ISSUE TITLE
Implant Bundle provides an uplink implant

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#6872]
this clearly seems unintended as fuck yo

**Comment by Anonus** [comment]
Not a bug, also intended!

**Comment by paprka** [comment]
Yeah, that uplink has been in there for a long time. rip

**Comment by Stickymayhem** [comment]
Revolver Bundle: 24
Darth Maul Bundle: 19 + TK and a hoodie
Assassin Bundle: 21
Maint Murderbone Bundle: 24
Space Bomber Bundle: 22
AI Upload Bundle: 25
Implant Bundle: 38 + Explosive implant

**Comment by tkdrg** [comment]
It's not a bug. It might be a balance issue, but it's not a bug.

**Comment by Stickymayhem** [comment]
Then can it get the balance issue tag

**Comment by Stickymayhem** [comment]
Brilliant thanks

**Comment by Incoming5643** [comment]
This was changed in #2806 but still resulted in a somewhat shitty bundle until the changes to telecrystals. Now it's probably one of the better bundles.

I still think leaving someone with a bundle with just implants is pretty lame because if you need to get cloned you lose all the implants you have, and as a stealth bundle the whole "lets clone the dead antag because we don't know he's an antag" happens pretty often.

**Comment by Incoming5643** [comment]
My only request is that if you end up removing the uplink that you still have the implant vars spell out "fuck"

**Comment by Stickymayhem** [comment]
I think all those implants are perfectly acceptable without the uplink implant. People underestimate how important all those second chances are when used well. It's what makes changelings so damn sticky and dangerous. The uplink bundle is ludicrously strong as it just allows you to buy some additional dangerous shit on top of everything else while you're already immune to both security and borgs, with a way to kill people silenty (EMPing their headset).

**Comment by Dorsisdwarf** [comment]
Please go to the forums if you wish to continue this discussion. Feedback is a good place.
