### ISSUE TITLE
Defib patients dying immediately after resuscitation

### ISSUE THREAD

**Issue by Tenebrosity** [tgstation/-tg-station#6921]
Recently I've noticed that successfully defibrillating someone usually results in them dying again about a second afterwards.

**Comment by Boggart** [comment]
Probably due to #6881.

**Comment by PKPenguin321** [comment]
If this happens it's generally because they're loaded with poisons and since poison wont decompose in the body while it's dead it will still be there when you revive them, easy solution is an antitoxin pill before defibbing

**Comment by leibniztg** [comment]
I experienced this after getting killed by a blobbernaut. After I died they extinguished the flames on my body, then revived me, only to get set on fire again by the chems in my blood.
Rework blobbernaut.

**Comment by phil235** [comment]
Also happens when reviving an irradiated player.

**Comment by Lumipharon** [comment]
defibbing basically just removes oxyloss and tries to make you not dead. Which is why it fails if you've got over 200 of non oxyloss damage. But if you had say, 199 brute damage and got defibbed, you'd immediately die again, unless someone pumped your corpses with dex/dex+/improv (which would start working as soon as you got revived.
