### ISSUE TITLE
The AI can still interact with an APC when the camera is offline.

### ISSUE THREAD

**Issue by Chnkr** [tgstation/-tg-station#7019]
as the title says, open APC, let someone break camera, you can still interact.

**Comment by RemieRichards** [comment]
It's an electronic device, I'd argue once the AI has established a link with it (clicking it once) that they have that link until they rescind it or the device is destroyed.

**Comment by tkdrg** [comment]
This should have been fixed by #6110, does it still happen?

**Comment by Razharas** [comment]
Well since its reported i suppose its still happening

**Comment by HoaxIT** [comment]
Last time i checked on /tg/ yes.

**Comment by MrStonedOne** [comment]
I'm gonna point out that ai interaction uses get_turf_pixel, so pixel shifted objects are interacted based on the shifted location, there may have been more than one camera allowing them to see it, such as a camera on the other side of the wall.

other then that, this should have been fixed by @neersighted's nano rewrite

**Comment by duncathan** [comment]
Fixed by neer
