### ISSUE TITLE
Public Game Logs

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7047]
Head Admins would like to get some form of publicly accessible game, attack, and admin logs for the benefit of the players.

We'd have the IPs and CIDs censored, and only logs from at least a day earlier (or round, if possible) would be available so they can't cheat the current round. 

Asay chatter could also be kept private as we do occasionally have sensitive conversations in there, like we do in adminbus. But I think everything else should be put up for grabs.

**Comment by Ikarrus** [comment]
Pinging @mrstonedone and @hornygranny as they may be interested parties

**Comment by Ikarrus** [comment]
Proposal was defeated by executive decision.

**Comment by An0n3** [comment]
There's some misrepresentation of the situation in these comments.

We had a lengthy discussion about making the logs public on the forums a while back, in which Hornygranny and myself both said it would be a bad idea.  None of us were headmins yet, but our opinions haven't changed much since then.

We discussed this again and I don't think it's fair to SoS to say he solely veto'ed it when he, HG, and myself again expressed misgivings about having all these records publicly viewable.

**Comment by Tenebrosity** [comment]
Are you actually going to share any of these reasons?

**Comment by Niknakflak** [comment]
Saved admin logs can still be a thing?

**Comment by Ikarrus** [comment]
@Niknakflak #7096
