### ISSUE TITLE
Job preferences menu is too wide

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7086]
The sorting got messed up because of my splitting cargotechs/miners into their own 'supply' job sort. But i have literally no clue how to work with this HTML to restore it back to normal, so.

![ss 2015-01-15 at 01 27 57](https://cloud.githubusercontent.com/assets/7247232/5755140/bfa1431a-9c55-11e4-8c9e-7c16cc9fe221.png)

They should be below HoP, and their color should be brown.

**Comment by Jordie0608** [comment]
As far as I can tell, since the subsystem list used for this is populated in alphabetical order of the files which jobs are in, a lazy fix would be to just move the three jobs back into the civilian.dm file or perhaps a civilian_supply.dm.

As for color, just change the selection_color var in each job's define.

**Comment by Carn** [comment]
use timSort to sort them?
