### ISSUE TITLE
Let Admins Flag Ckeys to Watch

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7158]
Let admins flag specific ckeys so they can be alerted whenever that ckey joins the server.

It would be really useful for watching problematic players.

Credit to ahammer I'm just making this issue for him because I really like this idea.

**Comment by Ahammer18** [comment]
+1 good idea

**Comment by TheVekter** [comment]
:+1:

**Comment by Alek2ander** [comment]
Should also trigger on related keys, because multikeyers.

**Comment by PKPenguin321** [comment]
@Alek2ander Probably not, since I'm like 85% sure there's already a thing for people playing on the same IP and if you go through the trouble of changing your IP but not making a unique ckey then you're probably gonna get banned anyways by an observant admin. Leaving that up to automation could lead to errors getting innocent people flagged or banned.
