### ISSUE TITLE
Aubrie Allen stammers, "<p-p-pan-n c-c-cl-l-l-las-ss-s-s='san-n-n-ns-s-s'><s-s-sp-pan-n-n-n c-cl-l-lass-s='jok-ker-rm-m-man-n'>H-H-H-Hm-mm.</s-s-sp-pan-n></s-sp-pan-n>"

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#7259]
Stammering interfers with other speech span classes.

**Comment by Miauw62** [comment]
@Iamgoofball i'm going to murder you

**Comment by Iamgoofball** [comment]
Fucking stammering code, probably just need to move the mutations say handler to below stammer handling

**Comment by Deantwo** [comment]
According to [say_readme.dm line L116](https://github.com/tgstation/-tg-station/blob/e25affe12ee9d677952f3a5f4dafedef67f26494/code/modules/mob/say_readme.dm#L116)
This where the problem is. Font changing should probably be moved to there somehow.
Here is a the search results I found: "[treat_message(](https://github.com/tgstation/-tg-station/search?utf8=%E2%9C%93&q=treat_message%28)"

(I told you on [#coderbus](irc://irc.rizon.net/coderbus) @Iamgoofball, just leaving a note here for others to see.)
