### ISSUE TITLE
Janiborg and Mediborg hacked modules don't work

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7273]
They should be full of, and refill with in chargers, space lube and polyacid, respectively.
I'm guessing chem issue.

**Comment by GunHog** [comment]
You must sit in a cyborg recharger to gain the reagents.

**Comment by Anonus** [comment]
Yes, and they're A: empty, and B: don't refill.

**Comment by MrStonedOne** [comment]
@Iamgoofball

**Comment by snakebutt** [comment]
Another associated problem I've noticed is that if you unequip the module, it completely empties instantly, requiring another 3 minute charge session to fill the spray bottle.

By association, mediborg beaker is useless as fuck because you can't fill the beaker with a robust mix and inject it with the syringe, as the instant you stow the beaker it's empty. I haven't examined the code but my best guess is every time you grab a module it spawns a new item rather than a single persistant one, or clears variables whenever stowed. Either way, with the limited module space borgs have, beign FORCED to keep something equipped to be usable is pretty bullshit.

**Comment by Iamgoofball** [comment]
wasn't there a chem container overhaul recently

**Comment by Jordie0608** [comment]
This issue was fixed by qq's PR.

@snakebutt's issue has existed for ages since anytime a reagent_container with the opencontainer flag is stowed by a borg, it's cleared of reagents; and beakers, sprays, bottles etc. have been opencontainers forever.
