### ISSUE TITLE
Edge case: If an AI uses the teleport spell when in an intellicard, it clones the AI core and breaks the intellicard, plus core display issues?

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7303]
I was AI, I got the teleporter spell because admins, and I tried to teleport while carded. The following happened:

- New AI core generated at where I teleported to, that was considered where I "was"
- Old intellicard still showed as having me in it, according to the admin I was "both in it and not."
- Possibly related, possibly a separate bug (leaning toward the latter but putting it here): The AI core display showed the "dead" animation. This went away only upon changing my AI core display again via the verb.

Might also work in integrity restorer

**Comment by Miauw62** [comment]
needs testing, may be fixed already.

**Comment by bgobandit** [comment]
this happened like one round ago so I sincerely doubt that

**Comment by GunHog** [comment]
Confirming this as the Roboticist that repaired the dead AI. It teleported out of the AI fixer, creating a new core with a dead clown AI sprite. I carded the AI again, only to have it teleport out of the card. It still had the AI's icon, but was otherwise an empty card. The cores left behind from carding the AI remained as empty AI cores.

Because this is caused by badmins, and cannot occur in a normal round, it is not that high of a priority.

**Comment by Incoming5643** [comment]
it actually can, but the requirements make it staggeringly unlikely:

1. A wizard would have to learn the teleport spell as well as cast summon events
2. The rare robeless casting event would have to take place
3. After this the wizard would have to be MMI'd and installed as an AI
4. That AI would then have to be carded.

**Comment by Incoming5643** [comment]
this was fixed in #6990
