### ISSUE TITLE
Mobs are randomly removed from the moblist

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#7317]
Alright, going to ref this to @Ergovisavi because he knows what's going on (from a coding standpoint).

Essentially what's happening is, every so often, a player disappears from the moblist. No one's sure why it's happening but it needs to be looked into. CANNOT REPRODUCE, but I'll ping anyone who wants to be pinged when it happens.

Side-effects:
*Players cannot die, can take up to 500+ brute to no ill effect.
*If stunned/disabled/what-have-you, they stay in tha tstate. Can't be revived in any way.
*They don't show up in the moblist, so you can't interact with them in any way. No ban, no kick, no get-mob, nothing.

Someone mentioned it basically stops them from updating.

Seriously needs to be fixed, this requires us to remake an entire player every time it happens.

**Comment by Iamgoofball** [comment]
i think it's time to dust off the higgs bugson tag

**Comment by WJohn** [comment]
Jesus christ.

**Comment by TheVekter** [comment]
I think this merits a high priority, yeah?

**Comment by paprka** [comment]
@Carn if you can take a look at this please

**Comment by Carn** [comment]
Only helping because I know the answer and it'll take you all ages to find this.
https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/mobs.dm#L24
People started modifying the mob_list from Life() or a proc called by Life()
As a result, incorrect elements are being removed by that Cut().
May also result in out-of-bounds.
Similar issues where encountered with machines. Likely related to qdel() system.

**Comment by TheVekter** [comment]
Much love, @Carnie. I'll make sure the others see this asap.

**Comment by Carn** [comment]
Disregard that i suck cocks :alien:

**Comment by TheVekter** [comment]
That wasn't it? o_O

**Comment by Boggart** [comment]
I did a search for mob_list and I didn't see anything besides new and destroy modifying it.
