### ISSUE TITLE
No Gravity In Ship Area's

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#7326]
@Carn

If you walk into a area a ship would normally be, for example the Nuke Ops ship, you'll find there's no gravity anywhere in that area.

This means a small part of the Nuke Ops base, for example, loses Gravity while the ship is away, and if anyone walks around the area the ship used to be, they will be without gravity, even though there's snow tiles there.

**Comment by WJohn** [comment]
Perhaps have docking ports be able to project gravity?

**Comment by Steelpoint** [comment]
It would need to be toggable, so that docking ports over space don't give Gravity.

**Comment by Carn** [comment]
STOP
PINGING
ME

**Comment by Carn** [comment]
>act like shit
>I leave
>ping me to fix stuff

**Comment by paprka** [comment]
@Carn 
>be dramatic
>leave
>will probably come back eventually anyway

Or maybe just don't leave and continue to maintain your shit instead. Thinking of /tg/ as this big entity that's collectively wronged you instead of a select group of people is fucking stupid, sorry.

I know you care about the project, so fucking man up and start abiding by sticks and stones instead of having the literal frailest of egos.

You created bugs, you left without any real notice. Not everyone is up to speed with your dramatic itinerary. Either stay gone and stop commenting or get the fuck back here and unfuck your mess before it gets replaced.

**Comment by Carn** [comment]
lol

**Comment by Steelpoint** [comment]
Did Carn just bail?

**Comment by paprka** [comment]
yes

**Comment by dannno** [comment]
lmao drama
