### ISSUE TITLE
Plates are named after the dish that was on them 

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7374]
e.g. "the waffles" instead of "the plate" or "the tray"

**Comment by AlexanderUlanH** [comment]
They also disappear when you wash them.  I imagine there either used to be or were going to be actual plates which would be ingredients in recipes, and which you could get back by cleaning, but that either wasn't implemented or was removed.  The fix for this would be either to get rid of the dirty plates left behind after food's eaten, or to add plates/bowls/trays to the kitchen vendor, put them in recipes, and fix washing.

**Comment by Tenebrosity** [comment]
Yeah it's always struck me as odd you don't need plates to make food but they leave plates behind

**Comment by Dorsisdwarf** [comment]
did @phil235 's kitchen overhaul fix this?

**Comment by phil235** [comment]
nope, still there
