### ISSUE TITLE
Speech formatting is handled shittily

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#7378]
it was okish before when there was only italics but with all the new shit added, Gia was right and I should code something to make this not suck.

**Comment by GunHog** [comment]
Poor Meow. If you do not mind, could you also make these fonts and things possible with NTSL?

**Comment by Miauw62** [comment]
i can't, i dont understand how ntsl works.

**Comment by GunHog** [comment]
It is not at all THAT complicated to add. When you reworked languages, you let NTSL read languages with the $language var. If you gave fonts a define in say(), along with a var for which font to use, and let NTSL read *and set* the var for the message, you can control the font using NTSL. I would wager that since you are improving upon the original method of applying fonts, I could code the NTSL portions myself.

**Comment by Iamgoofball** [comment]
the original method of applying fonts is a span class

**Comment by Miauw62** [comment]
that is the dumbest thing i've ever heard.

**Comment by Iamgoofball** [comment]
/vg/ was researching it for ages and it was the only way

**Comment by optimumtact** [comment]
The only good solution in my mind is that a message stays as a datum consisting of the raw message text and the formatting options to apply to it. This remains this way until it is actually output to the client.

That would require a pretty big rewrite though.

**Comment by pudl** [comment]
when will we kill telecoms

**Comment by Miauw62** [comment]
oh hey this can be closed

**Comment by Iamgoofball** [comment]
when was this fixed

**Comment by Miauw62** [comment]
smh
