### ISSUE TITLE
goliaths are not fun to fight

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#7416]
I would prefer that the tentacles be used twice as often, but stun half as long, for example.

**Comment by AlexanderUlanH** [comment]
The tentacles need to stun long enough to give the goliath a decent chance to close in on you.  If you halve the stun time, you halve the distance the goliath can travel while you're down, meaning you can safely let yourself get knocked down while shooting at the goliath with the KA.  
Personally, I find fighting goliaths pretty interesting, because you need to either prepare an open area to fight the goliath, or manage your position carefully in an irregular mine to avoid being stuck next to the goliath, or, when the tentacles are coming, a wall.  It's at least more interesting than fighting basilisks.

**Comment by dannno** [comment]
Goliaths are like, the only mining mob whose fighting strategy isn't "run up and click them fast as you can before they can kill you"
Literally the only interesting mob to fight

**Comment by Cheridan** [comment]
git gud lmao

**Comment by Cheridan** [comment]
fixed by someone i guess. tentacles work different now.
