### ISSUE TITLE
Free arcade items. #ripfun

### ISSUE THREAD

**Issue by HoaxIT** [tgstation/-tg-station#7457]
> Open arcade
> Click start
> Hop in locker
> spam click continue

**Comment by HoaxIT** [comment]
Only works on the ORION TRAIL machines, at least as far as i tested.

**Comment by paprka** [comment]
>implying arcades will ever be fun

**Comment by Tenebrosity** [comment]
>implying the items will ever be worth it

**Comment by Iamgoofball** [comment]
>implying you don't want toy esword

**Comment by Chocobro** [comment]
i'll test to see if this happens with regular arcade machines now.

**Comment by phil235** [comment]
The issue is being able to click buttons on machine windows while inside a closet. This happens with all machines apparently, clicking the button works and somehow the window isn't updated thus the possible abuse. The machine Topics need a new check to make sure the mob is actually next to the machine.
