### ISSUE TITLE
You can occasionally sleep the wrong way

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7599]
![sleepdood](https://cloud.githubusercontent.com/assets/5677255/6093811/7ee4a5f0-af07-11e4-9aa8-addec2c73c41.png)
mostly a sprites issue.

**Comment by RemieRichards** [comment]
not a sprite issue at all.

Ages ago laying down used to always face the right, as we used an entire seperate set of sprites for players and clothing and genetics for lying down.

Sensibly when Byond 500 came out we moved it all over to just rotating the standing up icons by 90 degrees, which added the ability to rotate the other direction, which was then included as a possible chance.

Whatever method sleeping uses for rotating should probably just be swapped with a guaranteed fall to the right, so that beds line up correctly.

**Comment by Chocobro** [comment]
thanks byobama

**Comment by paprka** [comment]
Or you could just buckle yourself to the bed before sleeping...

**Comment by TZK13** [comment]
Please don't make it impossible to rest facing left with any sort of fix to this, as Pap said buckling to the bed works absolutely fine.

**Comment by Cheridan** [comment]
yeah just buckle yourself
