### ISSUE TITLE
24h limit on PRs is arbitrary

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7659]
https://tgstation13.org/phpBB/viewtopic.php?f=5&t=2766

There really is no reason for things not to be handled case-by-case

**Comment by paprka** [comment]
Doesn't need to be an issue report, people have stated their case on it. 

I think it should remain for things tagged 'feature' or 'map edit', but small tweaks should be able to be merged without much of an issue. @Cheridan expressed some issue with removing the limit for anything, I don't know, most server-crash fixes are merged immediately anyway but whatever.

**Comment by Incoming5643** [comment]
I thought the time limit was there to prevent stealth merges and collusion pulls where only the creator and one person with merge access ever saw it, since you know, they could be friends.

**Comment by Deantwo** [comment]
It is nice to have the 24 hour wait.
That way we are sure that at least a few people have had a chance to look at the code.

Could just change it to be that x number of maintainers has to have given the code a ":+1:", but then you'll just end up waiting longer than the 24 hours.

The only place the 24 hour wait doesn't make sense is for single line fixes that are easy to understand and clearly doesn't break anything.

**Comment by Razharas** [comment]
Things that are excepted from 24 hour rule:
* Fixes of critical bugs(either explained why its critical in description or fixes an issue marked as critical)
* Map changes without balance changes/with balance changes agreed upon before the pr was made
* Changelog prs

**Comment by Cheridan** [comment]
There's a lot of reasons to keep it, that @Deantwo and @Incoming5643 touched upon. The limit is there so that things can be reviewed and discussed properly. 

You can't go "Oh well I'll make an exception for this cuz it's only a tiny 1-line thing", because this is programming and 1 line can cause massive lag, huge errors, or non-compiling code. 

It's also not good in the long run for people to be able to make sweeping changes just because "OH HEY IT COMPILES GJ *smashes forehead on merge button*"

24hr is not too long to wait.
