### ISSUE TITLE
Humanized monkeys have no blood types

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7803]
Humanizing a monkey gives you a stock of typeless blood, which makes the humonkey both a universal donor and universal receiver.

**Comment by Incoming5643** [comment]
Also, humorously, you can attach two IVs to a humanized monkey, one injecting typed blood and one drawing untyped blood, and create a bioreactor that removes the typing from all blood.

**Comment by RemieRichards** [comment]
with that last comment you've just confirmed this is a feature and will now not be changed.

**Comment by Incoming5643** [comment]
Outside of this bug you can do the opposite with someone who's AB+, and slowly but surely make all the blood reserves on station nearly useless.

It'd be a hell of a slow sabotage though

**Comment by Chocobro** [comment]
wasn't this reported already? i might be hallucinating.

**Comment by paprka** [comment]
There's a proc that randomizes blood that needs to be applied to monkey humans somewhere, but I don't know genetics code so

**Comment by Menshin** [comment]
Monkeys apparently don't possess DNA (and monkeyize humans are still human species since their DNA is not updated).

Humanized monkeys are getting a blood type when i'm testing... that doesn't match the one in their DNA...

Why two vars (_blood_type_ and _dna.blood_type_) in the first place ?

The whole thing is a mess... :confused:
