### ISSUE TITLE
Kinetic accelerator shots call gets_drilled really strangely

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#7813]
This results in some oddities.

Drilling turfs around the shooter instead of where he shot.
Sometimes *not* drilling turfs he shoots at.
**Sometimes drilling gibtonite twice at the same time, making it explode instantly.**

 #7720

**Comment by paprka** [comment]
top kek

**Comment by Dorsisdwarf** [comment]
uh, if you hit the gibtonite with the main blast, it will ALWAYS explode instantly.
I dont know about the 3X3 bit

**Comment by ACCount12** [comment]
It is not calling gets_drilled directly for radius explosion. It calls ex_act instead.
1. I spent 2 hours catching this bug. It's GC being massive wall of shit i think.
2. This is because kinetic uses ex_act(). Ex_act has a bit of random in it.
3. Totally intended. You are using a big bad energy pump shotgun with explosive charges for mining, after all.

**Comment by RandomMarine** [comment]
It is in this codebase @ACCount12

It was changed because it caused #7719 here.
