### ISSUE TITLE
The kinetic accellerator is unbalanced as FUCK

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7831]
With one shot from a kinetic accelerator when it's tweaked enough with a screwdriver, you  can clear 9 tiles of rock immediately. It's simply the best mining tool right now, when it's meant to be a fucking combat tool primarily for monsters.

Holy shit, rework this @Iamgoofball , it's extremely unbalanced.

**Comment by Chocobro** [comment]
didn't even know you could tweak it.

**Comment by AnonymousNow** [comment]
It's a very recent change, Chocobro.

As somebody who has played mining a hell of a lot since the Goofchem fiasco started, I have to reluctantly confirm this ('cos I want to keep playing with it...). Were it not the for the double-fire bug which has the added disadvantage of triggering gibtonite immediately, the PKA would be the be-all and end-all of mining equipment.

I want tweaks, but maybe it's better if they're optimised for combat rather than mining. I've previously used the PKA as a makeshift mining tool until I could upgrade to something better, and I'm not entirely sure it should fill the hole completely.

**Comment by paprka** [comment]
I don't mind the tweaks but holy shit there is no reason to not use the kinetic accellerator since there is zero downside to tweaking it. I think if you want to tweak it with a screwdriver it would have some downside of potentially exploding in your hands or backfiring and shooting yourself. It's stupid good right now.

**Comment by Iamgoofball** [comment]
It does this by default, I'll tweak it.

**Comment by paprka** [comment]
Well then test it because it doesn't at all do that

**Comment by TheWiznard** [comment]
I just tried it and holy hell it is so good when you fully screwdriver/diamond it up. As much as it makes mining a breeze I don't think it should be so extremely good, like maybe reduce the screwdriver tweaking to once and only adding 1-2 diamonds instead of what it is now.

**Comment by Dorsisdwarf** [comment]
It makes mining so fun it's unreal I love it 190/190

**Comment by francinum** [comment]
This is 30 minutes with a Full KA:

![](http://i.imgur.com/zjZ9Kmd.png)

**Comment by Miauw62** [comment]
ergo is probably spinning in his grave.

**Comment by Iamgoofball** [comment]
Someday I'll nerf it

**Comment by WJohn** [comment]
Yeah this needs to be nerfed badly. I'm seeing miners with tens of thousands of points on their cards making a thousand sheets of plasma every round, and cargo gets stupidly retardedly rich from it.

**Comment by Iamgoofball** [comment]
paprika was going to fuck with this but then paprika got banned

i'll nerf it

**Comment by AnonymousNow** [comment]
Maybe have this functionality locked behind a mineral gate. What once took a screwdriver now needs gold/silver/uranium/alladem. Maybe it can be rebalanced alongside the diamond upgrades.
