### ISSUE TITLE
Editing alien icon .dmi paths reverts to what it was a second later.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7849]
As an admin, if you try to edit an alien's icon .dmi location to something else or something you made (in my example to try out different looks and castes), it will revert back to what it was almost immediately. This doesn't seem to happen with humans.

**Comment by Razharas** [comment]
Its probably because unlike with humans whos icons are just rotated, aliens have different icons for unconcious and dead states, so probably alien life proc is changing it back to what it was
Wild guess

**Comment by RemieRichards** [comment]
it's wired into how alien update_icons() works, without it, the aliens would be stuck in alien_leap.dmi
Humans don't have this issue because everything human is in one dmi, everything they wear is in seperate ones,

Aliens have two icon files, 1 of standard size, one of leap size, so it has to force it back if it's not in leap mode.

**Comment by WJohn** [comment]
Is there any way to fix this outside of moving all the sprites to the 3x3.dmi?

**Comment by RemieRichards** [comment]
Can't even do that WJ.
Byond locks sprites to being the same size.

**Comment by WJohn** [comment]
I mean it'd be easy enough to shift them into place so they'd be in the middle. I've done this many times.
