### ISSUE TITLE
Toggle internals doesn't work with oxy jetpack

### ISSUE THREAD

**Issue by quaggaman555555** [tgstation/-tg-station#7879]

**Comment by AnonymousNow** [comment]
Not a bug - a recent deliberate change, apparently to make jetpacks less appealing to greytiders... actually, I'm still not entirely sure about this one. Could somebody remind me of the real reason, please?

Same change also readded large tanks to exosuit slots on certain hardsuits (by making all tanks into similar objects in the code again), which is nice.

**Comment by PKPenguin321** [comment]
I don't recall anything like that. Probably just broke because they had to separate jetpacks from internals tanks to make internals fit into suit storage slots without letting you wear jetpacks.

**Comment by paprka** [comment]
you do not have to separate jetpacks in order to hold large tanks in your suit storage slot. xxalpha just did this because he ~needed~ to repath all the fucking tanks and miauw said my solution was 'hacky'.

https://github.com/tgstation/-tg-station/pull/7465

reminder that miauw shouldn't be a maintainer and xxalpha is a shitty coder.

**Comment by PKPenguin321** [comment]
You can still breathe from it, you just need to open the internals menu and open the valve. The HuD shortcut just doesn't work.

**Comment by paprka** [comment]
That's even more hilarious.

**Comment by xxalpha** [comment]
Not being able to use jetpacks as internals is deliberate.

**Comment by paprka** [comment]
It's a bad balance change. The reason jetpacks use oxygen in the first place is because in real life you can choose to expend your oxygen reserves as fuel for your jetpack. It's also good for inventory management. I suggest just adding jetpacks to the button again, since you can do it anyway by opening the valve from the jetpack's menu.

Again, this is why I said 'internals' as a child path was a bad name.

**Comment by Miauw62** [comment]
It was better than your hacky-ass fix, paprka. Not their fault that people are using this for the wrong reasons.
