### ISSUE TITLE
Machines can't be unfastened or wrenched into place

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#7903]
Machine-frames are not consistent with other frames. All similar frames (computer, airlock, turret) need to be wrenched in place before continuing construction, but machine-frames get disassembles by a wrench, when others get disassembled by a welder.

This means that e.g. moving a freezer/heater to another location is not as fast as you'd expect since you need to build the frame all over again.

Now that I think of it (but should this be a new issue?), wall girders are a weird one as well since they get disassembled by a wrench too, and if you want to disassemble a dislodged girder, you first need to wrench it in place, then wrench it again to disassemble it. Feels weird, but I guess people are kinda used to it.

**Comment by TheVekter** [comment]
If we're talking about just the plain machine frame, nothing in it, then yeah, definitely. I don't see why you CAN'T move them. But when they have stuff in them they're not supposed to be mobile.

**Comment by Lumipharon** [comment]
Some machines are supposed to be mobile, and would be EXTREMELY tedious otherwise.

For example, vending machines. You have three refill things, that are all bulky items.
Also hydro trays have always been mobile, and you can move them without disturbing the plant inside them.

But yeah, +1 to moving frames.

**Comment by Cheridan** [comment]
fixed by thing probly
