### ISSUE TITLE
Antag/Sec hud overlay for admins

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#7957]
Would it be possible to give a toggle-able button? So that observing admins can quickly see the antag (for example, rev and rev heads or cultists) via the overlay players get. 

And also another button to allow job view similar to the sec hud. This would give a lot of extra information, quickly, to admins.

**Comment by Steelpoint** [comment]
Just for fun why not allow Ghost to get a antag hud?

Make it a function where if you select to be able to see a antag hud as a ghost, you forfeit your ability to be cloned and whatnot.

**Comment by GunHog** [comment]
HUD icons are all there, left over from Ninja, as well as the team antagonist icons. Ghosts having Medical and Security HUDs would be quite nice. AntagHUDs might be a bit of a controversy, so that one must be approached with caution.

**Comment by Chocobro** [comment]
ghosts shouldn't get an antag hud in case of multi-keying or metacomms. admins can be trusted with this since, well, they're admins.

a sec/med hud on ghosts should be fine, since you can't do much other than gather info on who is weak, or who is set to arrest.

**Comment by peoplearestrange** [comment]
Antag hud as admins was the thing I was shooting for, specially in rev rounds where its not always easy to see who is currently a rev.

**Comment by Chocobro** [comment]
yeah i'm all for that.

**Comment by MrStonedOne** [comment]
The issue is ghosts have no regularly occurring anything

So doing this in any smart way would require a lot of hacky code to find any where somebody can be made an antag.

Start with porting sec and medical huds to ghosts that isn't gonna break the no copy and paste rule.

After you grow 15 grey hairs from that, you will have a better idea of how hard it will be to do antag hud.

You either have to do a loop for things in the ghosts sight on a regular basis, or bind to all the places that somebody can become an antag, than risk that some other code change is gonna cause somebody to become an antag without triggering, giving them no hud icon, then they get yelled at by an admin.

If you do go with the latter option, do put a warning message to the admin triggering it that they should alway check the mobs tator panel before taking administrative action on somebody showing up as not an antag.

**Comment by Miauw62** [comment]
We have a passive HUD system, I don't remember who added it but it should
be possible to just add ghosts to it?

**Comment by GunHog** [comment]
Yes, indeed.

**Comment by MrStonedOne** [comment]
For medical and sec huds, yes.

This issue is antag hud.

I looked at adding this some time ago, and its not as easy as you would hope.


The issue is the fact that antags change, and they do so ALOT. so any hud system has to hook in to every where any antag status can be changed, then you have to hope nobody changes antag shit in way that doesn't take account for you shit.

If you make a hud that will be used by admins to determine rather or not somebody should be banned for certain actions, you can't afford any mistakes.

So the choices are: Active hud system that actually checks visible mobs for their antag status

Or: passive hud system that can be wrong and give false positives or false negatives and makes maintainability harder as its yet ***another*** passive system that has to be notified when certain things happen.

**Comment by Steelpoint** [comment]
If its going to be used by admins then it needs to have a very low chance of failure. No one wants to be yelled at by a admin because the system mistakenly thought the guy was a antag or something.

**Comment by MrStonedOne** [comment]
Actually, i still have the code for an active hud system. (the only kind without a chance of failure, and what vg/bay uses)

I'm gonna go update the branch and work on it right now.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
