### ISSUE TITLE
Virology PanD.E.M.I.C 2200 exploit

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#8031]
You can get around the cooldown on generating a new virus culture bottle in the PanD.E.M.I.C 2200 machine in virology.
It's as simple as inserting a blood sample with a virus, clicking the "Create virus culture bottle" button, then clicking the "Create virus culture bottle" button again as many times as you want, then clicking OK on all the menus that pop up.
Completely ignores the cooldown on generating new bottles which probably definitely isn't intended. Bottles generated is equal to the number of times you clicked the "Create virus culture bottle" button.

**Comment by Marflowerose** [comment]
To be fair, the regular cooldown is just frustrating, which coupled with the RNG of virology in general makes it just an extra nuisance. It's not like printing out 30 bottles of virus blood has many uses since there are other ways of gaining infinite non-typed human blood that all blood types can use. If you fix the bug at least lower the cooldown and if you're worried about balance, make the virus blood unusable as regular blood refills or have the bottles have smaller amount of blood.

**Comment by PKPenguin321** [comment]
i feel about the same, only reason i reported this as a bug is because it's not intended, even if it is better than what we have
if someone goes to fix this, consider just removing the cooldown so it'll be considered intended and no longer considered a bug
