### ISSUE TITLE
Energy Shields: Reflect Chance Bug?

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8035]
When not active, these have a reflect chance of 0 and when active, they have a reflect chance of 40.

In actuality though, their reflect chance is 100% when active and 0% when not; the reflect_chance values really don't do anything.

If this is intentional, then the reflect values should probably be removed...but if they're not, well...there's a bug.

**Comment by paprka** [comment]
Honestly I always assumed energy shields were supposed to be 100%, which is why they're so pricy.

Even if this isn't intentional, it's proven to be a good strategy for nuke ops that makes the energy shields worthwhile instead of RNG tools. Perhaps their price can be increased if they're a constantly chosen thing though.

**Comment by Razharas** [comment]
I remember talking about this with ergo, and they said that while unintentional it probably shall be made intentional

**Comment by Fox-McCloud** [comment]
Ahh; may want to remove the reflect chance then, so as to not cause confusion.

Thanks for clearin' it up.

**Comment by Razharas** [comment]
I and ergo discovered this on their server a few months ago durning stun nerf testing, and after talking decided to leave it be coz it seemed balanced enough
But ill accept both nerf to proper values or the removal of chance var

**Comment by Fox-McCloud** [comment]
sounds like removal of the var is the way to go then!
