### ISSUE TITLE
Black powder holy shit

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#8039]
![shotgun dart](https://cloud.githubusercontent.com/assets/7869430/6414006/5b4fecec-bef9-11e4-8ee1-4abc90e2c447.jpg)

Not a very big explosion you say?
This was from a shotgun dart.

Seriously just look at the code for blackpowder. You can make it purely from a chem dispenser and heater in a minute tops, and JUST LOOK AT THIS SHIT.
at 30u you get a 3,5,7 explosion.

What.
The.
Fuck.

You can gib someone with a SYRINGE if you're clever.

Cryobeakers let you POUR people into tiny pieces.

Literally just, what.

**Comment by Iamgoofball** [comment]
Will up the dividers on it

**Comment by Dorsisdwarf** [comment]
I think we should just remove black powder.
We already have explosion chems, black powder is way too easy and way too explosive. Nitroglycerine (a really hard to make chem) looks wimpy by comparison.

**Comment by Iamgoofball** [comment]
@Dorsisdwarf no

**Comment by Dorsisdwarf** [comment]
Why? Because it's your ported codebabby? It's overpowered, over-easy to make, and makes two other recipies redundant all for the reason "I want to be more goon".

In general I'm mostly okay with the new chemicals now they've been fiddled with extensively, but this is "I want my fukken doom powder okay? is from favorite server"

**Comment by Iamgoofball** [comment]
No, because I have planned changes to it that will make it worth having and not OP

**Comment by paprka** [comment]
any explosions are OP unless they're fire bombs

**Comment by TZK13** [comment]
What is the point in a third explosive chemical reaction though?

**Comment by AnonymousNow** [comment]
Ah, Goonchem.

**Comment by Lumipharon** [comment]
So as well as being OP as shit, it's also genuinely fucking hilarious.
I went around as a tatorling with a shotgun and a bag full of these gib darts, and gibbed half a dozen people.

NO ONE EVEN REALISED what was going on. After someone gets hit by the dart, there's a good 3 seconds before they actually explode.

I shot a HoP in the medbay, and he had time to chase me out into the corridor by the bridge, before blowing up.

**Comment by babinsquared** [comment]
@TZK13 Black powder explodes when heated, not necessarily when mixed like potassium/water and nitroglycerin. Black powder also has a super super low metabolism rate.

Potassium makes small bombs (big if you get bluespace beakers but good luck getting those in large numbers or at all)
Nitroglycerin makes big bombs but requires help from other departments (and good luck getting corn from the botanist if botany is meta because nitro is the only reason chemists ask for corn EVER), it's also tedious to make because you have to keep grinding and sifting out everything but the corn oil to make just a small amount of glycerol.
Black powder makes bombs which can stay dormant inside people until you manage to heat them up. It's got hilarity potential, it just needs some scaling back in terms of damage and obtainability. 

It has a nice niche because of its unique mechanics.

**Comment by dannno** [comment]
unique mechanics which obviously aren't working, if lumipharon can gib people just by getting it on them.

**Comment by Iamgoofball** [comment]
@dannno it's not like we can nerf it or anything :^)

**Comment by Jalleo** [comment]
@Iamgoofball have you thought about changing the units to be more separated e.g milliliters centiliters liters? This if done properly could make things much more balanced when it comes to chem while not making it as difficult.
