### ISSUE TITLE
Slime verb Feed does not allow to feed on other slimes.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8095]
As a human controlled slime you can drag drop yourself onto other slimes to feed on them. If you use slime verb Feed, slimes dont show up and you cant do so.

**Comment by Delimusca** [comment]
this is because feed() ignores slimes for the choices list, while dragdrop goes straight to feedon().
i'm not sure why feed ignores other slimes. i know AI slimes use feedon so it's not that, could be to stop list clutter, could be because slime-on-slime combat used to be silly and feed would've been OP. it is an easy way to get nutrition with little risk or harm though, that might be a bad thing. in any case, all the slime stuff needs a bit of a rework.

**Comment by phil235** [comment]
The inconsistency was fixed by one of my recent PR. Slimes can no longer feed on other slimes. The feed verb predates the mousedrop feeding so it seems feeding was never intended to work on slimes.
