### ISSUE TITLE
Welding Helmets do not prevent eye damage 

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8268]
![literal garbage](https://cloud.githubusercontent.com/assets/9714964/6568498/9a647440-c695-11e4-8f98-0029047b5422.png)

Shitty fucking screencap but details the issue

Eye damage is not blocked by welding helmet - No other eyegear present. Bear in mind this happened after an EXTREME amount of welding (30-40 uses)

**Comment by TheVekter** [comment]
I'll look into it.

**Comment by TheVekter** [comment]
Could not reproduce on live or test servers. Tested with normal welding helmet, welding gas mask and welding goggles.

Only thing I can think of is, was it a collectible one? They look identical but the collectible mask doesn't function as one. Odds are preeeetty low that's what it was, but it's an idea.

**Comment by SeikoTheSeal** [comment]
Happened to me aswell. Been fixing a borg without protection during blob, borg eventually dies, took it to robotics,grabbed a helmet before fixing it, welded few times, blind.

**Comment by phil235** [comment]
this happens when you have some significant eye damage (eye_stat var) beforehand.
It looks intended in the code, the eye_check() proc of the welding tool has:

>if (prob(user.eye_stat - 25 + 1))
_____user << "<span class='warning'>You go blind!</span>"
_____user.sdisabilities |= BLIND
else if(prob(user.eye_stat - 15 + 1))
_____user << "<span class='warning'>You go blind!</span>"
_____user.eye_blind = 5
_____user.eye_blurry = 5
_____user.disabilities |= NEARSIGHTED

**Comment by TheVekter** [comment]
Doesn't make any sense. Why would you go blind wearing a welding mask?

I'll probably change this later.

**Comment by Miauw62** [comment]
yeah, this is weird even if its intended.

**Comment by TheVekter** [comment]
If I had to guess, it's a hacky way of making eye damage scale based on
existing damage. Worse your eyes are the easier it is to go blind. I think
we can do better than that.
