### ISSUE TITLE
Balance: Eyestab is Overpowered

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8387]
This proc (https://github.com/tgstation/-tg-station/blob/52dfa42eb5100eca9396cf012ad7776dce5e92d8/code/game/objects/items.dm#L319)  is...problematic, to say the least; if someone isn't wearing glasses, a mask, or helmet that covers eyes, someone can just walk right up with a screwdriver or fork and hit stab you in the eye---this isn't inherently problematic except: 

- It has a 50% chance to  paralyzes you for a full cycle and weakens you for 2 cycles
- Has no attack animation or hitsound
-  will Induce permanent blindness after a few hits
- Code for it is ridiculously snowflakey

The 50% chance combined with the weaken duration pretty much guarantees a silent permastun against someone.

As a clumsy side effect its rather humorous, but as a combat tool, it's quite overpowered.

**Comment by CorruptComputer** [comment]
Can we just remove targeting eyes, and instead have it be a random chance when attacking someone's head. Because I agree, this is ridiculously overpowered.

**Comment by WJohn** [comment]
Having the whole "hitting eyes to blind people" should be expanded to far more than just screwdrivers, I'm sure there are PLENTY MORE pointy things to stab with than just these.

**Comment by Fox-McCloud** [comment]
@WJohn 

It's more the permastun I take issue with

**Comment by RandomMarine** [comment]
They need to get 3-5 eyestabs off before any of those effects can occur.

**Comment by Durkel** [comment]
Any type of eye wear or mask prevents the stabbing effect though, Even something that would only cover one eye.

**Comment by Lumipharon** [comment]
This is not a problem. Half the crew wears or has access to eye wear.
And for those that don't, one stab won't stun or blind you. I stabbed a traitor in the eye a dozen+ times before it stunned him, then when he got up he could still see well enough to revolver me across the room.

Clobbering someone over the head is just as, if not better for taking someone out, and doesn't rely on them not having eyewear.

**Comment by Kromgar** [comment]
>This is problematic and triggers me

**Comment by Fox-McCloud** [comment]
@Lumipharon 

One stab won't stun them? With a 50% chance to be weakened for 2 cycles every single eyestab---statitistics say that "yes one stab will stun" 

Compare this to the toolbox's 20% chance to knock down if targeting the chest or 10% if targetting the head; even compared to the idea: esword is 40% chance----and both of these can "miss" their intended target--eystabbing can't.

While it is fairly easy to counter, I'm not sure it's a good thing to encourage players to deliberately seek out specific headgear or glasses just because a single proc is so ridiculously strong.

**Comment by dannno** [comment]
@CorruptComputer 
>wanting more rng in combat

@Lumipharon
You seriously underestimate how powerful it is. Once you stabbed me in the eyes until I was blind because I picked a spellbook up off the ground that was near you while you appeared to be AFK and it fucked me for the rest of that round. (you're a fucking idiot for that by the way, jfc)

This shit is stupid strong. 1-2 stabs to the eyes will blur vision, slow, and possibly knockout the target. If you get 1-3 consecutive stabs on a person, you are practically guaranteed to knock them down and after that killing them is trivial. If they get away, they will have varying degrees of fucked up vision that require surgery.
As someone who has used this since as far back as I can remember, I can say that it is absolutely the best melee option against anyone with a mask/glasses barring eswords.

it's also just inconsistent as fuck

**Comment by Lumipharon** [comment]
Speaking of which, that is (what I think) is the major issue.
There is NO feedback what so ever, when eye stabbing. That time I stabbed you in the eyes, was because I kept chasing you trying to stab you, but I thought I wasn't connecting because I didn't get any message/animation - until you started bleeding everywhere.

**Comment by PKPenguin321** [comment]
Consider moving your feedback here: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3151

**Comment by dannno** [comment]
what kind of world is it where someone suggests posting on the forums instead of the github in the hopes of getting something changed

**Comment by PKPenguin321** [comment]
>what kind of world is it where someone wants the wider playerbase to have a say in things instead of letting coders do whatever the fuck they want

**Comment by dannno** [comment]
i'm not saying it's a bad thing
i'm just shocked

**Comment by Dorsisdwarf** [comment]
Why would this be an issue for player debate?
Goofballs fucking 'LOOK I CAN MAKE SCIENCE GOON' PR is an issue for player debate.
Screwdrivers being buggy and unfair is a minor bugfix for everyone but powergamers.

**Comment by Cheridan** [comment]
working as intended

**Comment by dannno** [comment]
:|
