### ISSUE TITLE
Changeling flesh mass counts as an abiotic item for the gibber

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#8546]
Obviously it can't be removed so changelings with it activated can't be gibbed.

**Comment by PKPenguin321** [comment]
i'd be okay with this being a feature tbh, nice subtle buff
and either way cremation should still work

**Comment by WJohn** [comment]
I actually don't mind this, it's a bit of extra insurance and makes the armor even better. This leaves the only surefire way to kill an armored ling the cremator.

**Comment by SconesC** [comment]
it's pretty funny how lings can activate/deactive this while cuffed, I had one who kept doing it while we dragged them in and out of surgery

**Comment by Amnestik** [comment]
The mass is clearly biotic though, so logically it should be allowed by the
gibber. It doesn't make sense and is misleading to players otherwise.

I'd suggest either changing the message when a body is rejected to refer
the bulk of the corpse rather than whether it's completely biologicor allow
flesh mass changelings to be gibbed. I'd prefer the latter personally, if
you've been dragged to the gibber it's because you failed every chance you
had to escape.

**Comment by Amnestik** [comment]
*biological or

**Comment by Dorsisdwarf** [comment]
>failed every chance you had to escape

That's not a synonym for 'didn't take monkey, misclicked, assistant unzipped stunprod'

**Comment by Miauw62** [comment]
If we assume jumpsuits are cotton they're biological too.
Anyway this is annoying to fix and the armor is supposed to be superstronk,
the space suit is so bloated it doesn't go in.
Op 26-mrt.-2015 14:35 schreef "Dorsisdwarf" <notifications@github.com>:

**Comment by WJohn** [comment]
Maybe don't allow people who wear exosuits to be thrown in? The vast majority are very bulky.

**Comment by KorPhaeron** [comment]
@tkdrg 

Shield mass is abstract, and abstract is ignored for abiotic. Someone fixed this at some point
