### ISSUE TITLE
You can monkify dead corpses in the Genetic Scanner bypassing nuke ops unremovable hardsuit

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#8606]
SERIOUSLY HOW CAN YOU TURN A DEAD BODY INTO A MONKEY? You can't use SE's to change dead bodies so why should the scanner not do the same?

**Comment by stapler2025** [comment]
:salt:

https://github.com/tgstation/-tg-station/issues/8565 dupe

**Comment by Lumipharon** [comment]
Literally all these issues would be non existant if ops just HAD THEIR EXPLOSIVE IMPLANTS BACK.

Exactly one person didn't like them, seriously, loot pinatas every nuke op round.

**Comment by Prickly-Cactus** [comment]
how can you live with this salt

**Comment by Marflowerose** [comment]
The only iffy part I had about nuke op explosive implants was that half the time people didn't know how to use it. With the new implant icons, that shouldn't be a problem. 
To the orginal post: IMO it works as intended, DNA injectors work on living and not dead because they don't have working circulation to spread the DNA mutator fluid whereas the scanner can be assumed to use more robust methods of altering DNA that don't rely (solely) on blood circulation.

**Comment by Supermichael777** [comment]
if i recall my history corectly this is one of the bugs thats been around sense before cloning
