### ISSUE TITLE
Liquid dark matter and sorium behave strangely, and other goofchem things

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#8647]
Not really a bug, it just works wierdly.

When they activate, they pull/push basically everything, but it's not like when you throw stuff - things just kind of, teleport to their new location and that's it.

I don't know if that's what's actually happening, or it's just a visual thing, but it looks wierd.

Also foam and smoke are pretty fucked up now.

Smoke is really bad now, because it transfers its reagents then becomes immediately useless.
While death smoke was arguable way too strong, that was more of an issue with certain chemicals (namely acid and mutagen that are super deadly specifically because of the 20+ TOUCH effects the smoke would proc just by going anywhere near the smoke, not the reagents itself, as seen by: (almost) any other death smoke, not actually being ggnore insta death.

Foam on the other hand, will just keep applying its full quantity of reagents every single tick, leading to hilarious things like me making grenade that put enough black powder in everyone that touches it to gib them and anything near them.

And speaking of blackpowder, after you mix it (or heat the stabilised version) you get the 'sparks an reacts violenly message, but it doesn't actually explode for a good 3 seconds. This is kind of dumb, for obvious reasons, and whenyou have it in grende form, the grende visually sits there for a bit after activation, before the actual boom happens.

Is this delay intended?

**Comment by Incoming5643** [comment]
Sorium blob is also weird because since the chem is in the mob, it pushes everyone away from the attacked person, but the attacked person themselves goes nowhere because it's the epicenter.

**Comment by Iamgoofball** [comment]
Foam can be fixed to use up reagents on people who enter it.

Black powder delay is intentional. It's not getting removed.
use nitro and water potass for grenade explosions, use black powder for "inject into someone and then blow them up at a later time" due to the intentionally slow metabolism rate on BP.
ps. You dont need stabilizer for it, it out right doesn't explode until it reaches 474K.

I can change LDM to use throw_at but there's no throw_away proc for sorium to use.

The blob issue is probably because of using orange. I'll check it out.

Smoke's getting a rewrite in the future that will make it more useful.

**Comment by RemieRichards** [comment]
@Iamgoofball for a throw_away style effect, look at how I did item throwing in explosions, you just find an edge_target_turf() (it's something like that) in the direction of the epicentre to the tile in question.
