### ISSUE TITLE
Plasma Cutter is out of control

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8747]
@ACCount12 

This thing has made mining mechs way too strong, they do too much damage to people and are way too efficient ammo-wise. It is almost to the point of being a critical balance concern. The Ripley is now a robust as fuck combat mech instead of a reliable cargo/engi/miner mech.

Also the pulse rifle sound needs to go

**Comment by WJohn** [comment]
I like how instead of nerfing the kinetic accelerator to stop the 26,000 point miners 30 mins and buffing the other items a bit, we only just saw a GIGANTIC buff to everything else.

Power creep everywhere.

**Comment by PKPenguin321** [comment]
i think it's hilarious
give eswords to miners at roundstart for "fighting mining mobs" when

**Comment by ACCount12** [comment]
How to balance that shit? Make plasma cutter slower, make it use more power, add projectile gun-like reload?

**Comment by WJohn** [comment]
Or really just nerf all of mining.

**Comment by ACCount12** [comment]
nerf is bad and you should feel bad for suggesting it

Nerf is NOT solution to every single balance issue.

**Comment by Lumipharon** [comment]
drill needs to lose the power requirement since they're literally useless, and the KA needs to be nerfed.

Seriously, 2 miners can DESTROY THE ENTIRE ASTROID in 30-50 minutes, it's hilariously fast.

As for the plasma cutter, 1 miner with a KA is like, x5 faster then a guy/ripley with a plasma cutter, without the energy/ammo requirement. It's too robust as a gun though, it's literally just an smg that doesn't need a firing pin that you can carry around essentially infinite ammo for, with slightly limited range. But it can melt walls and shit.

**Comment by Miauw62** [comment]
>thing is too powerful, to the point of making utility mech better than
combat mech
>nerf is not the solution

???
Op 5-apr.-2015 06:48 schreef "ACCount" <notifications@github.com>:
