### ISSUE TITLE
Out of game stat gathering is tied to an ingame object (the blackbox)

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8799]
I know we aren't even using the SQL stats right now but this just too bizarre not to point out:

In tcomms there's a machine called a blackbox recorder, it's an unassuming thing that doesn't even have a desc and offers no functionality with anything in game.

However when the game ends the code checks to see if the blackbox recorders survived the events of the round, and if it didn't no stats will be reported for the round. There's a survivibilty system for the blackbox to never truely die, but why even have it like this?

It's a nice little bit of flavor but also so fucking ridiculous I can't even believe it's apparently survived the ages up until this point.

**Comment by Amnestik** [comment]
I... why

**Comment by Memendia** [comment]
Never knew this

**Comment by Miauw62** [comment]
I thought this only recorded stats on radio use. You'll find a section
recording radio chatter in broadcast_message()
Op 7-apr.-2015 09:24 schreef "Ben Colman" <notifications@github.com>:

**Comment by Lumipharon** [comment]
That's hilarious, and explains so many things.

**Comment by Niknakflak** [comment]
If the blackbox is destroyed, another is spawned on centcom automatically.  Stats are always recorded, at least this is what I was told.

**Comment by Amnestik** [comment]
Why does it even exist




Why does stat tracking rely on its existence

**Comment by Incoming5643** [comment]
@Niknakflak 

![d10_icon](https://cloud.githubusercontent.com/assets/4176358/7028149/fe55549a-dd21-11e4-957a-5391e2e59336.png)

Yep: if the blackbox is destroyed it appears floating on the corner of reality in the void of centcom space.

So it DOESN'T effect stat tracking (probably), but it's STILL wacky as hell.

**Comment by Niknakflak** [comment]
Well I knew it respawned somewhere.

**Comment by AnonymousNow** [comment]
We should beef up the blackbox sprite and make it truly indestructable for flavour purposes.

**Comment by balohmatevz** [comment]
This was done simply because it sounded cool - having an ingame object which could be interacted with, which contains the statistical data. Unfortunately this fact sort of faded from common knowledge, as did the fact that the blackbox contains the whole round's chat logs. 

Now, whether the object that contains this data is on the game world or not is identical from a technology standpoint. If you think it's cool to have this object ingame, that's fine, if you think it's lame that's fine too. As to whether or not feedback should be decoupled from the blackbox object... well it makes no difference at all. It'd just be extra work for whoever does it, which risks breaking something. Personally I would recommend this isn't done simply because it presents some risk for no benefit, as well as because this open issue encourages someone to spend time on this - time they could be spending on something that actually has some benefit.

All in all, the way this was done is different, but not inherently worse than the more standard abstract object way.

**Comment by Amnestik** [comment]
Isn't the issue that it can be destroyed, leading to inaccurate stat reporting?

**Comment by balohmatevz** [comment]
No, it's recreated before it's destroyed and all the contents are cloned. It's recreated in its Del() function. I actually don't think it's possible to delete it at all - by anyone. Cause if it fails to create a new blackbox (say you somehow deleted z-level 2), then the current one is not deleted, since Del() runtimes before it reaches the point where the current one gets deleted.

**Comment by Incoming5643** [comment]
yeah it stopped being an issue once I realized it recreated itself, I just was bamboozled when I saw what was effectively "roleplaying code".

There's no intrinsic bug to it, it's just different.
