### ISSUE TITLE
spider player spawning

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#8861]
I didn't really follow the whole story, but a guy said that he was a spider and spawned as another spider and some other guy died as  a changeling and before he could heal, he was spawned as a spider, which made him upset.

SKITTER SKATTER

**Comment by RemieRichards** [comment]
so the bug here is that spider spawning does not ask the user.

**Comment by xxalpha** [comment]
The round that just ended had a billion player controlled spiders. It's kinda terrible having sentient spiders because they're so strong and it's even worse when they are spawned very fast and in great numbers.

There was nothing the crew could have done.

**Comment by Lumipharon** [comment]
Spiders have two issues.

1: Their bite transfers some assrape McGee toxin, which will basically kill you with a few bites, regardless of armor. It's also harder to deal with because toxin damage.

2: Spiders reproduce retardly fast. A queen shits out like 10 spiderlings per corpse, and they fully grow super fast - they make xenos look like a complete joke in comparison.

**Comment by Anonus** [comment]
The toxin was previously pretty weak; it probably wasn't adjusted for goonchem so yell at goofball.
Spiders reproduce like 4-8 spiderlings per corpse, but if the corpse somehow is removed from the cocoon, it can be used to spawn more spiderlings, which is probably bad.

**Comment by xxalpha** [comment]
It was never weak, I don't know how it is with goonchem, but before it was pretty strong, so much that fighting one spider required immediate anti-toxin to not die.

**Comment by Incoming5643** [comment]
Player spiders spawn player spiders, and they run on the same rules as xenos, namely anyone with be_alien is fair game without a prompt. There were just so many spiders (because the xenobiologist fed the starting spider like 10 monkeys) that dead chance was instantly and constantly converted to spiders. So it's not technically a bug so much a balance issue as it was so very easy to drown the station in spiders.

**Comment by Jalleo** [comment]
@iamgoofball do you know what chem the spiders use?

**Comment by Iamgoofball** [comment]
I'll check it out, but use charcoal and shit to purge and heal tox damage. Calomel can get it out of you fast if need be.

**Comment by AlexCrimson** [comment]
Doesnt it depend on the spider? I always thought the purple-eyed ones(hunters) injected more toxin, but that was the whole point. They have really low health though.

Also all events/spawn mechanics that pull from ghosts/deadchat should require a prompt before doing so. This imo should be a required thing. It would stop new players from being the "first" one and letting everyone down, and let people decline the antag role rather than be forced into it just for having their preferences set to "on".
