### ISSUE TITLE
Spray can stuns are OP as fuck

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#8871]
The have no eye/mouth protection checks, and work from range.
The spray can has limited ammo, but this ammo ONLY is used for making graffiti. not stunning mobs.
So the spray can is an infinite ranged stun device for revheads.
@sawu-tg

**Comment by sawu-tg** [comment]
This is an oversight, I forgot to add consuming ammo whilst stunning. Working from a range shouldn't technically be possible (its most likely just lag) because it uses after_attack or whatever.

Also it's paint. Paint will cover literally any surface (so spraying a helmet would still blind a person by covering the visor).

I'll fix the chain-stuns in a upcoming patch to spraycans.

**Comment by Lumipharon** [comment]
blinding a guy with glasses/helmet wouldn't be the same as spraying directly into their eyeballs.
ie: Flash vs stun baton to the mouth.

**Comment by Kelenius** [comment]
Actually, afterattack can work in the distance, it has a proximity flag that needs to be checked to make sure it's applied in melee.

**Comment by sawu-tg** [comment]
@Kelenius  I noticed that, I thought I was checking proximity, but I wasn't. 
@Lumipharon I'm nerfing spraycans in a following patch that will also fix some bugs.

**Comment by stapler2025** [comment]
can we please just remove these griffcans?  I don't want people to have easily accessible stuns that change how I look.

**Comment by Iamgoofball** [comment]
@stapler2025 did your eyes just block out the part where he says he's fixing it?

**Comment by stapler2025** [comment]
i went to school in a small town, I no read gud
