### ISSUE TITLE
BLACK POWDER CAUSES INFINITY EXPLOSIONS AND CRASHES SERVERS

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8945]
@Iamgoofball GOD FUCKING DAMNIT STOP CRASHING THE FUCKING SERVERS

**Comment by Iamgoofball** [comment]
WHAT

I NEED MORE DETAILS AND REPRODUCTION METHODA

**Comment by Miauw62** [comment]
nope this probably is false
there were 200 airhorns and a singulo.

**Comment by Incoming5643** [comment]
Miauw this is a DIFFERENT infinity explosion.

This one happened yesterday and all I could tell is there were two bottle of black powder in an infinitely exploding satchel

**Comment by Miauw62** [comment]
should i reopen this?

**Comment by Incoming5643** [comment]
I feel like this is the more descriptive version of the one that's currently open, but it depends if there's really a seperate bug with this that doesn't use black powder

**Comment by Iamgoofball** [comment]
there's still an infinity explosion?

**Comment by Incoming5643** [comment]
As of yesterday, if you've fixed something since then that isn't live yet, maybe not anymore?

My guess the problem was/is that black powders was being called to explosion in its own recursive explosion. Every time the bag tried to explode it would search in the bag to explode things in it, but since the explosion in the bag was strong enough to destroy the bag, it would start a new call to explode the things in the bag which at this point still contained the already exploding but still capable to explode black powder.

**Comment by Iamgoofball** [comment]
okay that's something I can test

**Comment by Iamgoofball** [comment]
@Incoming5643 can't reproduce
