### ISSUE TITLE
Wizard Mirror Mutantrace Problems

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/-tg-station#8981]
Wizard mirror was added as a cosmetic thing, but several mutantraces have actually ingame effects.  The obvious one is shadowling, which is currently selectable by wizards and will cause wizards to be harmed by light, and healed and made stunproof in shadows, but there are also slimemen, whose slimejelly metabolism can kill the wizard if they should switch between races after switching to slimeman, and possibly other effects.  It might be a good idea to give the mirror a whitelist or a blacklist, and to make the code that switches between mutantraces a bit more robust for things like exotic blood.

**Comment by Incoming5643** [comment]
Before anyone says "YOU LET THEM BE SHADOWLINGS?!"

It's only the light mechanic, because of how shadowlings operate the wizard version gains no abilities nor any armor with special properties. Frankly it's a hidiously bad idea to take it and fit only for huge gimmick wizards, because if you don't leave the den immediately you'll burn to death in the perma light.

The "slime jelly poisons people to death" thing however is something I've known about and been meaning to get around to.

**Comment by PKPenguin321** [comment]
How about just fixing it so when you're a slime person and changed into a different race it purges all the poison from you

**Comment by Incoming5643** [comment]
that's probably the plan

**Comment by WJohn** [comment]
I personally don't see a problem with being able to get powerful toxins as a slime person, I find it very unlikely that a wizard is going to use that for a syringe gun, and even still he has tons more abilities to screw the crew over with than that. Besides, he's a non human now, so the AI and borgs  can just murder him anyway.

**Comment by Incoming5643** [comment]
it's not that he uses it, it's that if he goes from a slime person back to something else via the mirror or other nonmagical means the slime toxin is still in his body and will almost certainly end up killing him

**Comment by WJohn** [comment]
Ah, I see the problem now.

**Comment by Incoming5643** [comment]
The parts of this one I considered an actual bug was fixed in #9129
