### ISSUE TITLE
#8067, but the other way around...

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#9051]
Basically this #8067 , but reverted. Golems are now hulks, weakening everyone they punch.

Be golem
Punch someone
Every punch is a weaken

Happened on yogs, didnt test it on my own server, yogs updated their code two days ago i believe.

**Comment by Jordie0608** [comment]
Golems weaken with around half their punches actually. Any punch that does at least 9 damage weakens the target and Golems add 5 damage onto the default of 0 to 9 damage. However because BYOND RNG is dumb it seems like they weaken more often than that.

I gathered up some opinions and the general consensus was this was ~balanced since Golems are considerably slower than humans and can't wear any clothing.
