### ISSUE TITLE
Mulligan is insane

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#9105]
When a blob round mulliganed into traitor+changeling, almost EVERY SINGLE PERSON spawning after the mulligan became an antag. In fact:

1. Out of 69 crew members 23 were antags (including the original blob), 12 were both traitors and changelings (in the config, traitor scaling is 7 and changeling scaling is 8).

2. Implanted people (security officers, HoS) became antagonists too despite the config option forbidding it.

**Comment by WJohn** [comment]
@Incoming5643 
The ride never ends.

**Comment by Dorsisdwarf** [comment]
Welcome to fightvale

**Comment by Incoming5643** [comment]
You're always more apt to become some sort of antag in traitorling because you essentially get to "roll twice", first for the ling, then for the traitor.

I can already see a problem in make_antag_chance() where it just assumed ticker.mode was the same as src (but to be fair when it was written that was true). That explains the restricted job antags.

It doesn't solve the apparent glut of antags. Here are the rolls for ling in traitorling

if(changelings.len <= (changelingcap - 2) || prob(100 / (config.changeling_scaling_coeff * 4)))

where changelingcap is

min( round(joined_player_list.len/(config.changeling_scaling_coeff*4))+2, round(joined_player_list.len/(config.changeling_scaling_coeff*2)) )

which given the numbers you gave me (thanks) means that changelingcap was 4. Therefore it must be that antags aren't added to changelings.len before the other calls of  make_antag_chance() finish, and since there were less than 2 people in changeling.len (at least for a lot more than the intended 2 people), a ton of people got antag. Probably a similar case in traitors.

Not sure why this bug only manifest now, maybe configs for changelings/traitors were lowered recently? In any case will fix ASAP.
