### ISSUE TITLE
Buckshot is very weak

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/-tg-station#9118]
15 damage pellets x 5 pellets = 75 damage in the best case, 15 damage less than the shotgun slug.  With the spread, you'll only hit with all 75 damage if it's point-blank range, and if they're 3+ tiles away, you'll probably hit with 2 or 3, for 30-45 damage, bringing you up to 3-4 shots required to crit.  Compare that to 60 damage, no questions asked.  Two shots and they're down.

Even in cases where the buckshot's supposed to excel, when you're fighting multiple people and all the pellets are likely to hit someone regardless of the spread, you're still probably better off with slug shots, because you'll be doing only very slightly less damage total, and you'll be downing someone in the crowd every other shot or so, rather than leaving everyone relatively unhindered until you've fired off your fifth or sixth shot and they start dropping.

This is especially important because nuke ops  start off with buckshot.

**Comment by WJohn** [comment]
I think buckshot is fine as is, as its spread is nice against retreating enemies. Perhaps add a shotgun slug that does the 60 damage of old without any spread?

**Comment by AlexanderUlanH** [comment]
There *is* a shotgun slug that does 60 damage without any spread.  It's the shotgun slug you can print off at a hacked autolathe.
If you're fighting a fleeing enemy who's gotten any decent amount of ground, you're probably going to be doing floor tile level damage.  Even though it's a nearly guaranteed hit, that's a very, very specialized application of a shotgun that could be critting your fleeing enemy in two shots.  The numbers just aren't there to make buckshot something you'd want to load into your shotgun, and they definitely aren't there to make the bulldog something you could go toe to toe against security with.

**Comment by Lumipharon** [comment]
It works very well in tight corridors like maint, since it doesn't spread.

Also fun fact: If you click far away from you to shoot, the pellets spread less then if you click close to you.
This works for all spread weapons.

Overall it's not that good though.

**Comment by Marflowerose** [comment]
I think lower damage is a tradeoff for the increased chance to hit, especially since we now have bleeding effect so even if you don't shoot at point blank, the target will probably start bleeding. I don't see why the damage couldn't be identical, though I'd still prefer there to be some bonus for the slugshot since it is inherently more "skill shot". Perhaps high chance to penetrate and continue its merry way to targets behind or something.

**Comment by AlexanderUlanH** [comment]
>If you click far away from you to shoot, the pellets spread less than if you click close to you.

I actually found that the exact opposite happened when I tested it.  I got 0-3 hits clicking on a target 7 squares away compared to a pretty consistent 4 clicking the nearest square in his direction.  (Mind, using that technique to get up to 60 total damage is only possible if your target is standing in a perfectly straight line from you.)
Also, the pellets did spread when I tested the shotgun in maint.  Try firing a shotgun down a windowed maint tunnel- you'll break the windows.

**Comment by Supermichael777** [comment]
buckshot really is worthless due to that spread. 5 meters at 7 meters is the kind of spread you get from anti-personel mines not shotguns. normally complaining about the lack of realism would be laughable but here the lack of realism just makes the weapon unnecessarily shitty. also what kind of wizard can control the spread of their shot.
However the core issue is that pellets are based on the outdated combat system from before bleeding.
With bleeding they have a potential use; causing heavy bleeding on a group of people. Heavy bleeding damage might make them more viable for fighting the tide of validhuntes who inevitably come for their chance to trip some red.

**Comment by AlexanderUlanH** [comment]
Bleeding made added to work seamlessly with the existing combat system by basing it on brute damage taken; pellets will cause bleeding normally if they do enough damage, they just don't do enough damage.

**Comment by WJohn** [comment]
The shotgun system IS kind of really dumb, too. The ability to shoot more accurately by firing at long range than short range makes no sense (from a gameplay perspective), and it really should perhaps not even spread at all for the first 3 tiles or something, so very close up all the pellets would still be together and very much deadly.

**Comment by WJohn** [comment]
This is mostly resolved now that buckshot and rubber shots have 6 pellets. The other part, of course, is fixing the broken cone spread.
