### ISSUE TITLE
NPC pool is lagging the server to shit.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9125]
![](http://i.imgur.com/cwiMmPm.png)

This is immediately fixed and the server is suddenly fast again as soon as all bots are deleted.

Could be the reason behind #9031.

@sawu-tg pls man.

**Comment by sawu-tg** [comment]
A single picture doesn't help.

Was there runtimes?

What NPCs/bots did you have spawned, and what were they doing?

NPCPool doesn't lag like this unless something has gone wrong.

**Comment by WJohn** [comment]
It seems to do this pretty much every round. Mulebots as of late have been acting really weirdly with their pathing, and I wouldn't be surprised if floor bots were responsible for it too since this stopped acting up when we deleted it.

**Comment by sawu-tg** [comment]
![performance](https://cloud.githubusercontent.com/assets/3829126/7291216/70c2d588-e9d0-11e4-81d1-d8f5d23d2ebf.PNG)

Testing out a bunch of things and this is the highest result I can get with far more things in the pool.

I will need performance logs and actual situations, because as far as I can tell, it's not NPCPool, it's someone using something else wrong that is cascading over to NPCPool.

**Comment by Jordie0608** [comment]
Can confirm bots were causing this a few days ago. A bunch of ED-209s were made (along with medbots, floorbots etc.) and one of them ended up in nullspace somehow, it was still trying to path to the station and lagging stuff out; deleting all the bots alleviated this.

**Comment by sawu-tg** [comment]
@Jordie0608 How did it end up in nullspace? That's silly.

**Comment by Jordie0608** [comment]
Not a clue I'm afraid.

**Comment by sawu-tg** [comment]
Sounds like an issue with botcode more than my code. No doubt the issues with bots are causing problems elsewhere too, and it's just most prevalent with NPCPool because of the frequency it checks them.

If no underlying fix is made for bots then i'll throw in a bunch of checks and extra rough list purging.

**Comment by Jordie0608** [comment]
HELP: Jyxpe/(Kadence Woodworth) (?) (PP) (VV) (SM) (JMP) (TP) : Sticky, all bots are responding to the summon of one bot 
Reply PM from-Jyxpe/(Kadence Woodworth): I saw it yesterday very clearly as AI. I sent a cleanbot to one location. All other bots rocked up too.
Reply PM from-Jyxpe/(Kadence Woodworth): And currently the mulebots keep chasing after a cleanbot

**Comment by sawu-tg** [comment]
@Jordie0608 

That is.. technically intentional.
Bots are supposed to come help each other but I didn't add any differentiation between bots. That kind of causes a bunch of them to just scoot down to the location.

**Comment by Miauw62** [comment]
@gunhog you need to talk to sawu i think

**Comment by optimumtact** [comment]
It's not the pool technically, it's the A* pathing and the checks it does, MSO did some profiles, i'll try to dig them up

**Comment by chimersable** [comment]
Could this effect slime follow and stay commands like in issue #9128 ? Seems like symptoms of the same problem.

**Comment by sawu-tg** [comment]
@chimersable Slimes do not use NPCPool, #9128 is a problem with switches or something.

**Comment by WJohn** [comment]
This doesn't seem relevant anymore, bots have not lagged stuff in a long time.
