### ISSUE TITLE
Construction changes are unwarranted and not fun

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9332]
Seriously, there was never even an opportunity to provide feedback on them, just "We're adding this for /consistency/"

They're fucking awful. Going blind moving machine frames, having girders be a huge pain in the ass - It's not fun, it just adds mindless tedium to the game. I don't think anybody cares about this being 'realistic' or whatever, or 'consistent' -  This was actually a pretty big change and I've heard nothing but negative feedback on it.

Revert this shit. Put a poll up or whatever but GET. IT. OUT.

**Comment by Anonus** [comment]
Change it to crowbar to unanchor and wrench to decon for all of the things. It shouldn't have a welder anywhere in there it's awful to need a welder to deconstruct anything.

**Comment by SconesC** [comment]
Anything but welders.

There is no public welding gear (presumably to prevent anti-rev powergame?) which only makes this so much worse.

**Comment by Supermichael777** [comment]
ask or steal from cargo.most cargo techs are bored enough to hand that shit out like candy.

**Comment by Marflowerose** [comment]
One roundabout solution would be to have new item, a piece of square darkened glass. When held in hand while welding, would greatly reduce the blinding effect but not to the extent welding masks do. It would make the welding more convinient while also being less convinient than a proper welding mask since you'd need to hold it in hand while welding and you'd still go blind after excessive use. It could possible also be constructed into an improvised welding mask that would work as well as the darkened glass but could be worn but not tilted up/down like welding mask can, owing to it being improvised.

**Comment by KorPhaeron** [comment]
I'm in complete agreement with Scones and posted as much in the PR feedback. I think this is a case of trying too hard to stop powergaming to the point where legitimate station activity is taking a massive hit.

I mean if you want players to be doing stuff other than killing each other, making construction tedious and awful is not the way to encourage it.

**Comment by PKPenguin321** [comment]
THIS IS EXACTLY WHAT I WAS SAYING ON THE ORIGINAL PR AAAAAAA

**Comment by chimersable** [comment]
What was the approval process for the change? Seems like changing big game mechanics is way too easy and lacks oversight.

**Comment by optimumtact** [comment]
>big game mechanics

it's just a construction recipe you doofus
