### ISSUE TITLE
Incinerator room is accessible with default maintenance access.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9390]
It should be limited to engineering general or perhaps atmos tech only.

**Comment by Ikarrus** [comment]
It's always been like this since forever? This is closer to a request to an actual issue.

**Comment by Marflowerose** [comment]
If we're talking about the turbine room that is called incinerator for some reason, I too find it odd that assistants have free access to a plasma/superheated gas canister. Sure, hardly anyone ever uses it and it has been like that since forever but that shouldn't be a reason to keep it like that when it's clearly atmos/engineering area.

**Comment by Jordie0608** [comment]
I don't really see a problem with this.

**Comment by Miauw62** [comment]
its called incinerator because it used to be a ghetto toxins lab

**Comment by EchoFade** [comment]
Are we talking about the room with the turbine generator? That you can pump in plasma from atmo? (the one to the right of engineering/atmos)

 or are we talking about the old incinerator (the one to the left of engineering/atmos) that no longer is mapped to properly work like an actual incinerator for some bizarre reason?
