### ISSUE TITLE
Virology stimulant culture seems to be broken

### ISSUE THREAD

**Issue by RocKeD** [tgstation/-tg-station#9485]
Whenever I get stimulant and inject myself with it, and after waiting until it gets to stage 5 I do not seem to move faster like it used to be. From what I can tell its the same speed as normal running. However it does seem that I am faster with a space suit equipped still.

**Comment by PKPenguin321** [comment]
It got changed (I *think* by goonchem) so that instead of making you sanic fast, you are immune to any possible speed debuffs (damage, hunger, spacesuits, legcuffs, etc.). This is technically a non-issue as this is intended behavior.

**Comment by RocKeD** [comment]
Ah, well that is disappointing. In my opinion there should be a speed buff as it is called stimulant. Was it changed to where there are no speed buffs anymore?

**Comment by Marflowerose** [comment]
Yeah, stimulant symptom only prevents speedloss, as is intented. If you want to go fast, you need meth. I think it's a better balance to have direct speed increase come with drawbacks while the symptom is more of an ease to people in hardsuits. 
Side note: Stimulant doesn't really require any work to get since you get it from Unstable Mutagen that you can just print out from chemistry.

**Comment by RocKeD** [comment]
But it does take work, out of all the symptoms you can get it seems, stimulant is one of the most difficult. It will take me at least 15-30 minutes of "grinding" symptoms for me to make a "super virus" if you went with stimulant alone this time might drop but either way its not all that easy.
