### ISSUE TITLE
Feature Request: Actual 'Local Sound'

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9595]
Currently the play local sound button plays a sound for people in an area, and it will follow them out of the area

I was sort of hoping that it would just play in the area that it was played and not chase me to the ends of the earth.

**Comment by Incoming5643** [comment]
All sounds act as if their physical source doesn't change throughout the whole sound because the whole sound is delivered at once. One exception to this rule is that a "sound" actually made of many sounds in a row (instruments) will have better spacial tracking.

Doing this would require a Doppler effect system, which would be cool but I'm not sure if its practical.

**Comment by xxalpha** [comment]
Talking out of my ass here, but might be impossible to implement it properly because byond.

**Comment by tgstation-server** [comment]
No it can be done, but world require hooking into movement code and giving
it it's own channel

**Comment by xxalpha** [comment]
How expensive would it be?

**Comment by Dorsisdwarf** [comment]
@Cheridan Feature Request tag

**Comment by RocKeD** [comment]
Probably a lot more expensive than what it is worth.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
