### ISSUE TITLE
Stripping glitch.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#9635]
>Assistant has staff of door creation on their back.
>Two officers strip the staff at mostly the same time.
>Two officers both end up picking up a staff each somehow, or at least the examine and onmob sprite seems that way.

However, the item wasn't cloned.

**Comment by phil235** [comment]
That's because the stripping proc doesn't check whether the item is still on the target mob after the time delay: https://github.com/tgstation/-tg-station/blob/1875f3a9c22af350ce42556191d441f50429626a/code/modules/mob/living/living.dm#L704 . So the target mob calls Unequip(item) after the first officer has picked up the item which changes the item's location to be at the feet of the target. So the real staff is in the hands of the second officer.

**Comment by phil235** [comment]
Fixed, by me, in some PR...
