### ISSUE TITLE
Spears, etc. can become embedded in adamantine golems

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9726]
the spear embeds itself in Adamantine Golem (88) (as Adamantine Golem)'s head!
You hug Adamantine Golem (916) to make him feel better!
Adamantine Golem (437) says, "How the fuck is there a spear in your head"

isn't part of the point of golems that they are made of stone and immune to things like this, how is an assistant-crafted makeshift spear strong enough to PIERCE ADAMANTINE

**Comment by Supermichael777** [comment]
For the same reason glass shards hurt their unshorn feet: they are a crappy human knockoff with poorly implemented no-drop invisible gear which they don't get because someone made it so they couldn't wear gear at all instead of having it welded to their bodies.
because they are a child of humans in the code they use the same damage model which only checks the throw-force of the projectile and target armor and they are technically unarmored

**Comment by Incoming5643** [comment]
Golem armor was made intrinsic a while back, and someone put in a flag for the glass shards things a while ago.

Someone, maybe me, could expand the flag to be "pierce resistant" pretty easily
