### ISSUE TITLE
Meteors cause a inordinate amount of lag.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9746]
Larger scale meteor events will bring the server to a near standstill while meteor rounds will actually crash the server.

As cool as the meteors are, they need to not lag so goddam badly.

**Comment by stapler2025** [comment]
#blamefastmos

**Comment by TheVekter** [comment]
Coderbus reckons it's got to do with the meteors causing multiple explosions, instead of just blowing up when they hit something dense.

It's a bit above my head, so hopefully we can get it sorted out.

**Comment by phil235** [comment]
Actually, part of the lag is due to meteor debris being thrown in space. Combined that with our current issue with the space cube often forming a loop and you end up with 200+ debris (the ones from the meteor plus the glassh shards/rods/metalsheet that the explosion throws into space) constantly running the code in the while loop of their throw_at() proc.

**Comment by TheVekter** [comment]
Is there any way to fix that?

**Comment by phil235** [comment]
@TheVekter Yes. We can add a safety check to the throw_at() loop. Also, not throwing the meteor debris (200+ objects during a meteor wave event) will help. I'm working on it
