### ISSUE TITLE
Can't save the DNA of dead people to buffer

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#9851]
The DNA scanners in genetics used to be able to save the DNA of dead people (and in turn, make DNA injectors with their DNA). At some point somebody patched being able to *modify* dead people's DNA and must have removed the ability to *download* dead people's DNA. There's no reason a DNA machine shouldn't be able to do this and it leads to headaches when trying to give someone who was husked their identity back after putting them in a new body.

**Comment by Tokiko1** [comment]
I am pretty sure that husks were never able to have their DNA saved. Still, this makes it impossible for traitors to kill someone and then steal their identity.

**Comment by PKPenguin321** [comment]
That is another big issue with this

**Comment by PKPenguin321** [comment]
somebody please fix this it's so annoying

**Comment by RemieRichards** [comment]
> At some point somebody patched being able to modify dead people's DNA and must have removed the ability to download dead people's DNA. 

Exactly this @Fayrik did it, but he didn't specify *WHY* he did it, or what he was intending to fix (all the issues he put in his PR were fixed by separate lines of code, not this, making it really confusing as to why he did it.

That PR for ref: https://github.com/tgstation/-tg-station/pull/8628

**Comment by Fayrik** [comment]
@RemieRichards Super sorry for that, this was a blanket change to fix people from touching dead people's DNA because this was part of the exploit that was letting people steal nuke op suits.
That set of bug fixes were kind of shit, and this wasn't the only one that I rushed because I couldn't see a better way of working the code.

If anyone can see a better way of working this, please get rid of my shitty work here.
Lets just not return to "QUICK, MONKEY THE DEAD GUYS."

**Comment by KorPhaeron** [comment]
Reply PM from-Jazaen/(Jazaen): Apparently phil rewrote whole thing, and all it took after that was disabling checks marking dead as unoperable. There are separate checks for modification of genes, so you can't stick dead ops inside and get their armour by monkeyfication. See https://github.com/tgstation/-tg-station/issues/9851 for reference
