### ISSUE TITLE
[Feature Request] Add a safer way for admins to remove min pop needed for gamemodes

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#9910]
Currently the only way to force some gamemodes regardless of Pop is to use debug game. However, this also ignores antag requirements, can break things, and spams a bunch of debug information to all the players. It would be nice to have something a bit safer to use for forcing gamemodes where not enough people readied up.

**Comment by Jordie0608** [comment]
In most cases ignoring the requirements for a will cause it to bug out or just not initialize at all; having another way to force gamemodes so won't really overcome that limitation.

**Comment by Stickymayhem** [comment]
Check the lobby, roll extended and start it manually.

What would actually be useful is an easy way to change what gamemode it presently is, so malf/blob/gang/rev actually work to end the round.

**Comment by Iamgoofball** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
@Stickymayhem will look into, doesn't seem like it'd be hard

**Comment by Incoming5643** [comment]
As for this feature, if you often find you're on a server where you want to run a mode at lower pop than is usually allowed you can edit the game mode file and put something on the bottom to make a child game mode with a lower requirement using just something like this:

/datum/game_mode/revolution/lowpop:
	name = "lowpop rev"
	config_tag = "low_rev"
	required_players = 10
	required_enemies = 1
	recommended_enemies = 1

Because it's its own mode and undefined in the config files, it'd never run naturally, but you could force it just like any other mode and it would behave as a rev round that only needed 10 players and only had one head.

Currently there's no way to modify mode datums before round start, because those datums aren't initialized before the game begins.

**Comment by Fayrik** [comment]
I think the biggest issue here is the fact that all nuke-op related features are tied to hard coded if statements that include the nuke-ops game mode.
Want to create a one man nuke-op team in an extended round?
Too bad, they're getting traitor gear instead.

**Comment by Miauw62** [comment]
WELCOME TO GAMEMODE CODE, ENJOY YOUR STAY

**Comment by Incoming5643** [comment]
I WILL TAME THIS BEAST SOME DAY
